.Dd 11 августа 2018 г.
.Dt "AT" 1
.Os
.Sh NAME
.Nm at ,
.Nm batch ,
.Nm atq ,
.Nm atrm
.Nd queue, examine or delete jobs for later execution
.Sh SYNOPSIS
.Nm at
.Op Fl q Ar queue
.Op Fl f Ar file
.Op Fl mldbv
.Ar time
.Nm at
.Op Fl q Ar queue
.Op Fl f Ar file
.Op Fl mldbv
.Fl t
.Sm off
.Op Oo Ar CC Oc Ar YY
.Ar MM DD hh mm Op . Ar SS
.Sm on
.Nm at
.Fl c Ar job Op Ar job ...
.Nm at
.Fl l Op Ar job ...
.Nm at
.Fl l
.Fl q Ar queue
.Nm at
.Fl r Ar job Op Ar job ...
.Pp
.Nm atq
.Op Fl q Ar queue
.Op Fl v
.Pp
.Nm atrm
.Ar job
.Op Ar job ...
.Pp
.Nm batch
.Op Fl q Ar queue
.Op Fl f Ar file
.Op Fl mv
.Op Ar time
.Sh DESCRIPTION
The
.Nm at
и
.Nm batch
коммунальные услуги
читать команды из стандартного ввода или указанного файла, которые необходимо
быть выполнено позже, используя
.Xr sh 1 .
.Bl -tag -width indent
.It Nm at
выполняет команды в указанное время;
.It Nm atq
выводит список ожидающих заданий пользователя, если только пользователь не является суперпользователем; в этом
В случае, все рабочие места перечислены;
.It Nm atrm
удаляет задания;
.It Nm batch
выполняет команды, когда позволяет уровень загрузки системы; другими словами, когда
средняя нагрузка падает ниже 1,5-кратного количества активных процессоров,
или значение, указанное при вызове
.Nm atrun .
.El
.Pp
The
.Nm at
утилита позволяет выполнять некоторые умеренно сложные
.Ar time
характеристики.
с
.Ar HHMM
или
.Ar HH:MM
для запуска задания в определенное время суток.
(Если это время уже прошло, предполагается, что наступит следующий день.)
В качестве альтернативы можно указать следующие ключевые слова:
.Em midnight ,
.Em noon ,
или
.Em teatime
(4pm)
и время суток могут быть дополнены суффиксом
.Em AM
или
.Em PM
для бега утром или вечером.
Также можно указать день запуска задания.
указав дату в форме
.Ar \%month-name day
с дополнительным
.Ar year ,
или указать дату форм
.Ar DD.MM.YYYY ,
.Ar DD.MM.YY ,
.Ar MM/DD/YYYY ,
.Ar MM/DD/YY ,
.Ar MMDDYYYY , или
.Ar MMDDYY .
Указание даты должно соответствовать указанию
время суток.
Время также можно указать как:
.Op Em now
.Em + Ar count \%time-units ,
где могут быть единицы времени
.Em minutes ,
.Em hours ,
.Em days ,
.Em weeks ,
.Em months
или
.Em years
и
.Nm
можно сказать запустить задание сегодня, добавив к времени суффик
.Em today
и запустить задание завтра, добавив к времени суффикс
.Em tomorrow .
.Pp
Например, чтобы запустить задание в 16:00 через три дня, используйте
.Nm at Ar 4pm + 3 days ,
чтобы запустить задание в 10:00 31 июля, используйте
.Nm at Ar 10am Jul 31
и чтобы запустить задание завтра в 1 час ночи, используйте
.Nm at Ar 1am tomorrow .
.Pp
The
.Nm at
утилита также поддерживает
.Tn POSIX
формат времени(смотреть
.Fl t
вариант).
.Pp
Для обоих
.Nm
и
.Nm batch ,
команды считываются со стандартного ввода или из указанного файла
с
.Fl f
вариант и выполнен.
Рабочий каталог, окружение (кроме переменных
.Ev TERM ,
.Ev TERMCAP ,
.Ev DISPLAY
и
.Em _ )
и
.Ar umask
сохраняются с момента вызова.
An
.Nm
или
.Nm batch
команда, вызываемая из
.Xr su 1
оболочка сохранит текущий идентификатор пользователя.
Пользователю будут отправлены стандартные сообщения об ошибках и стандартный вывод от его
команды, если они есть.
Письмо будет отправлено с помощью команды
.Xr sendmail 8 .
Если
.Nm
выполняется из
.Xr su 1
оболочки, владелец оболочки входа получит почту.
.Pp
Суперпользователь может использовать эти команды в любом случае.
Для других пользователей разрешение на использование
.Nm
определяется файлами
.Pa /var/at/at.allow
и
.Pa /var/at/at.deny .
.Pp
Если файл
.Pa /var/at/at.allow
существует, нам разрешены только имена пользователей, упомянутые в нем
.Nm .
В этих двух файлах пользователь считается указанным только в том случае, если он
имя не имеет пробелов или других символов перед ним в строке и
символ новой строки сразу после имени, даже в конце
файл.
Остальные строки игнорируются и могут использоваться для комментариев.
.Pp
Если
.Pa /var/at/at.allow
не существует,
.Pa /var/at/at.deny
отмечено, любое имя пользователя, не упомянутое в нем, разрешено
использовать
.Nm .
.Pp
Если ни один из них не существует, только суперпользователю разрешено использовать
.Nm .
Это конфигурация по умолчанию.
.Sh IMPLEMENTATION NOTES
Обратите внимание, что
.Nm
реализуется посредством
.Xr cron 8
даемон вызвав
.Xr atrun 8
каждые пять минут.
Это означает, что степень детализации
.Nm
может быть неоптимальным для каждого развертывания.
Если требуется более мелкая детализация,
.Pa /etc/cron.d/at
файл можно редактировать и он будет прочитан системным кронтабом, из которого
тот
.Ev SHELL 
и
.Ev PATH
переменные среды наследуются.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl q Ar queue
Используйте указанную очередь.
Обозначение очереди состоит из одной буквы; действительные обозначения очереди
диапазон от
.Ar a
to
.Ar z
и
.Ar A
to
.Ar Z .
The
.Ar c
очередь является значением по умолчанию для
.Nm
и
.Ar E
очередь за
.Nm batch .
Очереди с более высокими буквами выполняются с большей приятностью.
Если задание отправлено в очередь, обозначенную заглавной буквой, оно
рассматривается так, как если бы он был отправлен в партию в это время.
Если
.Nm atq
если задана определенная очередь, будут показаны только задания, ожидающие выполнения в этой очереди.
.It Fl m
Отправлять письмо пользователю после завершения задания, даже если его не было.
выход.
.It Fl f Ar file
Прочитайте задание от
.Ar file
вместо стандартного ввода.
.It Fl l
Без аргументов выведите список всех заданий для вызвавшего пользователя.
Если один или несколько
номера вакансий указаны, перечислите только эти вакансии.
.It Fl d
Является псевдонимом для
.Nm atrm
(эта опция устарела; используйте
.Fl r
вместо).
.It Fl b
Is an alias for
.Nm batch .
.It Fl v
Для
.Nm atq ,
показывает выполненные, но еще не удаленные задания в очереди; в противном случае
показывает время выполнения задания
.It Fl c
Переведите задания, перечисленные в командной строке, в стандартный вывод.
.It Fl r
Удалить указанные задания.
.It Fl t
Укажите время задания, используя формат времени \*[Px].
Аргумент должен быть в форм
.Sm off
.Op Oo Ar CC Oc Ar YY
.Ar MM DD hh mm Op . Ar SS
.Sm on
где каждая пара букв означает следующее:
.Pp
.Bl -tag -width indent -compact -offset indent
.It Ar CC
Первые две цифры года (столетия).
.It Ar YY
Вторые две цифры года.
.It Ar MM
Месяц года от 1 до 12.
.It Ar DD
день месяца, от 1 до 31
.It Ar hh
Час дня от 0 до 23.
.It Ar mm
Минуты часа от 0 до 59.
.It Ar SS
Секунда минуты от 0 до 60.
.El
.Pp
Если
.Ar CC
и
.Ar YY
пары букв не указаны, значения по умолчанию соответствуют текущим
год.
Если
.Ar SS
пара букв не указана, значение по умолчанию равно 0.
.El
.Sh FILES
.Bl -tag -width /var/at/jobs/.lockfile -compact
.It Pa /var/at/jobs
каталог, содержащий файлы заданий
.It Pa /var/at/spool
каталог, содержащий выходные файлы спула
.It Pa /var/run/utx.active
записи входа в систему
.It Pa /var/at/at.allow
разрешить контроль разрешений
.It Pa /var/at/at.deny
запретить контроль разрешений
.It Pa /var/at/jobs/.lockfile
файл блокировки создания задания
.El
.Sh SEE ALSO
.Xr nice 1 ,
.Xr sh 1 ,
.Xr umask 2 ,
.Xr atrun 8 ,
.Xr cron 8 ,
.Xr sendmail 8
.Sh AUTHORS
.An -nosplit
В основном писал
.An Thomas Koenig Aq Mt ig25@rz.uni-karlsruhe.de .
Процедуры анализа времени
.An David Parsons Aq Mt orc@pell.chi.il.us ,
с небольшими улучшениями от
.An Joe Halpin Aq Mt joe.halpin@attbi.com .
.Sh BUGS
Если файл
.Pa /var/run/utx.active
недоступен или поврежден, или если пользователь не вошел в систему на
время
.Nm
вызывается, почта отправляется на найденный идентификатор пользователя
в переменной окружения
.Ev LOGNAME .
Если оно не определено или пусто, предполагается текущий идентификатор пользователя.
.Pp
The
.Nm at
и
.Nm batch
коммунальные услуги
реализованные в настоящее время, не подходят, когда пользователи конкурируют за
Ресурсы.
В этом случае можно использовать другую пакетную систему, такую как
.Em nqs
может быть более подходящим.
.Pp
Указание даты после 2038 года может не работать в некоторых системах.
