.\" $OpenBSD: diff.1,v 1.47 2015/11/24 19:35:41 jmc Exp $
.\"
.\" Авторское право (c) 1980, 1990, 1993
.\" Ректоры Калифорнийского университета. Все права защищены.
.\"
.\" Этот код произведен на основе программного обеспечения, предоставленного в Беркли
.\" Китом Мюллером из Калифорнийского университета, Сан-Диего.
.\"
.\" Разрешение на распространение и использование в исходной и бинарной формах,
.\" с изменениями или без них, разрешается при условии соблюдения следующих условий:
.\" 1. Распространение исходного кода должно сохранять приведенное выше уведомление о копирайте,
.\"    этот список условий и следующий отказ от ответственности.
.\" 2. Распространение в бинарной форме должно воспроизводить приведенное выше уведомление о копирайте,
.\"    этот список условий и следующий отказ от ответственности в
.\"    документации и/или других материалах, предоставляемых вместе с распространением.
.\" 3. Ни название университета, ни имена его участников
.\"    не могут использоваться для продвижения производных продуктов
.\"    без явного предварительного письменного разрешения.
.\"
.\" ДАННОЕ ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЕНО РЕГЕНТАМИ И УЧАСТНИКАМИ «КАК ЕСТЬ», И
.\" ЛЮБЫЕ ПРЯМЫЕ ИЛИ КОСВЕННЫЕ ГАРАНТИИ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ,
.\" ГАРАНТИЯМИ ТОВАРНОЙ ПРИГОДНОСТИ И СООТВЕТСТВИЯ КОНКРЕТНОЙ ЦЕЛИ,
.\" ОТКАЗЫВАЮТСЯ. В НИКАКОМ СЛУЧАЕ РЕГЕНТЫ ИЛИ УЧАСТНИКИ НЕ НЕСУТ ОТВЕТСТВЕННОСТИ
.\" ЗА ЛЮБЫЕ ПРЯМЫЕ, КОСВЕННЫЕ, СЛУЧАЙНЫЕ, СПЕЦИАЛЬНЫЕ, ПОКАЗАТЕЛЬНЫЕ ИЛИ ПОСЛЕДУЮЩИЕ
.\" УЩЕРБЫ (ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ, ПРИОБРЕТЕНИЕМ ЗАМЕЩАЮЩИХ ТОВАРОВ
.\" ИЛИ УСЛУГ; УТРАТОЙ ПРАВА ПОЛЬЗОВАНИЯ, ДАННЫХ ИЛИ ПРИБЫЛИ; ЛИБО ПРЕРЫВАНИЕМ ДЕЯТЕЛЬНОСТИ)
.\" НЕЗАВИСИМО ОТ ТОГО, НА КАКОЙ ТЕОРИИ ОТВЕТСТВЕННОСТИ, ДОГОВОРНОЙ, СТРОГОЙ
.\" ОТВЕТСТВЕННОСТИ ИЛИ ДЕЛИКТНОЙ (ВКЛЮЧАЯ НЕБРЕЖНОСТЬ ИЛИ ИНОЕ)
.\" ОСНОВЫВАЕТСЯ ЛИСПОЛЬЗОВАНИЕ ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ, ДАЖЕ ЕСЛИ БЫЛО СООБЩЕНО О
.\" ВОЗМОЖНОСТИ ТАКОГО УЩЕРБА.
.\"
.\"     @(#)diff.1	8.1 (Беркли) 6/30/93
.\"
.Dd 10 марта 2022 года
.Dt DIFF 1
.Os
.Sh НАЗВАНИЕ
.Nm diff
.Nd сравнение файлов и директорий
.Sh СИНТАКСИС
.Nm diff
.Op Fl aBbdipTtw
.Oo
.Fl c | e | f |
.Fl n | q | u | y
.Oc
.Op Fl -brief
.Op Fl -color Ns = Ns Ar when
.Op Fl -changed-group-format Ar GFMT
.Op Fl -ed
.Op Fl -expand-tabs
.Op Fl -forward-ed
.Op Fl -ignore-all-space
.Op Fl -ignore-case
.Op Fl -ignore-space-change
.Op Fl -initial-tab
.Op Fl -minimal
.Op Fl -no-ignore-file-name-case
.Op Fl -normal
.Op Fl -rcs
.Op Fl -show-c-function
.Op Fl -starting-file
.Op Fl -speed-large-files
.Op Fl -strip-trailing-cr
.Op Fl -tabsize Ar number
.Op Fl -text
.Op Fl -unified
.Op Fl I Ar pattern | Fl -ignore-matching-lines Ar pattern
.Op Fl F Ar pattern | Fl -show-function-line Ar pattern
.Op Fl L Ar label | Fl -label Ar label
.Ar file1 file2
.Nm diff
.Op Fl aBbdilpTtw
.Op Fl I Ar pattern | Fl -ignore-matching-lines Ar pattern
.Op Fl F Ar pattern | Fl -show-function-line Ar pattern
.Op Fl L Ar label | Fl -label Ar label
.Op Fl -brief
.Op Fl -color Ns = Ns Ar when
.Op Fl -changed-group-format Ar GFMT
.Op Fl -ed
.Op Fl -expand-tabs
.Op Fl -forward-ed
.Op Fl -ignore-all-space
.Op Fl -ignore-case
.Op Fl -ignore-space-change
.Op Fl -initial-tab
.Op Fl -minimal
.Op Fl -no-ignore-file-name-case
.Op Fl -normal
.Op Fl -paginate
.Op Fl -rcs
.Op Fl -show-c-function
.Op Fl -speed-large-files
.Op Fl -starting-file
.Op Fl -strip-trailing-cr
.Op Fl -tabsize Ar number
.Op Fl -text
.Fl C Ar number | -context Ar контекст
.Ar file1 file2
.Nm diff
.Op Fl aBbdiltw
.Op Fl I Ar pattern | Fl -ignore-matching-lines Ar pattern
.Op Fl -brief
.Op Fl -color Ns = Ns Ar when
.Op Fl -changed-group-format Ar GFMT
.Op Fl -ed
.Op Fl -expand-tabs
.Op Fl -forward-ed
.Op Fl -ignore-all-space
.Op Fl -ignore-case
.Op Fl -ignore-space-change
.Op Fl -initial-tab
.Op Fl -minimal
.Op Fl -no-ignore-file-name-case
.Op Fl -normal
.Op Fl -paginate
.Op Fl -rcs
.Op Fl -show-c-function
.Op Fl -speed-large-files
.Op Fl -starting-file
.Op Fl -strip-trailing-cr
.Op Fl -tabsize Ar number
.Op Fl -text
.Fl D Ar string | Fl -ifdef Ar string
.Ar file1 file2
.Fl D Ar string | Fl -ifdef Ar string
.Ar file1 file2
.Nm diff
.Op Fl aBbdilpTtw
.Op Fl I Ar pattern | Fl -ignore-matching-lines Ar pattern
.Op Fl F Ar pattern | Fl -show-function-line Ar pattern
.Op Fl L Ar label | Fl -label Ar label
.Op Fl -brief
.Op Fl -color Ns = Ns Ar when
.Op Fl -changed-group-format Ar GFMT
.Op Fl -ed
.Op Fl -expand-tabs
.Op Fl -forward-ed
.Op Fl -ignore-all-space
.Op Fl -ignore-case
.Op Fl -ignore-space-change
.Op Fl -initial-tab
.Op Fl -minimal
.Op Fl -no-ignore-file-name-case
.Op Fl -normal
.Op Fl -paginate
.Op Fl -rcs
.Op Fl -show-c-function
.Op Fl -speed-large-files
.Op Fl -starting-file
.Op Fl -strip-trailing-cr
.Op Fl -tabsize Ar number
.Op Fl -text
.Fl U Ar number | Fl -unified Ar number
.Ar file1 file2
.Nm diff
.Op Fl aBbdilNPprsTtw
.Oo
.Fl c | e | f |
.Fl n | q | u
.Oc
.Op Fl -brief
.Op Fl -color Ns = Ns Ar when
.Op Fl -changed-group-format Ar GFMT
.Op Fl -context
.Op Fl -ed
.Op Fl -expand-tabs
.Op Fl -forward-ed
.Op Fl -ignore-all-space
.Op Fl -ignore-case
.Op Fl -ignore-space-change
.Op Fl -initial-tab
.Op Fl -minimal
.Op Fl -new-file
.Op Fl -no-ignore-file-name-case
.Op Fl -normal
.Op Fl -paginate
.Op Fl -rcs
.Op Fl -recursive
.Op Fl -report-identical-files
.Op Fl -show-c-function
.Op Fl -speed-large-files
.Op Fl -strip-trailing-cr
.Op Fl -tabsize Ar number
.Op Fl -text
.Op Fl -unidirectional-new-file
.Op Fl -unified
.Op Fl I Ar pattern | Fl -ignore-matching-lines Ar pattern
.Op Fl F Ar pattern | Fl -show-function-line Ar pattern
.Bk -words
.Op Fl L Ar label | Fl -label Ar label
.Op Fl S Ar name | Fl -starting-file Ar name
.Op Fl X file | Fl -exclude-from file
.Op Fl x Ar pattern | Fl -exclude Ar pattern
.Ek
.Ar dir1 dir2
.Nm diff
.Op Fl aBbditwW
.Op Fl -color Ns = Ns Ar when
.Op Fl -expand-tabs
.Op Fl -ignore-all-blanks
.Op Fl -ignore-blank-lines
.Op Fl -ignore-case
.Op Fl -minimal
.Op Fl -no-ignore-file-name-case
.Op Fl -strip-trailing-cr
.Op Fl -suppress-common-lines
.Op Fl -tabsize Ar number
.Op Fl -text
.Op Fl -width
.Fl y | Fl -side-by-side
.Ar file1 file2
.Nm diff
.Op Fl -help
.Op Fl -version
.Sh ОПИСАНИЕ
Утилита
.Nm
 сравнивает содержимое
.Ar file1
и
.Ar file2
и выводит на стандартный вывод список изменений, необходимых для
преобразования одного файла в другой.
Никакой вывод не производится, если файлы идентичны.
.Pp
параметры вывода (взаимоисключающие):
.Bl -tag -width Ds
.It Fl C Ar number Fl -context Ar number
Аналогично
.Fl c
но создает diff с
.Ar number
строк контекста.
.It Fl c
Создает diff с 3 stringми контекста.
С
.Fl c
формат вывода немного изменяется:
вывод начинается с идентификации задействованных файлов и
их дат создания, а затем каждое изменение разделяется
строкой с пятнадцатью
.Li * Ns 's .
Строки, удаленные из
.Ar file1
помечены
.Sq \&-\ \& ;
те, что добавлены в
.Ar file2
помечены
.Sq +\ \& .
Строки, которые изменены из одного файла в другой, помечены в
обоих файлах
.Sq !\ \& .
Изменения, которые находятся в пределах 3 строк друг от друга, группируются вместе на
выводе.
.It Fl D Ar string Fl -ifdef Ar string
Создает объединенную версию
.Ar file1
и
.Ar file2
на стандартном выводе с включенными управляющими конструкциями препроцессора C, так что
компиляция результата без определения
.Ar string
эквивалентна компиляции
.Ar file1 ,
в то время как определение
.Ar string
приведет к получению
.Ar file2 .
.It Fl e -ed
Производит вывод в формате, подходящем для входных данных редактора,
.Xr ed 1 ,
который затем может быть использован для преобразования file1 в file2.
.Pp
При сравнении каталогов с
.Fl e ,
добавляются дополнительные команды в вывод, так что результат является
.Xr sh 1
скриптом для преобразования текстовых файлов, общих для двух каталогов,
из их состояния в
.Ar dir1
в их состояние в
.Ar dir2 .
.It Fl f -forward-ed
Идентичный вывод тому, что у
.Fl e
флага, но в обратном порядке.
Не может быть переварен
.Xr ed 1 .
.It Fl -help
Эта опция выводит сводку на stdout и завершает работу со статусом 0.
.It Fl n
Производит скрипт, аналогичный тому, что у
.Fl e ,
но в обратном порядке и с подсчетом измененных строк на каждой
вставке или удалении команды.
Это форма, используемая rcsdiff.
.It Fl q -brief
Просто выводит строку, когда файлы различаются.
Не выводит список изменений.
.It Fl U Ar number Fl -unified Ar number
Аналогично
.Fl u
но создает diff с
.Ar number
строк контекста.
.It Fl u
Создает
.Em единый
diff с 3 stringми контекста.
Единый diff аналогичен контекстному diff, производимому опцией
.Fl c .
Однако, в отличие от
.Fl c ,
все строки для изменения (добавленные и/или удаленные) присутствуют в
одном разделе.
.It Fl -version
Эта опция выводит строку версии на stdout и завершает работу со статусом 0.
.It Fl y Fl -side-by-side
Вывод в две колонки с маркером между ними.
Маркер может быть одним
из следующих:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It space
Соответствующие строки идентичны.
.It '|'
Соответствующие строки различаются.
.It '<'
Файлы различаются и только первый файл содержит строку.
.It '>'
Файлы различаются и только второй файл содержит строку.
.El
.El
.Pp
параметры сравнения:
.Bl -tag -width Ds
.It Fl a -text
Обрабатывает все файлы как текст ASCII.
Обычно
.Nm
просто выводит
.Dq Бинарные файлы ... отличаются
если файлы содержат бинарные символы.
Использование этой параметры заставляет
.Nm
производить diff.
.It Fl B Fl -ignore-blank-lines
Игнорирует блоки, содержащие только пустые строки.
.It Fl b -ignore-space-change
Игнорирует конечные пробелы (пробелы и табы) и считает другие
строки пробелов равными.
.It Fl -color= Ns Oo Ar when Oc
Окрашивает добавления зеленым, а удаления красным, или значение в
.Ev DIFFCOLORS
переменная окружения.
Возможные значения
.Ar when
это
.Dq Cm never ,
.Dq Cm always
и
.Dq Cm auto .
.Cm auto
будет использовать цвет, если вывод идет на tty и переменная
.Ev COLORTERM
окружения установлена в непустую строку.
.It Fl d -minimal
Очень старается произвести diff как можно меньше.
Это может потребовать много вычислительной мощности и памяти при обработке
больших файлов с множеством изменений.
.It Fl F Ar pattern, Fl -show-function-line Ar pattern
Как
.Fl p,
но отображает последнюю строку, соответствующую предоставленному patternу.
.It Fl I Ar pattern Fl -ignore-matching-lines Ar pattern
Игнорирует изменения, вставки и удаления, строки которых соответствуют
расширенному регулярному выражению
.Ar pattern .
Может быть указано несколько
.Fl I
patternов.
Все строки в изменении должны соответствовать какому-либо patternу, чтобы изменение было
игнорировано.
См.
.Xr re_format 7
для получения дополнительной информации о patternах регулярных выражений.
.It Fl i -ignore-case
Игнорирует регистр букв.
Например,
.Dq A
будет считаться равным
.Dq a .
.It Fl l -paginate
Пропускает вывод через
.Xr pr 1
для разбиения его на страницы.
.It Fl L Ar label Fl -label Ar label
Печатает
.Ar label
вместо первого (и второго, если эта опция указана дважды)
имени файла и времени в заголовке контекстного или единого diff.
.It Fl p -show-c-function
С контекстными и едиными diff, показывает с каждым изменением
первые 40 символов последней строки перед началом контекста
начиная с буквы, подчеркивания или доллара.
Для исходного кода на C и Objective-C, следующего стандартным соглашениям о форматировании, это
покажет прототип функции, к которой применяется изменение.
.It Fl T -initial-tab
Печатает табуляцию вместо пробела перед остальной частью строки для
нормальных, контекстных или единых форматов вывода.
Это делает выравнивание табуляций в строке последовательным.
.It Fl t -expand-tabs
Будет расширять табуляции в stringх вывода.
Нормальный или
.Fl c
вывод добавляет символ(ы) в начало каждой строки, что может испортить
отступы исходных строк и затруднить интерпретацию вывода.
Эта опция сохранит исходные отступы.
.It Fl w -ignore-all-blanks
Похоже на
.Fl b -ignore-space-change
но заставляет полностью игнорировать пробелы (пробелы и табуляции).
Например,
.Dq if (\ \&a == b \&)
будет считаться равным
.Dq if(a==b) .
.It Fl W Ar number Fl -width Ar number
Выводит не более
.Ar number
колонок при использовании формата бок о бок.
Значение по умолчанию - 130.
.It Fl -changed-group-format Ar GFMT
Форматирует входные группы в предоставленном
.Pp
формате - string со специальными ключевыми словами:
.Bl -tag -width %<
.It %<
строки из file1
.It %<
строки из file2
.El
.It Fl -ignore-file-name-case
игнорирует регистр при сравнении имен файлов
.It Fl -no-ignore-file-name-case
не игнорирует регистр при сравнении имен файлов (по умолчанию)
.It Fl -normal
стандартный вывод diff
.It Fl -speed-large-files
заглушка для совместимости с GNU diff
.It Fl -strip-trailing-cr
удаляет символ возврата каретки во входных файлах
.It Fl -suppress-common-lines
Не выводит общие строки при использовании формата бок о бок
.It Fl -tabsize Ar number
Количество пробелов, представляющих табуляцию (по умолчанию 8)
.El
.Pp
параметры сравнения каталогов:
.Bl -tag -width Ds
.It Fl N -new-file
Если файл найден только в одном каталоге, действует так, как если бы он был найден и в
другом каталоге, но имел нулевой размер.
.It Fl P -unidirectional-new-file
Если файл найден только в
.Ar dir2 ,
действует так, как если бы он был найден и в
.Ar dir1
но имел нулевой размер.
.It Fl r -recursive
Применяет
.Nm
рекурсивно к общим подкаталогам, встреченным.
.It Fl S Ar name Fl -starting-file Ar name
Заново запускает сравнение каталогов
.Nm
с середины, начиная с файла
.Ar name .
.It Fl s -report-identical-files
Заставляет
.Nm
сообщать о файлах, которые одинаковы, которые иначе не упоминались бы.
.It Fl X file Fl -exclude-from file
Исключает файлы и подкаталоги из сравнения, имена которых соответствуют
stringм в
.file .
Можно указать несколько
.Fl X
опций.
.It Fl x Ar pattern Fl -exclude Ar pattern
Исключает файлы и подкаталоги из сравнения, имена которых соответствуют
.Ar pattern .
patternы сопоставляются с использованием patternов оболочки через
.Xr fnmatch 3 .
Можно указать несколько
.Fl x
опций.
.El
.Pp
Если оба аргумента являются каталогами,
.Nm
сортирует содержимое каталогов по имени, а затем запускает
обычный файл
.Nm
алгоритм, производящий список изменений,
на текстовых файлах, которые отличаются.
Бинарные файлы, которые отличаются,
общие подкаталоги и файлы, которые появляются только в одном каталоге
описываются как таковые.
В режиме каталога сравниваются только обычные файлы и каталоги.
Если встречается необычный файл, такой как специальный файл устройства или FIFO,
выводится диагностическое сообщение.
.Pp
Если только один из файлов
.Ar file1
и
.Ar file2
является каталогом,
.Nm
применяется к не каталоговому файлу и файлу, содержащемуся в
каталоговом файле с именем файла, которое совпадает с
последним компонентом не каталогового файла.
.Pp
Если один из файлов
.Ar file1
или
.Ar file2
является 
.Sq - ,
то вместо него используется стандартный ввод.
.Ss Стиль вывода
Стандартный (без
.Fl e ,
.Fl c ,
или
.Fl n -rcs
.\" -C
опций)
вывод содержит строки следующих форм, где
.Va XX , YY , ZZ , QQ
являются номерами строк соответственно порядку файлов.
.Pp
.Bl -tag -width "XX,YYcZZ,QQ" -compact
.It Li XX Ns Ic a Ns Li YY
В (конце) строке
.Va XX
из
.Ar file1 ,
добавьте содержимое
строки
.Va YY
из
.Ar file2
чтобы они стали равны.
.It Li XX Ns Ic a Ns Li YY,ZZ
То же, что и выше, но добавьте диапазон строк,
.Va YY
через
.Va ZZ
из file2 к строке
.Va XX
из file1.
.It Li XX Ns Ic d Ns Li YY
На строке
.Va XX
удалите
строку.
Значение
.Va YY
говорит, до какой строки изменение приведет
.Ar file1
в соответствие с
.Ar file2 .
.It Li XX,YY Ns Ic d Ns Li ZZ
Удалите диапазон строк
.Va XX
через
.Va YY
в
.Ar file1 .
.It Li XX Ns Ic c Ns Li YY
Измените строку
.Va XX
в
.Ar file1
на строку
.Va YY
в
.Ar file2 .
.It Li XX,YY Ns Ic c Ns Li ZZ
Замените указанный диапазон строк строкой
.Va ZZ .
.It Li XX,YY Ns Ic c Ns Li ZZ,QQ
Замените диапазон
.Va XX , Ns Va YY
из
.Ar file1
на диапазон
.Va ZZ , Ns Va QQ
из
.Ar file2 .
.El
.Pp
Эти строки напоминают
.Xr ed 1
подкоманды для преобразования
.Ar file1
в
.Ar file2 .
Номера строк перед буквами действий относятся к
.Ar file1 ;
те, что после, относятся к
.Ar file2 .
Таким образом, обменяв
.Ic a
на
.Ic d
и прочитав строку в обратном порядке, можно также
определить, как преобразовать
.Ar file2
в
.Ar file1 .
Как в
.Xr ed 1 ,
идентичные
пары (где num1 = num2) сокращены до одного
числа.
.Sh ОКРУЖЕНИЕ
.Bl -tag -width DIFFCOLORS
.It Ev DIFFCOLORS
Значение этой переменной формируется
.Ar добавить Ns : Ns Ar удалить ,
где
.Ar добавить
это ASCII последовательность управления для добавлений и
.Ar удалить
для удалений.
Если это не установлено,
.Nm
использует зеленый для добавлений и красный для удалений.
.El
.Sh ФАЙЛЫ
.Bl -tag -width /tmp/diff.XXXXXXXX -compact
.It Pa /tmp/diff.XXXXXXXX
Временный файл, используемый при сравнении устройства или стандартного ввода.
Обратите внимание, что временный файл удаляется, как только он создается,
поэтому он не будет отображаться в списке каталогов.
.El
.Sh КОД ЗАВЕРШЕНИЯ
Утилита
.Nm
 завершается одним из следующих значений:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It 0
Различий не найдено.
.It 1
Найдены различия.
.It >1
Произошла ошибка.
.El
.Pp
параметры
.Fl -help
и
.Fl -version
завершаются со статусом 0.
.Sh ПРИМЕРЫ
Сравните
.Pa old_dir
и
.Pa new_dir
рекурсивно, генерируя единый diff и обрабатывая файлы, найденные только в одном
из этих каталогов, как новые файлы:
.Bd -literal -offset indent
$ diff -ruN /path/to/old_dir /path/to/new_dir
.Ed
.Pp
То же самое, но исключая файлы, соответствующие выражениям
.Dq *.h
и
.Dq *.c :
.Bd -literal -offset indent
$ diff -ruN -x '*.h' -x '*.c' /path/to/old_dir /path/to/new_dir
.Ed
.Pp
Показывает одну строку, указывающую, если файлы различаются:
.Bd -literal -offset indent
$ diff -q /boot/loader.conf /boot/defaults/loader.conf
Файлы /boot/loader.conf и /boot/defaults/loader.conf различаются
.Ed
.Pp
Предполагая, что файл назван
.Pa example.txt
со следующим содержимым:
.Bd -literal -offset indent
FreeBSD — это операционная система
Linux — это ядро
OpenBSD — это операционная система
.Ed
.Pp
Сравните stdin с
.Pa example.txt
исключая из сравнения те строки, которые содержат либо
.Qq Linux
или
.Qq Open :
.Bd -literal -offset indent
$ echo "FreeBSD — это операционная система" | diff -q -I 'Linux|Open' example.txt -
.Ed
.Sh СМ. ТАКЖЕ
.Xr cmp 1 ,
.Xr comm 1 ,
.Xr diff3 1 ,
.Xr ed 1 ,
.Xr patch 1 ,
.Xr pr 1 ,
.Xr sdiff 1
.Rs
.%A James W. Hunt
.%A M. Douglas McIlroy
.%T "Алгоритм для сравнения файлов по различиям"
.%J Технический отчет Вычислительной Науки
.%Q Bell Laboratories 41
.%D июнь 1976
.Re
.Sh СТАНДАРТЫ
Утилита
.Nm
 соответствует
.St -p1003.1-2008
спецификации.
.Pp
Флаги
.Op Fl aDdIiLlNnPpqSsTtwXxy
являются расширениями этой спецификации.
.Sh ИСТОРИЯ
A
.Nm
команда появилась в
.At v6 .

