.\" НЕ ИЗМЕНЯЙТЕ ЭТОТ ФАЙЛ! Он был сгенерирован при помощи help2man 1.33.
.TH DIFF3 "1" "апрель 2004" "diffutils 2.8.7" "Пользовательские команды"
.SH НАЗВАНИЕ
diff3 \- сравнить три файла построчно
.SH СИНТАКСИС
.B diff3
[\fIOPTION\fR]... \fIMYFILE OLDFILE YOURFILE\fR
.SH ОПИСАНИЕ
Сравнивает три файла построчно.
.TP
\fB\-e\fR  \fB\-\-ed\fR
Выводит необъединенные изменения из OLDFILE в YOURFILE в MYFILE.
.TP
\fB\-E\fR  \fB\-\-show\-overlap\fR
Выводит необъединенные изменения, заключив конфликты в квадратные скобки.
.TP
\fB\-A\fR  \fB\-\-show\-all\fR
Выводит все изменения, заключив конфликты в квадратные скобки.
.TP
\fB\-x\fR  \fB\-\-overlap\-only\fR
Выводит перекрывающиеся изменения.
.TP
\fB\-X\fR
Выводит перекрывающиеся изменения, заключив конфликты в квадратные скобки.
.TP
\fB\-3\fR  \fB\-\-easy\-only\fR
Выводит необъединенные неперекрывающиеся изменения.
.TP
\fB\-m\fR  \fB\-\-merge\fR
Выводит объединенный файл вместо скрипта ed (по умолчанию \fB\-A\fR).
.TP
\fB\-L\fR LABEL  \fB\-\-label\fR=\fILABEL\fR
Использует LABEL вместо имени файла.
.TP
\fB\-i\fR
Добавляет команды `w' и `q' в скрипты ed.
.TP
\fB\-a\fR  \fB\-\-text\fR
Обрабатывает все файлы как текст.
.TP
\fB\-\-strip\-trailing\-cr\fR
Удаляет конечный символ возврата каретки при вводе.
.TP
\fB\-T\fR  \fB\-\-initial\-tab\fR
Выравнивает табуляцию, добавляя в начало табуляцию.
.TP
\fB\-\-diff\-program\fR=\fIPROGRAM\fR
Использует PROGRAM для сравнения файлов.
.TP
\fB\-v\fR  \fB\-\-version\fR
Выводит информацию о версии.
.TP
\fB\-\-help\fR
Выводит эту справку.
.PP
Если FILE это `-', читает стандартный ввод.
Статус выхода равен 0 в случае успеха, 1 при конфликтах, 2 при проблемах.
.SH АВТОР
Написано Рэнди Смитом.
.SH "СООБЩЕНИЯ ОБ ОШИБКАХ"
Сообщайте об ошибках на <bug-gnu-utils@gnu.org>.
.SH АВТОРСКИЕ ПРАВА
Авторское право \(c) 2004 Фонд свободного программного обеспечения, Inc.
.br
Это свободное программное обеспечение; смотрите исходный код для условий копирования. НЕТ
гарантии; даже для ТОРГОВЛИ или ПРИГОДНОСТИ ДЛЯ КОНКРЕТНЫХ ЦЕЛЕЙ.
.SH "СМ. ТАКЖЕ"
Полная документация по
.B diff3
содержится в руководстве Texinfo. Если
.B info
и
.B diff3
правильно установлены на вашем сайте, команда
.IP
.B info diff3
.PP
должна предоставить вам доступ к полному руководству.
