.\" Авторское право  (c) 2013-2016 Девин Теске
.\" Все права защищены.
.\"
Разрешение на распространение и использование в исходной и бинарной формах,
.\" с изменениями или без них, разрешается при условии соблюдения следующих условий:
.\" 1. Распространение исходного кода должно сохранять приведенное выше уведомление о копирайте,
.\"    этот список условий и следующий отказ от ответственности.
.\" 2. Распространение в бинарной форме должно воспроизводить приведенное выше уведомление о копирайте,
.\"    этот список условий и следующий отказ от ответственности в
.\"    документации и/или других материалах, предоставляемых вместе с распространением.
.\"
.\" ДАННОЕ ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЕНО РЕГЕНТАМИ И УЧАСТНИКАМИ «КАК ЕСТЬ», И
.\" ЛЮБЫЕ ПРЯМЫЕ ИЛИ КОСВЕННЫЕ ГАРАНТИИ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ,
.\" ГАРАНТИЯМИ ТОВАРНОЙ ПРИГОДНОСТИ И СООТВЕТСТВИЯ КОНКРЕТНОЙ ЦЕЛИ,
.\" ОТКАЗЫВАЮТСЯ. В НИКАКОМ СЛУЧАЕ РЕГЕНТЫ ИЛИ УЧАСТНИКИ НЕ НЕСУТ ОТВЕТСТВЕННОСТИ
.\" ЗА ЛЮБЫЕ ПРЯМЫЕ, КОСВЕННЫЕ, СЛУЧАЙНЫЕ, СПЕЦИАЛЬНЫЕ, ПОКАЗАТЕЛЬНЫЕ ИЛИ ПОСЛЕДУЮЩИЕ
.\" УЩЕРБЫ (ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ, ПРИОБРЕТЕНИЕМ ЗАМЕЩАЮЩИХ ТОВАРОВ
.\" ИЛИ УСЛУГ; УТРАТОЙ ПРАВА ПОЛЬЗОВАНИЯ, ДАННЫХ ИЛИ ПРИБЫЛИ; ЛИБО ПРЕРЫВАНИЕМ ДЕЯТЕЛЬНОСТИ)
.\" НЕЗАВИСИМО ОТ ТОГО, НА КАКОЙ ТЕОРИИ ОТВЕТСТВЕННОСТИ, ДОГОВОРНОЙ, СТРОГОЙ
.\" ОТВЕТСТВЕННОСТИ ИЛИ ДЕЛИКТНОЙ (ВКЛЮЧАЯ НЕБРЕЖНОСТЬ ИЛИ ИНОЕ)
.\" ОСНОВЫВАЕТСЯ ЛИСПОЛЬЗОВАНИЕ ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ, ДАЖЕ ЕСЛИ БЫЛО СООБЩЕНО О
.\" ВОЗМОЖНОСТИ ТАКОГО УЩЕРБА.
.\"
.Dd 2 ноября 2021 года
.Dt DPV 1
.Os
.Sh НАЗВАНИЕ
.Nm dpv
.Nd потоковая передача данных из stdin или нескольких путей с просмотром хода выполнения в диалоге
.Sh СИНТАКСИС
.Nm
.Op options
.Sm off
.Op Ar bytes Cm \&:
.Ar label
.Sm on
.Nm
.Op options
.Fl m
.Sm off
.Op Ar bytes1 Cm \& :
.Ar label1
.Sm on
.Ar path1
.Oo
.Sm off
.Op Ar bytes2 Cm \&:
.Ar label2
.Sm on
.Ar path2
.Ar ...
.Oc
.Sh ОПИСАНИЕ
.Nm
предоставляет вид диалога хода выполнения, позволяющий пользователю видеть текущую скорость передачи
и общий объем переданных данных для одного или нескольких потоков.
.Pp
Утилита
.Nm
имеет два основных режима обработки входных данных.
.Pp
Стандартный режим ввода, без
.Ql Fl m ,
.Nm
считывает байты из стандартного ввода.
Должна быть предоставлена метка для данных.
.Pp
Второстепенный режим ввода, с
.Ql Fl m ,
.Nm
считывает несколько путей
.Pq до 2047 или Dq ARG_MAX/2-1 ,
последовательно.
.Pp
Данные, считанные в любом из режимов, либо удаляются
.Pq по умолчанию,
либо отправляются в запущенный экземпляр программы, указанный через
.Ql Fl x Ar cmd ,
или отправляются в уникальный файл, указанный через
.Ql Fl o Ar file .
.Pp
С
.Ql Fl m
или без,
прогресс отображается с использованием одного из
.Xr dialog 3
.Pq по умолчанию,
.Xr dialog 1
.Pq см. Ql Fl D ,
или вместо этого
.Xr Xdialog 1 Pq Pa ports/x11/xdialog
.Pq см. Ql Fl X .
.Pp
Доступны следующие параметры:
.Bl -tag -width "-b backtitle"
.It Fl a Ar text
Отображать
.Ar text
ниже индикатора прогресса файла(ов).
.It Fl b Ar backtitle
Отображать
.Ar backtitle
на фоне, в верхнем левом углу, за виджетом диалога.
При использовании
.Xr Xdialog 1 Pq Pa ports/x11/xdialog ,
это отображается внутри окна
.Pq в верхней части,
за которым следует разделительная линия.
.It Fl D
Не использовать стандартный интерфейс
.Xr dialog 3 ,
а вместо этого запустить экземпляр
.Xr dialog 1 .
Путь к
.Xr dialog 1
берется из переменной окружения
.Ev DIALOG
или просто
.Dq Li dialog
если не установлена или NULL.
.It Fl d
Режим отладки.
Выводить данные диалогового приглашения в стандартный вывод и предоставлять дополнительную отладку в стандартный поток ошибок.
.It Fl h
Вывести короткую инструкцию по синтаксису с краткими описаниями опций и выйти.
Вывод производится в стандартный поток ошибок.
.It Fl I Ar format
Настроить строку формата для нескольких файлов, используемую для обновления строки состояния.
Игнорируется при использовании
.Ql Fl D
или
.Ql Fl X ,
которые не имеют возможности отображать строку состояния
.Pq содержащую информацию о байтах/скорости/потоках.
Значение по умолчанию
.Dq Li %'10lli bytes read @ %'9.1f bytes/sec. [%i/%i busy/wait] .
Этот формат используется при обработке более чем одного файла.
.It Fl i Ar format
Настроить строку формата для одного файла, используемую для обновления строки состояния.
Игнорируется при использовании
.Ql Fl D
или
.Ql Fl X ,
которые не имеют возможности отображать строку состояния
.Pq содержащую информацию о байтах/скорости/потоках.
Значение по умолчанию
.Dq Li %'10lli bytes read @ %'9.1f bytes/sec.
Этот формат используется при обработке одного файла.
.It Fl k
Сохранить заголовок.
Предотвращает визуально отвлекающие процедуры инициализации/завершения для скриптов, запускающих
.Xr dialog 1
несколько раз.
.It Fl L Ar size
Размер метки.
Если отрицательный, уменьшить до ширины самой длинной метки.
.It Fl l
Режим строки.
Читать строки из входных данных вместо байтов.
.It Fl m
Многовходовый режим.
Вместо чтения байтов из стандартного ввода, читать из набора путей
.Pq один для каждой метки.
По умолчанию каждый путь обрабатывается последовательно в указанном порядке.
.It Fl N
Без переполнения.
Если включено, останавливать чтение входных данных с известной длиной, когда ввод достигает указанной длины.
.It Fl n Ar num
Отображать не более
.Ar num
индикаторов прогресса на экране.
Если ноль, отображать столько, сколько возможно.
Если отрицательное, отображать только главный индикатор прогресса.
Значение по умолчанию 0.
Максимальное значение 10.
.It Fl o Ar file
Вывести данные в
.Ar file .
Первое вхождение
.Ql %s
.Pq если таковое имеется
в
.Ql Ar file
будет заменено на текст
.Ar label .
.It Fl P Ar size
Размер мини-индикатора прогресса.
Если отрицательный, не отображать мини-индикаторы прогресса
.Pq отображается только большой общий индикатор прогресса.
Если ноль, автоматически регулируется в зависимости от количества файлов для чтения.
Когда ноль и только один файл для чтения, по умолчанию равно -1.
Когда ноль и более одного файла для чтения, по умолчанию равно 17.
.It Fl p Ar text
Отображать
.Ar text
над индикатором(ами) прогресса файла(ов).
.It Fl T
Тестовый режим.
Симулирует чтение определенного количества байтов, равномерно распределенных между количеством файлов,
во время прохождения каждого процентного значения каждого файла для обработки.
Добавляет
.Dq Li [TEST  MODE]
в строку состояния
.Pq для изменения используйте Ql Fl u Ar format.
Данные на самом деле не читаются.
.It Fl t Ar title
Отображать
.Ar title
наверху диалогового окна.
Обратите внимание, что если вы используете эту опцию одновременно с
.Ql Fl X
и
.Ql Fl b Ar backtitle ,
то
.Ar backtitle
и
.Ar title
фактически меняются местами
.Pq см. раздел BUGS ниже.
.It Fl U Ar num
Обновлять строку состояния
.Ar num
раз в секунду.
Значение по умолчанию
.Ql Li 2 .
Значение
.Ql Li 0
отключает обновления строки состояния.
Если отрицательное, обновлять строку состояния максимально быстро.
Игнорируется при использовании
.Ql Fl D
или
.Ql Fl X ,
которые не имеют возможности отображать строку состояния
.Pq содержащую информацию о байтах/скорости/потоках.
.It Fl w
Широкий режим.
Позволяет длинным аргументам
.Ar text ,
используемым с
.Ql Fl p
и
.Ql Fl a ,
увеличивать ширину диалога.
Приглашения, шире максимальной ширины, будут переноситься на новую строку
если не используется
.Xr Xdialog 1 Pq Pa ports/x11/xdialog ;
см. раздел BUGS ниже.
.It Fl X
Включить режим X11, используя
.Xr Xdialog 1 Pq Pa ports/x11/xdialog
вместо
.Xr dialog 1
или
.Xr dialog 3 .
.It Fl x Ar cmd
Выполнить
.Ar cmd
.Pq через Xr sh 1
и отправить ему данные, которые были прочитаны.
Данные доступны
.Ar cmd
на стандартном вводе.
С
.Ql Fl m ,
.Ar cmd
выполняется один раз для каждого
.Ar path
аргумента.
Первое вхождение
.Ql %s
.Pq если таковое имеется
в
.Ql Ar cmd
будет заменено на текст
.Ar label .
.El
.Sh ОКРУЖЕНИЕ
Следующие переменные окружения упоминаются в
.Nm :
.Bl -tag -width ".Ev USE_COLOR"
.It Ev DIALOG
Переопределить строку команды, используемой для запуска
.Xr dialog 1
.Pq требуется Ql Fl D
или
.Xr Xdialog 1 Pq Pa ports/x11/xdialog
.Pq требуется Ql Fl X ;
по умолчанию это либо
.Ql dialog
.Pq для Ql Fl D
или
.Ql Xdialog
.Pq для Ql Fl X .
.It Ev DIALOGRC
Если установлено и не NULL, путь к файлу
.Ql .dialogrc .
.It Ev HOME
Если
.Ql Ev $DIALOGRC
не установлено или NULL, используется как префикс к
.Ql .dialogrc
.Pq т.е., Ql $HOME/.dialogrc .
.It Ev USE_COLOR
Если установлено и NULL, отключает использование цвета при использовании
.Xr dialog 1 .
Не применяется к
.Xr Xdialog 1 Pq Pa ports/x11/xdialog .
.El
.Sh ЗАВИСИМОСТИ
Если используется
.Ql Fl D ,
.Xr dialog 1
необходим.
.Pp
Если используется
.Ql Fl X ,
.Xr Xdialog 1 Pq Pa ports/x11/xdialog
необходим.
.Sh ФАЙЛЫ
.Bl -tag -width "$HOME/.dialogrc" -compact
.It Pa $HOME/.dialogrc
.El
.Sh ПРИМЕРЫ
Простой пример, демонстрирующий, насколько быстро
.Xr yes 1
генерирует строки
.Pq обычно около десяти миллионов в секунду; результаты могут отличаться:
.Bd -literal -offset indent
yes | dpv -l yes
.Ed
.Pp
Отображение прогресса, пока измеряется, сколько времени занимает
.Xr yes 1
для генерации полумиллиарда строк
.Pq обычно менее одной минуты; результаты могут отличаться:
.Bd -literal -offset indent
time yes | dpv -Nl 500000000:yes
.Ed
.Pp
Пример, показывающий, как быстро передается файл с использованием
.Xr nc 1 :
.Bd -literal -offset indent
dpv -x "nc -w 1 somewhere.com 3000" -m label file
.Ed
.Pp
Похожий пример, передача файла из другого процесса и передача ожидаемого размера в
.Nm :
.Bd -literal -offset indent
cat file | dpv -x "nc -w 1 somewhere.com 3000" 12345:label
.Ed
.Pp
Более сложный пример:
.Bd -literal -offset indent
tar cf - . | dpv -x "gzip -9 > out.tgz" \\
    $( du -s . | awk '{print $1 * 1024}' ):label
.Ed
.Pp
Создание образа диска:
.Bd -literal -offset indent
dpv -o disk-image.img -m label /dev/ada0
.Ed
.Pp
Запись образа обратно на диск:
.Bd -literal -offset indent
dpv -o /dev/ada0 -m label disk-image.img
.Ed
.Pp
Обнуление диска:
.Bd -literal -offset indent
dpv -o /dev/md42 "Zeroing md42" < /dev/zero
.Ed
.Sh сМ. ТАКЖЕ
.Xr dialog 1 ,
.Xr sh 1 ,
.Xr Xdialog 1 Pq Pa ports/x11/xdialog ,
.Xr dialog 3
.Sh ИСТОРИЯ
Утилита
.Nm
впервые появилась в
.Fx 10.2 .
.Sh АВТОРЫ
.An Девин Теске Aq dteske@FreeBSD.org
.Sh ОШИБКИ
.Xr Xdialog 1 Pq Pa ports/x11/xdialog ,
когда указаны оба
.Ql Fl -title Ar title
.Pq см. выше Ql Fl t Ar title
и
.Ql Fl -backtitle Ar backtitle
.Pq см. выше Ql Fl b Ar backtitle ,
отображает backtitle вместо title и наоборот.
.Pp
.Xr Xdialog 1 Pq Pa ports/x11/xdialog
не переносит длинные тексты приглашений, полученные после первоначального запуска.
Это известная проблема с виджетом
.Ql --gauge
в
.Xr Xdialog 1 Pq Pa ports/x11/xdialog .
.Pp
.Xr dialog 1
не отображает первый символ после серии экранированных последовательностей escape
(например, ``\\n'' воспроизводит ``\\'' вместо ``\\n'').
Это известная проблема с
.Xr dialog 1
и не влияет на
.Xr dialog 3
или
.Xr Xdialog 1 Pq Pa ports/x11/xdialog .
.Pp
Если ваше приложение игнорирует
.Ev USE_COLOR
когда установлено и NULL перед вызовом
.Xr dpv 1
с цветными escape-последовательностями,
.Xr dialog 3
и
.Xr dialog 1
могут отображаться некорректно.
Решение — обнаружить, когда
.Ev USE_COLOR
установлено и NULL и либо не использовать цветные escape-последовательности в это время, либо использовать
.Xr unset 1
.Xr [ sh 1 ]
или
.Xr unsetenv 1
.Xr [ csh 1 ]
чтобы сбросить
.Ev USE_COLOR ,
что позволяет интерпретировать цветные последовательности.
Это не влияет на
.Xr Xdialog 1 Pq Pa ports/x11/xdialog ,
который отображает цветные escape-последовательности как обычный текст.
См.
.Do
встроенные последовательности "\\Z"
.Dc
в
.Xr dialog 1
для дополнительной информации.
