.\" @(#)drill.1 1.7.0 14-Jul-2004 OF; 
.TH drill 1 "28 мая 2006"
.SH НАЗВАНИЕ
drill \- получить (отладить) информацию из DNS(SEC)
.SH СИНТАКСИС
.B drill
[
.IR OPTIONS
]
.IR name
[
.IR @server
]
[
.IR type
]
[
.IR class
]

.SH ОПИСАНИЕ
\fBdrill\fR — это инструмент, предназначенный для извлечения различных видов информации из DNS. Он специально разработан для работы с DNSSEC.
.PP
Название \fBdrill\fR является каламбуром слова \fBdig\fR. С помощью \fBdrill\fR вы сможете получить еще больше информации, чем с \fBdig\fR.
.PP
Если аргументы не указаны, класс по умолчанию - 'IN', а тип - 'A'. Сервер(ы),
указанные в /etc/resolv.conf, используются для запросов.

.PP
\fIname\fR
Запрашиваемое имя.

.PP
\fI@server\fR
Отправляет запрос на этот сервер. Если не указан, использует серверы из
\fI/etc/resolv.conf\fR.

.PP
\fItype\fR
Запрашиваемый тип RR. Если тип не указан в командной строке, по умолчанию
используется 'A', за исключением случаев обратного поиска, когда тип по умолчанию - 'PTR'.

.PP
\fIclass\fR
Использовать этот класс при запросе.

.SH ПРИМЕРЫ ИСПОЛЬЗОВАНИЯ
\fBdrill mx miek.nl\fR
Показать записи MX домена miek.nl.

.TP
\fBdrill \-S jelte.nlnetlabs.nl\fR
Проследить все подписи в домене jelte.nlnetlab.nl. Эта опция доступна
только в случае компиляции ldns с openssl-support.

.TP
\fBdrill \-TD www.example.com\fR
Выполнить DNSSEC (\-D) трассировку (\-T) от корневых серверов до www.example.com.
Эта опция работает только при компиляции ldns с поддержкой openssl.

.TP
\fBdrill \-s dnskey jelte.nlnetlabs.nl\fR
Показать запись(и) DNSKEY для jelte.nlnetlabs.nl. Для каждой найденной записи DNSKEY
также распечатать запись DS.

.Sh ПАРАМЕТРЫ

.TP
\fB\-D
Включить DNSSEC в запросе. При запросе типов DNSSEC (DNSKEY, RRSIG,
DS и NSEC) это \fBне\fR включено автоматически.

.TP
\fB\-T
Выполнить трассировку \fIname\fR от корня. При использовании этой параметры аргумент @server
не используется.

.TP
\fB\-S
Проследить подпись(и) 'имени' до известного ключа или как можно выше в
дереве.

.TP
\fB\-I  \fIIPv4 или IPv6 адрес\fR
Исходный адрес для запроса. Исходный адрес должен присутствовать
на интерфейсе хоста, запускающего drill.

.TP
\fB\-V \fIlevel\fR
Быть более подробным. Установите уровень на 5, чтобы увидеть фактический отправленный запрос.

.TP
\fB\-Q
Тихий режим, отменяет \-V.

.TP
\fB\-f \fIfile\fR
Прочитать запрос из файла. Запрос должен быть сохранен с помощью \-w.

.TP
\fB\-i \fIfile\fR
Прочитать ответ из файла вместо сети. Это помогает в отладке и может использоваться для проверки правильности запроса на диске.
Если файл содержит двоичные данные, предполагается, что это запрос в
сетевом порядке.

.TP
\fB\-w \fIfile\fR
Записать пакет ответа в файл.

.TP
\fB\-q \fIfile\fR
Записать пакет запроса в файл.

.TP
\fB\-v
Показать версию drill.

.TP
\fB\-h
Показать короткое сообщение с помощью.

.SS ПАРАМЕТРЫ ЗАПРОСА

.TP
\fB\-4
Оставаться на ip4. Отправлять запросы только на серверы, поддерживающие ip4.

.TP
\fB\-6
Оставаться на ip6. Отправлять запросы только на серверы, поддерживающие ip6.

.TP
\fB\-a
Использовать механизм резервного копирования структуры резолвера, если ответ
усечен (TC=1). Если получен усеченный пакет и этот
параметр установлен, drill сначала отправит новый запрос с размером буфера EDNS0
4096.

Если размер буфера EDNS0 уже установлен на 512+ байт или
повторная попытка также приводит к усеченному ответу,
структура резолвера перейдет на TCP.

.TP
\fB\-b \fIразмер\fR
Использовать размер в качестве размера буфера в псевдо RR EDNS0.

.TP
\fB\-c \fIfile\fR
Использовать файл вместо /etc/resolv.conf для конфигурации серверов имен.

.TP
\fB\-d \fIdomain\fR
При трассировке (\-T) начать с этого домена, а не с корня.

.TP
\fB\-t
Использовать TCP/IP при запросе сервера.

.TP
\fB\-k \fIkeyfile\fR
Использовать этот файл для чтения (доверенного) ключа. При указании этой параметры
\fBdrill\fR пытается проверить текущий ответ с помощью этого ключа. Не производится никакой проверки. Когда \fBdrill\fR выполняет безопасную трассировку, этот
ключ будет использоваться как доверенный якорь. Может содержать запись DNSKEY или DS.

Альтернативно, при включенной DNSSEC трассировке (\fB-TD\fR) или подписи
(\fB-S\fR), если \fB-k\fR не указан и по умолчанию доверенный якорь
(/etc/unbound/root.key) существует и содержит действительную запись DNSKEY или DS,
он будет использоваться как доверенный якорь.

.TP
\fB\-o \fImnemonic\fR
Использовать эту опцию для установки или сброса определенных битов заголовка. Бит устанавливается
с помощью мнемоники в ЗАГЛАВНЫХ буквах. Бит сбрасывается, если
мнемоника указана строчными буквами. Следующие мнемоники
понимаются \fBdrill\fR:

        QR, qr: установить, сбросить QueRy (по умолчанию: включено)
        AA, aa: установить, сбросить Authoritative Answer (по умолчанию: выключено)
        TC, tc: установить, сбросить TrunCated (по умолчанию: выключено)
        RD, rd: установить, сбросить Recursion Desired (по умолчанию: включено)
        CD, cd: установить, сбросить Checking Disabled (по умолчанию: выключено)
        RA, ra: установить, сбросить Recursion Available (по умолчанию: выключено)
        AD, ad: установить, сбросить Authenticated Data (по умолчанию: выключено)

Таким образом: \fB-o CD\fR включит Checking Disabled, что инструктирует
кеш не проверять ответы, которые он выдает.

.TP
\fB\-p \fIport\fR
Использовать этот порт вместо порта 53 по умолчанию.

.TP
\fB\-r \fIfile\fR
При трассировке (\-T) использовать файл как корневой файл подсказок серверов.

.TP
\fB\-s
При встрече с DNSKEY также напечатать эквивалент DS.

.TP
\fB\-u
Использовать UDP при запросе сервера. Это значение по умолчанию.

.TP
\fB\-w \fIfile\fR
Записать ответ в файл. Файл будет содержать шестнадцатеричный дамп запроса. Это может быть использовано вместе с \-f.

.TP
\fB\-x
Выполнить обратный поиск. Аргумент типа не используется, он предварительно установлен в PTR.

.TP
\fB\-y \fI<name:key[:algo]>\fR
указать именованный base64 tsig ключ, и опционально алгоритм (по умолчанию hmac-md5.sig-alg.reg.int)

.TP
\fB\-z \fR
не рандомизировать список серверов имен перед отправкой запросов.

.SH "КОД ЗАВЕРШЕНИЯ"
КОД ЗАВЕРШЕНИЯ равен 0, если найденный ответ является безопасным и доверенным
или небезопасным.
КОД ЗАВЕРШЕНИЯ не равен 0, если найденный ответ ненадежен или поддельный,
либо произошла ошибка при выполнении запроса.

.SH "ФАЙЛЫ"
.TP
/etc/unbound/root.key
Файл, из которого загружаются доверенные ключи, когда опция \fB-k\fR не указана.
.SH "СМ. ТАКЖЕ"
.LP
unbound-anchor(8)

.SH АВТОР
Йелте Янсен и Мик Гибен. Оба из NLnet Labs.

.SH СООБЩЕНИЕ ОБ ОШИБКАХ
Сообщайте об ошибках на <ldns-team@nlnetlabs.nl>.

.SH ОШИБКИ

.SH АВТОРСКИЕ ПРАВА
Авторкое право (c) 2004-2008 NLnet Labs.
Лицензирован по пересмотренной лицензии BSD. Гарантий НЕТ; даже для товарной пригодности или
ПРИГОДНОСТИ ДЛЯ ОПРЕДЕЛЕННОЙ ЦЕЛИ.

.SH СМ. ТАКЖЕ
\fBdig\fR(1), \fIRFC403{3,4,5}\fR.
