.\" Copyright (c) 1990, 1993
.\"	Ректоры Калифорнийского университета. Все права защищены.
.\"
.\" Распространение и использование в исходном коде и двоичной форме, с использованием или без использования
.\" модификаций, если следующие условия
.\" соблюдаются:
.\" 1. При распространении исходного кода должно сохраняться вышеуказанное уведомление
.\"    об авторских правах, этот список условий и следующий дисклеймер.
.\" 2. При распространиении в двоичной форме должно воспроизводиться уведомление об авторских правах,
.\"    этот список условий и следующий ниже отказ от ответственности в
.\"    документации и/или других материалах, поставляемых с дистрибутивом.
.\" 3. Ни название университета, ни имена его участников не могут быть использованы для
.\"    поддержки или продвижения продуктов, созданных на основе данного программного обеспечения,
.\"    без специального предварительного письменного согласия.
.\"
.\" ДАННОЕ ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЯЕТСЯ ПРАВООБЛАДАТЕЛЯМИ И СОАВТОРАМИ ``КАК ЕСТЬ'', И 
.\" МЫ ОТКАЗЫВАЕМСЯ ОТ ЛЮБЫХ ПОДРАЗУМЕВАЕМЫХ ОБЯЗАТЕЛЬСТВ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ, 
.\" ПОДРАЗУМЕВАЕМЫЕ ГАРАНТИИ ТОВАРНОЙ ПРИГОДНОСТИ И НЕПРИГОДНОСТИ ДЛЯ ОПРЕДЕЛЕННОЙ
.\" ЦЕЛИ. НИ В КОЕМ СЛУЧАЕ ПРАВООБЛАДАТЕЛИ ИЛИ СОВАТОРЫ НЕ НЕСУТ ОТВЕТСТВЕННОСТИ
.\" ЗА ЛЮБЫЕ ПРЯМЫЕ, КОСВЕННЫЕ, СЛУЧАЙНЫЕ, ОСОБЫЕ, ПОКАЗАТЕЛЬНЫЕ ИЛИ ЛОГИЧЕСКИ ВЫТЕКАЮЩИЕ
.\" УБЫТКИ (ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ ИМИ, ПРИОБРЕТЕНИЕ ЗАМЕНЯЮЩИХ ТОВАРОВ ИЛИ УСЛУГ;
.\" ПОТЕРЮ ВОЗМОЖНОСТИ ИСПОЛЬЗОВАНИЯ, ДАННЫХ ИЛИ ПРИБЫЛИ; ИЛИ ПРЕКРАЩЕНИЕ ДЕЯТЕЛЬНОСТИ)
.\" НЕЗАВИСИМО ОТ ПРИЧИНЕННОГО УЩЕРБА И НА ОСНОВАНИИ ЛЮБОЙ ТЕОРИИ ОТВЕТСТВЕННОСТИ, БУДЬ ТО В РАМКАХ КОНТРАКТА, 
.\" ПРЯМОЙ ОТВЕТСТВЕННОСТИ ИЛИ ДЕЛИКТА (ВКЛЮЧАЯ ХАЛАТНОСТЬ ИЛИ ИНОЕ), ВОЗНИКШЕГО КАКИМ-ЛИБО ОБРАЗОМ
.\" В РЕЗУЛЬТАТЕ ИСПОЛЬЗОВАНИЯ ДАННОГО ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ, ДАЖЕ ЕСЛИ ВЫ БЫЛИ ОСВЕДОМЛЕНЫ О ВОЗМОЖНОСТИ
.\" ТАКОГО УЩЕРБА.
.\"
.\"	    @(#)passwd.1	8.1 (Berkeley) 6/6/93
.\"
.Dd 14 февраля, 2014 год
.Dt PASSWD 1
.Os
.Sh НАЗВАНИЕ
.Nm passwd , yppasswd
.Nd modify a user's password
.Sh СИНТАКСИС
.Nm
.Op Fl l
.Op Ar пользователь
.Nm yppasswd
.Op Fl l
.Op Fl y
.Op Fl d Ar домен
.Op Fl h Ar хост
.Op Fl o
.Sh ОПИСАНИЕ
Утилита
.Nm
изменяет локальный пароль пользователя,
пароль Kerberos или пароль NIS.
Если пользователь не является суперпользователем,
.Nm
сначала запрашивает текущий пароль, и она не будет продолжена, пока
не будет введен правильный пароль.
.Pp
При введении нового пароля, введенные символы не выводятся на экран, 
чтобы посторонний не увидел пароль.
Утилита
.Nm
запрашивает новый пароль дважды, для того, чтобы выявить опечатки.
.Pp
Общая длинна пароля не должна быть бльше чем
.Dv _PASSWORD_LEN
(на данный момент 128 символов).
.Pp
Как только пароль будет подтвержен,
.Nm
передает информацию о новом пароле
на хост аутентификации Kerberos.
.Pp
Доступна следующая опция:
.Bl -tag -width indent
.It Fl l
Заставляет пароль обновляться только в локальном 
файле паролей, а не в базе данных Kerberos.
При изменении только локального пароля,
.Xr pwd_mkdb 8
Испльзуется для обновления базы данных паролей.
.El
.Pp
При смене локального пароля или пароля NIS, дата следующей смены пароля 
устанавлиается в соответствии  с возможностью
.Dq passwordtime
в классе логинов пользователя.
.Pp
Чтобы изменить пароль другого пользователя Kerberos, необходимо сначала
запустить
.Xr kinit 1
сопровождаемый
.Nm .
Суперпользователю не требуется вводить текущий пароль пользователя,
если изменен только локальный пароль.
.Sh NIS ВЗАИМОДЕЙСТВИЕ
Утилита
.Nm
утилита имеет встроенную поддержку NIS.
Если пользователь существует вбазе данных паролей NIS,
но не существует локально,
.Nm
автоматически переключается в 
.Nm yppasswd
режим.
Если указанный
пользователь не существует ни в локальной базе данных паролей,
ни в картах паролей NIS,
.Nm
возвращает сообщение об ошибке.
.Pp
При смене пароля NIS непривилегированные пользователи должны указать
свой старый пароль для аутентификации (демон
.Xr rpc.yppasswdd 8
требует ввести исходный пароль, прежде
чем он разрешит какие-либо изменения в картах паролей NIS).
Это ограничение распространяется даже на
суперпользователя, за одним важным исключением: аутентификация по паролю
для суперпользователя обходится без проверки подлинности по паролю на главном сервере NIS.
Это означает, что
суперпользователь на главном сервере NIS может беспрепятственно изменять
чей-либо пароль NIS.
Суперпользователю в клиентских системах NIS и на подчиненных
серверах NIS по-прежнему необходимо ввести пароль, прежде чем обновление будет обработано.
.Pp
Доступны следующие дополнительные опции, поддерживающие работу с NIS:
.Bl -tag -width indent
.It Fl y
переопределение
.Nm Ns 's
проверяет эвристику и переводит
ее в режим NIS.
.It Fl l
Когда NIS доступна, флаг
.Fl l
Может быть использован для принудительного
.Nm
внутри
.Dq только локально
режима.
Этот флаг можно использовать для изменения записи
для локального пользователя, если существует пользователь NIS с таким же логином.
Например, иногда вы можете найти записи для системных пользователей
.Dq placeholder
таких как
.Pa bin
или
.Pa daemon
как в картах паролей NIS, так и в локальной базе данных пользователей.
По
умолчанию,
.Nm
попытается изменить пароль NIS.
Вместо этого, флаг
.Fl l
можно использовать для изменения локального пароля.
.It Fl d Ar домен
Укажите, какой домен использовать при смене пароля NIS.
По умолчанию,
.Nm
предполагает, что следует использовать системный домен по умолчанию.
Этот флаг
в первую очередь предназначен для использования суперпользователем на главном сервере NIS: один
Сервер NIS может поддерживать несколько доменов.
Доменное имя на главном сервере NIS может быть не задано (необязательно,
чтобы сервер NIS также был клиентом) в этом случае команде
.Nm
необходимо указать, в каком домене она будет работать.
.It Fl h Ar хост
Указывает имя NIS-сервера.
Эта опция, в сочетании
с опцией 
.Fl d
может использоваться для изменения пароля NIS на нелокальном
сервере NIS.
Когда домен указан с помощью опции
.Fl d
и
.Nm
не удается определить имя главного сервера NIS (возможно, из
-за того, что не задано локальное доменное имя), предполагается, что имя мастера NIS является
.Dq localhost .
Это может быть отменено с помощью флага
.Fl h .
Указанное имя хоста необязательно должно быть именем главного сервера NIS:
имя главного сервера NIS для данной карты можно определить, запросив любой
Сервер NIS (главный или подчиненный) в домене, поэтому указание имени
подчиненного сервера будет работать одинаково хорошо.
.It Fl o
Не следует автоматически отменять проверку подлинности по паролю для
суперпользователя на главном сервере NIS; предполагается установить
.Dq old
режим вместо этого.
Этот
флаг имеет ограниченное практическое применение, но полезен для тестирования.
.El
.Sh ФИЛЬТРЫ
.Bl -tag -width /etc/master.passwd -compact
.It Pa /etc/master.passwd
база данных пользователей
.It Pa /etc/passwd
файл паролей в формате Version 7
.It Pa /etc/passwd.XXXXXX
временная копия файла паролей
.It Pa /etc/login.conf
login class capabilities database
база данных возможностей класса логинов
.El
.Sh СМОТРИТЕ ТАКЖЕ
.Xr chpass 1 ,
.Xr kinit 1 ,
.Xr login 1 ,
.Xr login.conf 5 ,
.Xr passwd 5 ,
.Xr kerberos 8 ,
.Xr kpasswdd 8 ,
.Xr pam_passwdqc 8 ,
.Xr pw 8 ,
.Xr pwd_mkdb 8 ,
.Xr vipw 8
.Rs
.%A Роберт Моррис
.%A Кен Томпсон
.%T "защита паролем UNIX"
.Re
.Sh ПРИМЕЧАНИЯ
Команда
.Nm yppasswd
на самом деле является всего лишь ссылкой на
.Nm .
.Sh ИСТОРИЯ
Команда 
.Nm
появилась в
.At v6 .
