.\" Copyright (c) 1991 Кит Мюллер.
.\" Copyright (c) 1993
.\"	    Ректоры Калифорнийского университета. Все права защищены.
.\"
.\" Этот код основан на программном обеспечении, предоставленном в Беркли
.\" Китом Миллером из Калифорнийского университета в Сан-Диего.
.\"
.\" Распространение и использование в исходном коде и двоичной форме, с использованием или без использования
.\" модификаций, если следующие условия
.\" соблюдаются:
.\" 1. При распространении исходного кода должно сохраняться вышеуказанное уведомление
.\"    об авторских правах, этот список условий и следующий дисклеймер.
.\" 2. При распространиении в двоичной форме должно воспроизводиться уведомление об авторских правах,
.\"    этот список условий и следующий ниже отказ от ответственности в
.\"    документации и/или других материалах, поставляемых с дистрибутивом.
.\" 3. Ни название университета, ни имена его участников не могут быть использованы для
.\"    поддержки или продвижения продуктов, созданных на основе данного программного обеспечения,
.\"    без специального предварительного письменного согласия.
.\"
.\" ДАННОЕ ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЯЕТСЯ ПРАВООБЛАДАТЕЛЯМИ И СОАВТОРАМИ ``КАК ЕСТЬ'', И 
.\" МЫ ОТКАЗЫВАЕМСЯ ОТ ЛЮБЫХ ПОДРАЗУМЕВАЕМЫХ ОБЯЗАТЕЛЬСТВ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ, 
.\" ПОДРАЗУМЕВАЕМЫЕ ГАРАНТИИ ТОВАРНОЙ ПРИГОДНОСТИ И НЕПРИГОДНОСТИ ДЛЯ ОПРЕДЕЛЕННОЙ
.\" ЦЕЛИ. НИ В КОЕМ СЛУЧАЕ ПРАВООБЛАДАТЕЛИ ИЛИ СОВАТОРЫ НЕ НЕСУТ ОТВЕТСТВЕННОСТИ
.\" ЗА ЛЮБЫЕ ПРЯМЫЕ, КОСВЕННЫЕ, СЛУЧАЙНЫЕ, ОСОБЫЕ, ПОКАЗАТЕЛЬНЫЕ ИЛИ ЛОГИЧЕСКИ ВЫТЕКАЮЩИЕ
.\" УБЫТКИ (ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ ИМИ, ПРИОБРЕТЕНИЕ ЗАМЕНЯЮЩИХ ТОВАРОВ ИЛИ УСЛУГ;
.\" ПОТЕРЮ ВОЗМОЖНОСТИ ИСПОЛЬЗОВАНИЯ, ДАННЫХ ИЛИ ПРИБЫЛИ; ИЛИ ПРЕКРАЩЕНИЕ ДЕЯТЕЛЬНОСТИ)
.\" НЕЗАВИСИМО ОТ ПРИЧИНЕННОГО УЩЕРБА И НА ОСНОВАНИИ ЛЮБОЙ ТЕОРИИ ОТВЕТСТВЕННОСТИ, БУДЬ ТО В РАМКАХ КОНТРАКТА, 
.\" ПРЯМОЙ ОТВЕТСТВЕННОСТИ ИЛИ ДЕЛИКТА (ВКЛЮЧАЯ ХАЛАТНОСТЬ ИЛИ ИНОЕ), ВОЗНИКШЕГО КАКИМ-ЛИБО ОБРАЗОМ
.\" В РЕЗУЛЬТАТЕ ИСПОЛЬЗОВАНИЯ ДАННОГО ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ, ДАЖЕ ЕСЛИ ВЫ БЫЛИ ОСВЕДОМЛЕНЫ О ВОЗМОЖНОСТИ
.\" ТАКОГО УЩЕРБА.
.\"
.\"     @(#)pr.1	8.3 (Berkeley) 4/18/94
.\"
.Dd 3 июля, 2004 год
.Dt PR 1
.Os
.Sh НАЗВАНИЕ
.Nm pr
.Nd print files
.Sh СИНТАКСИС
.Nm
.Bk -words
.Op Ar \&+страница
.Ek
.Bk -words
.Op Fl Ar столбец
.Ek
.Op Fl adFfmprt
.Bk -words
.Oo
.Op Fl e
.Op Ar символ
.Op Ar интервал
.Oc
.Ek
.Bk -words
.Op Fl L Ar локаль
.Ek
.Bk -words
.Op Fl h Ar заголовок
.Ek
.Bk -words
.Oo
.Op Fl i
.Op Ar символ
.Op Ar интервал
.Oc
.Ek
.Bk -words
.Op Fl l Ar строки
.Ek
.Bk -words
.Op Fl o Ar смещение
.Ek
.Bk -words
.Oo
.Op Fl s
.Op Ar символ
.Oc
.Ek
.Bk -words
.Oo
.Op Fl n
.Op Ar символ
.Op Ar ширина
.Oc
.Ek
.Bk -words
.Op Fl w Ar ширина
.Ek
.Op -
.Op Ar
.Sh ОПИСАНИЕ
Утилита
.Nm
является фильтром для печати и разбивки на страницы текстовых файлов.
При указании нескольких входных файлов каждый из них читается, форматируется
и выводится в стандартный вывод.
По умолчанию входные данные разделяются на страницы по 66 строк, каждая из которых содержит
.Bl -bullet
.It
5-строчный заголовок с номером страницы, датой, временем и
путём к файлу.
.It
5-строчный колонтитул, состоящий из пустых строк.
.El
.Pp
Если стандартный вывод связан с терминалом,
диагностические сообщения подавляются до тех пор, пока
.Nm
утилита не завершит обработку.
.Pp
При указании вывода в несколько столбцов,
текстовые колонки имеют равную ширину.
По умолчанию текстовые столбцы разделены как минимум одним
.Em <пробел> .
Строки ввода, которые не умещаются в текстовый столбец, обрезаются.
Строки не обрезаются при выводе в один столбец.
.Sh ОПЦИИ
В следующих описаниях опций, столбец, строки, смещение, страница и
ширина являются положительными десятичными числами, а интервал - неотрицательным десятичным числом.
.Bl -tag -width 4n
.It Ar \&+страница
Начает вывод с номера страницы
.Ar страница
или отформатированного ввода.
.It Fl Ar столбец
Создает вывод шириной
.Ar столбцы
(по умолчанию 1), который записывается вертикально
вниз по каждой колонке в том порядке, в котором текст
поступает из входного файла.
Опции
.Fl e
и
.Fl i
предполагаются.
Эту опцию не следует использовать с
.Fl m .
При использовании с
.Fl t
используется минимальное количество строк для отображения вывода.
(Для более общего создания колонок и изменения формы текстовых файлов без дополнительного
форматирования смотрите
.Xr rs 1
утилиту.)
.It Fl a
Изменить эффект опции
.Fl столбец
так, чтобы столбцы заполнялись по странице в порядке распределения по кругу
(например, когда column равно 2, первая строка ввода находится в колонке
1, вторая - в колонке 2, третья является второй строкой
в колонке 1 и т.д.).
Эта опция требует использования
.Fl столбец
опции.
.It Fl d
Создает вывод с двойным интервалом.
Дополнительный
.Em <новая_строка>
символ выводится после каждой
.Em <новая_строка>
найденной на входе.
.It Fl e Xo
.Op Ar символ Ns
.Op Ar интервал
.Xc
Расширить каждый входной
.Em <табуляция>
до следующей большей позиции колонки,
указанной формулой
.Ar n*отступ+1 ,
где
.Em n
- это целое число > 0.
Если
.Ar 
равно нулю или опущено, по умолчанию используется 8.
Все
.Em <табуляция>
во входных данных расширяются до соответствующего
количества
.Em <пробелы> .
Если указан любой нецифровой символ
.Ar символ ,
он используется в качестве символа табуляции на входе.
.It Fl F
Использует символ
.Em <перевод_формата>
для новых страниц,
вместо стандартного поведения, которое использует
последовательность
.Em <новая_строка>
символов.
.It Fl f
То же, что и
.Fl F
но делает паузу перед началом первой страницы, если стандартный вывод - терминал.
.It Fl h Ar заголовок
Использует строку
.Ar заголовок
чтобы заменить имя
.Ar файл
в строке заголовка.
.It Fl i Xo
.Op Ar символ Ns
.Op Ar отступ
.Xc
В выводе заменяет несколько
.Em <пробел>
на
.Em <табуляция>
каждый раз, когда два или более
смежных
.Em <пробел>
достигают позиций колонок
.Ar отступ+1 ,
.Ar 2*отступ+1 ,
и т.д.
Если
.Ar отступ
равен нулю или опущен, используется стандартная настройка
.Em <табуляция>
на каждой восьмой позиции колонки.
Если указан любой нецифровой символ,
.Ar символ ,
он используется в качестве выходного
.Em <табуляция> 
символа.
.It Fl L Ar локаль
Использует
.Ar локаль
указанную в аргументе, вместо той, что найдена в окружении.
Используйте "C", чтобы сбросить локаль к стандартной.
.It Fl l Ar строки
Переопределяет стандартное значение в 66 строк и установить длину страницы равной
.Ar строки .
Если
.Ar строки
не больше суммы глубин заголовка и подвала
(в строках), утилита
.Nm
подавляет вывод как заголовка, так и подвала, как если бы была в действии опция
.Fl t .
.It Fl m
Объединить содержимое нескольких файлов.
Одна строка из каждого файла, указанного операндом файла,
записывается рядом в текстовые колонки фиксированной ширины,
в терминах количества позиций колонок.
Количество текстовых колонок зависит от количества
успешно открытых операндов файла.
Максимальное количество объединенных файлов зависит от ширины страницы и
лимита открытых файлов на процесс.
Опции
.Fl e
и
.Fl i
предполагаются.
.It Fl n Xo
.Op Ar символ Ns
.Op Ar ширина
.Xc
Указывает
.Ar ширина
цифровую нумерацию строк.
По умолчанию для
.Ar ширина ,
если не указано, равно 5.
Номер занимает первые
.Ar ширина
позиций колонок каждой текстовой колонки или каждой строки
.Fl m
вывода.
Если
.Ar символ
(любой нецифровой символ) указан, он добавляется к номеру строки,
чтобы отделить его от всего, что следует за ним.
По умолчанию для
.Ar символ
является
.Em <табуляция> .
Номера строк длиннее
.Ar ширина
колонок обрезаются.
.It Fl o Ar смещение
Каждая строка вывода предваряется
.Ar смещение
.Em <пробелы> .
Если опция
.Fl o
не указана, по умолчанию равно нулю.
Занимаемое пространство добавляется к ширине строки вывода.
.It Fl p
Пауза перед каждой страницей, если стандартный вывод - терминал.
.Nm
будет писать символ предупреждения в стандартную ошибку и ждать,
пока на терминале не будет прочитан символ возврата каретки.
.It Fl r
Не пишет диагностические отчеты при неудаче открытия файла.
.It Fl s Ar символ
Разделяет текстовые колонки одним символом
.Ar символ
вместо соответствующего количества
.Em <пробел>
(по умолчанию для
.Ar символ
является 
.Em <табуляция> 
символ).
.It Fl t
Не отображет ни пятистрочный идентифицирующий
заголовок, ни пятистрочный подвал, обычно предоставляемые для каждой страницы.
Прекратить печать после последней строки каждого файла без заполнения до
конца страницы.
.It Fl w Ar ширина
Установите ширину строки до
.Ar ширина
позиций колонок только для вывода в несколько текстовых колонок.
Если опция
.Fl w
не указана и опция
.Fl s
не указана, ширина по умолчанию составляет 72.
Если опция
.Fl w
не указана и опция
.Fl s
указана, ширина по умолчанию составляет 512.
.It Ar файл
Путь к файлу, который будет напечатан.
Если операнды
.Ar файл
не указаны, или если операнд
.Ar файл
является
.Sq Fl ,
используется стандартный ввод.
Стандартный ввод используется только если операнды
.Ar файл
не указаны, или если операнд
.Ar файл
является
.Sq Fl .
.El
.Pp
Опция
.Fl s
не позволяет отделять букву опции от её аргумента,
и опции
.Fl e ,
.Fl i ,
и
.Fl n
требуют, чтобы оба аргумента, если они присутствуют, не были отделены от буквы опции.
.Sh СТАТУС ЗАВЕРШЕНИЯ
.Ex -std
.Sh ДИАГНОСТИКА
Если
.Nm
получает сигнал прерывания во время вывода в терминал, она
выводит все накопленные сообщения об ошибках на экран перед
завершением работы.
.Pp
Сообщения об ошибках выводятся на стандартный поток ошибок во время процесса печати
(если вывод перенаправлен) или после завершения успешной печати всех файлов
(при печати в терминал).
.Sh СМОТРИТЕ ТАКЖЕ
.Xr cat 1 ,
.Xr more 1 ,
.Xr rs 1
.Sh СТАНДАРТЫ
Утилита
.Nm
и
.St -p1003.1-2001
совместимы.
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.At v1 .
.Sh БАГИ
Утилита
.Nm
не распознает многобайтовые символы.
