.\" Copyright (c) 1983, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Этот код является производным от программного обеспечения, предоставленного в Беркли
.\" Робертом Эльц из Мельбурнского университета.
.\"
.\" Распространение и использование в исходном коде и двоичной форме, с использованием или без использования
.\" модификаций, если следующие условия
.\" соблюдаются:
.\" 1. При распространении исходного кода должно сохраняться вышеуказанное уведомление
.\"    об авторских правах, этот список условий и следующий дисклеймер.
.\" 2. При распространиении в двоичной форме должно воспроизводиться уведомление об авторских правах,
.\"    этот список условий и следующий ниже отказ от ответственности в
.\"    документации и/или других материалах, поставляемых с дистрибутивом.
.\" 3. Ни название университета, ни имена его участников не могут быть использованы для
.\"    поддержки или продвижения продуктов, созданных на основе данного программного обеспечения,
.\"    без специального предварительного письменного согласия.
.\"
.\" ДАННОЕ ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЯЕТСЯ ПРАВООБЛАДАТЕЛЯМИ И СОАВТОРАМИ ``КАК ЕСТЬ'', И 
.\" МЫ ОТКАЗЫВАЕМСЯ ОТ ЛЮБЫХ ПОДРАЗУМЕВАЕМЫХ ОБЯЗАТЕЛЬСТВ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ, 
.\" ПОДРАЗУМЕВАЕМЫЕ ГАРАНТИИ ТОВАРНОЙ ПРИГОДНОСТИ И НЕПРИГОДНОСТИ ДЛЯ ОПРЕДЕЛЕННОЙ
.\" ЦЕЛИ. НИ В КОЕМ СЛУЧАЕ ПРАВООБЛАДАТЕЛИ ИЛИ СОВАТОРЫ НЕ НЕСУТ ОТВЕТСТВЕННОСТИ
.\" ЗА ЛЮБЫЕ ПРЯМЫЕ, КОСВЕННЫЕ, СЛУЧАЙНЫЕ, ОСОБЫЕ, ПОКАЗАТЕЛЬНЫЕ ИЛИ ЛОГИЧЕСКИ ВЫТЕКАЮЩИЕ
.\" УБЫТКИ (ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ ИМИ, ПРИОБРЕТЕНИЕ ЗАМЕНЯЮЩИХ ТОВАРОВ ИЛИ УСЛУГ;
.\" ПОТЕРЮ ВОЗМОЖНОСТИ ИСПОЛЬЗОВАНИЯ, ДАННЫХ ИЛИ ПРИБЫЛИ; ИЛИ ПРЕКРАЩЕНИЕ ДЕЯТЕЛЬНОСТИ)
.\" НЕЗАВИСИМО ОТ ПРИЧИНЕННОГО УЩЕРБА И НА ОСНОВАНИИ ЛЮБОЙ ТЕОРИИ ОТВЕТСТВЕННОСТИ, БУДЬ ТО В РАМКАХ КОНТРАКТА, 
.\" ПРЯМОЙ ОТВЕТСТВЕННОСТИ ИЛИ ДЕЛИКТА (ВКЛЮЧАЯ ХАЛАТНОСТЬ ИЛИ ИНОЕ), ВОЗНИКШЕГО КАКИМ-ЛИБО ОБРАЗОМ
.\" В РЕЗУЛЬТАТЕ ИСПОЛЬЗОВАНИЯ ДАННОГО ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ, ДАЖЕ ЕСЛИ ВЫ БЫЛИ ОСВЕДОМЛЕНЫ О ВОЗМОЖНОСТИ
.\" ТАКОГО УЩЕРБА.
.\"
.\"	from: @(#)quota.1	8.1 (Berkeley) 6/6/93
.\"
.Dd 3 февраля, 2007 год
.Dt QUOTA 1
.Os
.Sh НАЗВАНИЕ
.Nm quota
.Nd display disk usage and limits
.Sh СИНТАКСИС
.Nm
.Op Fl ghlu
.Op Fl f Ar путь
.Op Fl v | q | r
.Nm
.Op Fl hlu
.Op Fl f Ar путь
.Op Fl v | q | r
.Ar пользователь ...
.Nm
.Fl g
.Op Fl hl
.Op Fl f Ar путь
.Op Fl v | q | r
.Ar группа ...
.Sh ОПИСАНИЕ
Утилита
.Nm
утилита отображает использование диска пользователями и их ограничения.
По умолчанию печатаются только пользовательские квоты.
Использование дискового блока и его ограничения показаны в виде блоков по 1024 байта.
.Pp
Доступны следующие опции:
.Bl -tag -width indent
.It Fl f Ar путь
Отображает информацию о квоте только для той файловой системы,
которая содержит указанный путь.
Это может быть любой файл в подключенной файловой системе.
.It Fl g
Выводит групповые квоты для группы,
членом которой является пользователь.
.It Fl h
"Удобочитаемый" вывод.
Использует суффиксы единиц измерения: Байт, Килобайт, Мегабайт, Гигабайт, Терабайт и Петабайт.
.It Fl l
Не сообщает о квотах на
.Tn NFS
файловые системы.
.It Fl q
Выводит более краткое сообщение,
содержащее только информацию
о файловых системах, использование которых превышает квоту.
Флаг
.Fl q
имеет приоритет над
.Fl v
флагом.
.It Fl r
Отображает исходную информацию о квоте в том виде, в каком она отображается в структуре квот.
Ненулевые значения времени также будут отображаться в
.Xr ctime 3
формате.
Этоа опция подразумевает
.Fl v
и переопределит
.Fl q
флаг.
.It Fl u
Отображает пользовательские квоты.
Это значение используется по умолчанию, если
.Fl g
указана.
.It Fl v
Отображает квоты для файловых систем,
в которых не выделено место для хранения.
.El
.Pp
При указании как
.Fl g ,
так и
.Fl u
отображает как пользовательские квоты, так и групповые (для
пользователя).
.Pp
Только суперпользователь может использовать флаг
.Fl u
и опционаьный аргумент
.Ar пользователь
чтобы просмотреть ограничения для других пользователей.
Пользователи, не являющиеся суперпользователями, могут использовать флаг
.Fl g
опциональный аргумент
.Ar группа
для просмотра только ограничений групп, членами которых они являются.
.Pp
Утилита
.Nm
пытается сообщить о квотах всех подключенных файловых систем.
Если файловая система подключена через
.Tn NFS ,
он попытается связаться с демоном
.Xr rpc.rquotad 8
на
.Tn NFS
сервере.
Для
.Tn UFS
файловых систем, квоты должны быть включены в
.Pa /etc/fstab .
Если
.Nm
завершается с ненулевым статусом, в одной или нескольких файловых системах
превышена квота или путь, указанный с опцией
.Fl f
не существует.
.Pp
Если флаг
.Fl l
указан,
.Nm
не будет проверять
.Tn NFS
файловые системы.
.Sh ФАЙЛЫ
.Bl -tag -width quota.group -compact
.It Pa quota.user
находится в корневом каталоге файловой системы с пользовательскими квотами
.It Pa quota.group
находится в корневом каталоге файловой системы с групповыми квотами
.It Pa /etc/fstab
чтобы найти имена и расположения файловых систем
.El
.Sh СМОТРИТЕ ТАКЖЕ
.Xr quotactl 2 ,
.Xr ctime 3 ,
.Xr fstab 5 ,
.Xr edquota 8 ,
.Xr quotacheck 8 ,
.Xr quotaon 8 ,
.Xr repquota 8 ,
.Xr rpc.rquotad 8
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.Bx 4.2 .
