.\" Copyright (c) 1999-2002 Proofpoint, Inc. and its suppliers.
.\"	All rights reserved.
.\" Copyright (c) 1985, 1987, 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\"
.\" By using this file, you agree to the terms and conditions set
.\" forth in the LICENSE file which can be found at the top level of
.\" the sendmail distribution.
.\"
.\"
.\"	$Id: vacation.1,v 8.35 2013-11-22 20:52:02 ca Exp $
.\"
.TH VACATION 1 "$Date: 2013-11-22 20:52:02 $"
.SH ИМЯ
vacation
\- авто-ответчик для E-mail
.SH СИНТАКСИС
.B vacation
.RB [ \-a
.IR alias ]
.RB [ \-C
.IR cffile ]
.RB [ \-d ]
.RB [ \-f
.IR database ]
.RB [ \-i ]
.RB [ \-I ]
.RB [ \-j ]
.RB [ \-l ]
.RB [ \-m
.IR message ]
.RB [ \-R
.IR returnaddr ]
.RB [ \-r
.IR interval ]
.RB [ \-s
.IR address ]
.RB [ \-t
.IR time ]
.RB [ \-U ]
.RB [ \-x ]
.RB [ \-z ]
.I login
.SH ОПИСАНИЕ
.B Vacation
возвращает сообщение,
.IR ~/.vacation.msg
по умолчанию, отправитель информируется о том, что Вы в данный момент не
читаете свою почту.
Сообщение отправляется каждому отправителю только только один раз в течение интервала ответа (смотрите
.B \-r
ниже).
Информация о предполагаемом использовании находится в файле
.I .forward
Например, Ваш файл
.I .forward
может содержать:
.IP
\eeric, "|/usr/bin/vacation -a allman eric"
.PP
который отправлял бы Вам (полагая, что Ваше имя пользователя eric) и
отвечал бы на любые сообщения для
``eric''
или
``allman''.
.PP
Доступные параметры:
.TP
.BI \-a " alias"
Обрабатывает сообщения для псевдонима
.I alias
таким же образом, как и полученные сообщения на имя пользователя.
.TP
.BI \-C " cfpath"
Указывает путь к файлу конфигурации отправляемого письма.  
Этот параметр игнорируется, если указан ключ
.B \-U
Этот параметр по умолчанию использует стандартный файл конфигурации отправляемого письма, 
находящийся в большинстве систем по адресу /etc/mail/sendmail.cf.
.TP
.B \-d
Отправляет сообщения об ошибках/отладке в stderr вместо syslog.
В противном случае, фатальные ошибки, такие как вызов
.B vacation
с ложными параметрами или с несуществующими именами пользователей в параметрах
.IR login s,
регистрируются в системном журнале с помощью
.Xr syslog 8 .
Этот параметр должен быть использован только в командной строке, а не в Вашем файле
.I .forward .
.TP
.BI \-f " filename"
Использовать
.I filename
в качестве имени базы данных вместо
.IR ~/.vacation.db
или
.IR ~/.vacation.{dir,pag} .
Если только
.I filename
не начинается с / не относится к ~.
.TP
.B \-i
Инициализировать файлы базы данных. Этот параметр должен использоваться
прежде, чем вы измените ваш файл
.I .forward .
Этот параметр должен использоваться только в командной строке, а не в Вашем файле
.I .forward .
.TP
.B \-I
Такой же параметр, что и
.B \-i
(для обратной совместимости).
Этот параметр должен использоваться только в командной строке, а не в Вашем файле
.I .forward .
.TP
.B \-j
Отвечает на сообщение независимо от того, указано ли имя пользователя (login) в качестве 
получателя сообщения.
Не используйте эту команду, если вы не уверены в последствиях.
Например, это может вынудить
.i vacation
отвечать на сообщения из списка рассылка, что может привести к удалению
вас из списка.
.TP
.B \-l
Отображать содержимое файла из базы данных vacation, включая адрес
и связанное с ним время последнего автоматического ответа на этот адрес.
Этот параметр должен использоваться только в командной строке, а не в Вашем файле
.I .forward .
.TP
.BI \-m " filename"
Использовать
.I filename
в качестве имени файла, содержащего сообщение, отправляемое вместо
.IR ~/.vacation.msg .
Если только
.I filename
не начинается с / не относится к ~.
.TP
.BI \-R " returnaddr"
Задать адрес отправителя в качестве адреса для ответа
.TP
.BI \-r " interval"
Установить интервал для ответа длительностью
.I interval
дней.  Значение по умолчанию равно одной неделе.
Интервал ``0'' или
``infinite''
(на самом деле, любой не-числовой символ) никогда не отправит больше
одного ответа.
Параметр
.B \-r
должен использоваться только тогда, когда база данных vacation запущена
(смотрите
.B \-i
выше).
.TP
.BI \-s " address"
Использовать
.I address
вместо входящего сообщения в строке
.I From
в качестве получателя сообщения vacation.
.TP
.BI \-t " time"
Игнорируется, доступно только для совместимости с программой Sun's vacation.
.TP
.B \-U
Не пытаться искать
.I login
в файле паролей.
Параметры -f и -m должны использоваться для указания файлов базы данных и файла сообщения,
так как домашний каталог не задан по умолчанию для этих параметров.
.TP
.B \-x
Читать список исключений из stdin (по одному адресу на строку).
Письма, поступающие с адреса 
из этого списка исключений, останутся без ответа от
.BR vacation .
Возможно исключить полные домены, указав
``@domain''
в качестве элемента списка исключений.
Этот параметр должен использоваться только в командной строке, а не в Вашем файле
.I .forward .
.TP
.B \-z
Установить в качестве отправителя сообщения от vacation
``<>''
вместо пользователя.
Это, вероятно, нарушает требования RFC, поскольку стандарт не требует, чтобы сообщения от vacation
содержали нулевой обратный путь.
.PP
.B Vacation
читает первую строку из стандартного ввода UNIX
(строку ``From'' ) для определения 
отправителя. Sendmail(8) включает строку
``From''
автоматически.
.PP
Сообщение не будет отправлено, если только
.I login
(или
.I alias
указанный с помощью параметра
.B \-a )
не является частью заголовков письма
``To:''
или
``Cc:'' .
Ни на какие сообщения от
``???-REQUEST'',
``???-RELAY'',
``???-OWNER'',
``Postmaster'',
``UUCP'',
``MAILER'',
или
``MAILER-DAEMON''
не будут даны ответы (регистр в этих строках
имеет значение) и они не получат уведомлений в случает, если строки
``Precedence: bulk''
или
``Precedence: junk''
включенs в заголовок письма.
Люди, которые отправляли Вам сообщения, хранятся в базах данных
db(3)
или
dbm(3)
файлов
.I .vacation.db
или
.I .vacation.{dir,pag}
в Вашем домашнем каталоге.
.PP
.B Vacation
ожидает наличия файла
.IR .vacation.msg ,
в вашем домашнем каталоге, содержащего сообщение, отправляемое обратно каждому
отправителю. Это должно быть полноценное сообщения (включая заголовки).
Например, оно может содержать:
.IP
.nf
From: eric@CS.Berkeley.EDU (Eric Allman)
Subject: I am on vacation
Delivered-By-The-Graces-Of: The Vacation program
Precedence: bulk

I am on vacation until July 22. If you have something urgent,
please contact Keith Bostic bostic@CS.Berkeley.EDU.
--eric
.fi
.SH ФАЙЛЫ
.TP 1.8i
~/.vacation.db
файл базы данных по умолчанию для db(3)
.TP 1.8i
~/.vacation.{dir,pag}
файл базы данных по умолчанию для dbm(3)
.TP
~/.vacation.msg
сообщение для отправки по умолчанию
.SH СМОТРИТЕ ТАКЖЕ
.Xr sendmail 8 ,
.Xr syslog 8 ,
.SH ИСТОРИЯ
Команда
.B vacation
появилась в
4.3BSD.
