.\" $Id: apropos.1,v 1.51 2020/10/01 22:50:00 schwarze Exp $
.\"
.\" Copyright (c) 2011, 2012 Kristaps Dzonsons <kristaps@bsd.lv>
.\" Copyright (c) 2011,2012,2014,2017,2018 Ingo Schwarze <schwarze@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: Октябрь 1 2020 $
.Dt APROPOS 1
.Os
.Sh ИМЯ
.Nm apropos ,
.Nm whatis
.Nd ищет базы данных страниц руководства 
.Sh КРАТКОЕ ОПИСАНИЕ
.Nm
.Op Fl afk
.Op Fl C Ar file
.Op Fl M Ar path
.Op Fl m Ar path
.Op Fl O Ar outkey
.Op Fl S Ar arch
.Op Fl s Ar section
.Ar expression ...
.Sh ОПИСАНИЕ
Утилиты
.Nm apropos
и
.Nm whatis
запрашивают базы данных страниц руководства, созданные с помощью 
.Xr makewhatis 8 ,
оценивания
.Ar expression
для каждого файла в каждой базе данных.
По умолчанию в них отображаются названия, номера разделов и строки
описания всех соответствующих руководств.
.Pp
По умолчанию,
.Nm
ищет базу данных
.Xr makewhatis 8
в путях по умолчанию, указанных
.Xr man 1
и использует нечувствительное к регистру расширенное сопоставление регулярных выражений с именами и описаниями, приведенными вручную
.Pq the Li \&Nm No and Li \&Nd No macro keys .
Множественные термины подразумевают попарное использование
.Fl o .
.Pp
.Nm whatis
это синоним для
.Nm
.Fl f .
.Pp
Возможны следующие параметры:
.Bl -tag -width Ds
.It Fl a
Вместо того чтобы показывать только строки заголовка, показывает все страницы руководства целиком,
как бы сделал
.Xr man 1
.Fl a
.
Если стандартным выходом является оконечное устройство и
.Fl c
не указаны, использует
.Xr less 1
чтобы пронумеровать их по страницам.
В режиме
.Fl a
, параметры
.Fl IKOTW
описанный в инструкции
.Xr mandoc 1
также доступны.
.It Fl C Ar file
Указывает альтернативную конфигурацию
.Ar file
в формате
.Xr man.conf 5
.
.It Fl f
Ищет все слова в
.Ar выражении
только в названиях страниц с ручным управлением.
Поиск выполняется без учета регистра и выполняется только по целым словам.
В этом режиме макрокоманды, операторы сравнения и логические операторы
недоступны.
.It Fl k
Поддерживает целый синтакс
.Ar выражения
.
Это значение по умолчанию для
.Nm .
.It Fl M Ar path
Использует путь, разделенный двоеточием, вместо списка
искомых путей по умолчанию для базы данных
.Xr makewhatis 8
.
Недопустимые пути или пути без ручных баз данных игнорируются.
.It Fl m Ar path
Добавляет пути, разделенные двоеточием, в список искомых путей
базы данных
.Xr makewhatis 8
.
Недопустимые пути или пути без ручных баз данных игнорируются.
.It Fl O Ar outkey
Показывает значения, связанные с ключом
.Ar outkey
вместо описания из инструкции
.It Fl S Ar arch
Ограничивает поиск страницами для указанной архитектуры
.Xr machine 1
.
.Ar arch
регистр не учитывается.
По умолчанию отображаются страницы для всех архитектур.
.It Fl s Ar section
Ограничивает поиск указанным разделом руководства.
По умолчанию отображаются страницы из всех разделов.
См.
.Xr man 1
для получения списка разделов.
.El
.Pp
Параметры
.Fl chlw
также поддерживаются и документированы в
.Xr man 1 .
Параметры
.Fl fkl
являются взаимоисключающими и перекрывают друг друга.
.Pp

.Ar выражение
состоит из поисковых терминов, соединенных логическими операторами
.Fl a
.Pq и
и
.Fl o
.Pq или .
Оператор
.Fl a
имеет приоритет над
.Fl o
и то, и другое оценивается слева направо.
.Bl -tag -width Ds
.It \&( Ar expr No \&)
Истинно, если подвыражение
.Ar expr
истинно.
.It Ar expr1 Fl a Ar expr2
Истинно, если и
.Ar expr1 ,
и
.Ar expr2
истинны (логично
.Sq и ) .
.It Ar expr1 Oo Fl o Oc Ar expr2
Истинно если
.Ar expr1
и/или
.Ar expr2
вычисляет значение истинно (логическое
.Sq или ) .
.It Ar term
Истинно, если
.Ar term
удовлетворен.
У этого есть синтаксис
.Sm off
.Oo
.Op Ar key Op , Ar key ...
.Pq Cm = | \(ti
.Oc
.Ar val ,
.Sm on
где
.Ar key
is an
.Xr mdoc 7
macro to query and
.Ar val
is its value.
См.
.Sx Macro Keys
для получения списка доступных ключей.
Оператор
.Cm =
вычисляет подстроку, в то время как
.Cm \(ti
вычисляет расширенное регулярное выражение, учитывающее регистр символов.
.It Fl i Ar term
Если
.Ar term
является регулярным выражением, оно
вычисляется без учета регистра символов.
Не влияет на условия подстроки.
.El
.Pp
Результаты сортируются сначала по номеру раздела в
порядке возрастания, затем по названию страницы в порядке возрастания
.Xr ascii 7
в алфавитном порядке, без учета регистра.
.Pp
Каждая выходная строка форматируется следующим образом
.Pp
.D1 name[, name...](sec) \- description
.Pp
Где
.Dq имя
является названием руководства,
.Dq сектор
является разделом руководства, и
.Dq описание
это краткое описание руководства.
Если для руководства указана архитектура, она отображается в виде
.Pp
.D1 name(sec/arch) \- description
.Pp
К полученным руководствам можно получить доступ как
.Pp
.Dl $ man \-s sec name
.Pp
Если в выходных данных указана архитектура, используется
.Pp
.Dl $ man \-s sec \-S arch name
.Ss Macro Keys
Запросы обрабатываются по подмножеству
.Xr mdoc 7
макроэлементы, индексируемые
.Xr makewhatis 8 .
В дополнение к перечисленным ниже макрокомандам, специальная клавиша
.Cm any
может использоваться, чтобы сопоставить с любым доступным макроключем.
.Pp
Названия и описание:
.Bl -column "xLix" description -offset indent -compact
.It Li \&Nm Ta manual name
.It Li \&Nd Ta one-line manual description
.It Li arch Ta machine architecture (case-insensitive)
.It Li sec  Ta manual section number
.El
.Pp
Sections and cross references:
.Bl -column "xLix" description -offset indent -compact
.It Li \&Sh Ta section header (excluding standard sections)
.It Li \&Ss Ta subsection header
.It Li \&Xr Ta cross reference to another manual page
.It Li \&Rs Ta bibliographic reference
.El
.Pp
Semantic markup for command line utilities:
.Bl -column "xLix" description -offset indent -compact
.It Li \&Fl Ta command line options (flags)
.It Li \&Cm Ta command modifier
.It Li \&Ar Ta command argument
.It Li \&Ic Ta internal or interactive command
.It Li \&Ev Ta environmental variable
.It Li \&Pa Ta file system path
.El
.Pp
Semantic markup for function libraries:
.Bl -column "xLix" description -offset indent -compact
.It Li \&Lb Ta function library name
.It Li \&In Ta include file
.It Li \&Ft Ta function return type
.It Li \&Fn Ta function name
.It Li \&Fa Ta function argument type and name
.It Li \&Vt Ta variable type
.It Li \&Va Ta variable name
.It Li \&Dv Ta defined variable or preprocessor constant
.It Li \&Er Ta error constant
.It Li \&Ev Ta environmental variable
.El
.Pp
Various semantic markup:
.Bl -column "xLix" description -offset indent -compact
.It Li \&An Ta author name
.It Li \&Lk Ta hyperlink
.It Li \&Mt Ta Do mailto Dc hyperlink
.It Li \&Cd Ta kernel configuration declaration
.It Li \&Ms Ta mathematical symbol
.It Li \&Tn Ta tradename
.El
.Pp
Physical markup:
.Bl -column "xLix" description -offset indent -compact
.It Li \&Em Ta italic font or underline
.It Li \&Sy Ta boldface font
.It Li \&Li Ta typewriter font
.El
.Pp
Text production:
.Bl -column "xLix" description -offset indent -compact
.It Li \&St Ta reference to a standards document
.It Li \&At Ta At No version reference
.It Li \&Bx Ta Bx No version reference
.It Li \&Bsx Ta Bsx No version reference
.It Li \&Nx Ta Nx No version reference
.It Li \&Fx Ta Fx No version reference
.It Li \&Ox Ta Ox No version reference
.It Li \&Dx Ta Dx No version reference
.El
.Pp
In general, macro keys are supposed to yield complete results without
expecting the user to consider actual macro usage.
For example, results include:
.Pp
.Bl -tag -width 3n -offset 3n -compact
.It Li \&Fa
function arguments appearing on
.Ic \&Fn
lines
.It Li \&Fn
function names marked up with
.Ic \&Fo
macros
.It Li \&In
include file names marked up with
.Ic \&Fd
macros
.It Li \&Vt
types appearing as function return types and
.It \&
types appearing in function arguments in the SYNOPSIS
.El
.Sh ENVIRONMENT
.Bl -tag -width MANPAGER
.It Ev MANPAGER
Any non-empty value of the environment variable
.Ev MANPAGER
is used instead of the standard pagination program,
.Xr less 1 ;
see
.Xr man 1
for details.
Only used if
.Fl a
or
.Fl l
is specified.
.It Ev MANPATH
A colon-separated list of directories to search for manual pages; see
.Xr man 1
for details.
Overridden by
.Fl M ,
ignored if
.Fl l
is specified.
.It Ev PAGER
Specifies the pagination program to use when
.Ev MANPAGER
is not defined.
If neither PAGER nor MANPAGER is defined,
.Xr less 1
is used.
Only used if
.Fl a
or
.Fl l
is specified.
.El
.Sh FILES
.Bl -tag -width "/etc/man.conf" -compact
.It Pa mandoc.db
name of the
.Xr makewhatis 8
keyword database
.It Pa /etc/man.conf
default
.Xr man 1
configuration file
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Search for
.Qq .cf
as a substring of manual names and descriptions:
.Pp
.Dl $ apropos =.cf
.Pp
Include matches for
.Qq .cnf
and
.Qq .conf
as well:
.Pp
.Dl $ apropos =.cf =.cnf =.conf
.Pp
Search in names and descriptions using a case-sensitive regular expression:
.Pp
.Dl $ apropos \(aq\(tiset.?[ug]id\(aq
.Pp
Search for all manual pages in a given section:
.Pp
.Dl $ apropos \-s 9 \&.
.Pp
Search for manuals in the library section mentioning both the
.Qq optind
and the
.Qq optarg
variables:
.Pp
.Dl $ apropos \-s 3 Va=optind \-a Va=optarg
.Pp
Do exactly the same as calling
.Nm whatis
with the argument
.Qq ssh :
.Pp
.Dl $ apropos \-\- \-i \(aqNm\(ti[[:<:]]ssh[[:>:]]\(aq
.Pp
The following two invocations are equivalent:
.Pp
.D1 Li $ apropos -S Ar arch Li -s Ar section expression
.Bd -ragged -offset indent
.Li $ apropos \e( Ar expression Li \e)
.Li -a arch\(ti^( Ns Ar arch Ns Li |any)$
.Li -a sec\(ti^ Ns Ar section Ns Li $
.Ed
.Sh SEE ALSO
.Xr man 1 ,
.Xr re_format 7 ,
.Xr makewhatis 8
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification of
.Xr man 1
.Fl k .
.Pp
All options, the
.Nm whatis
command, support for logical operators, macro keys,
substring matching, sorting of results, the environment variables
.Ev MANPAGER
and
.Ev MANPATH ,
the database format, and the configuration file
are extensions to that specification.
.Sh HISTORY
Part of the functionality of
.Nm whatis
was already provided by the former
.Nm manwhere
utility in
.Bx 1 .
The
.Nm
and
.Nm whatis
utilities first appeared in
.Bx 2 .
They were rewritten from scratch for
.Ox 5.6 .
.Pp
The
.Fl M
option and the
.Ev MANPATH
variable first appeared in
.Bx 4.3 ;
.Fl m
in
.Bx 4.3 Reno ;
.Fl C
in
.Bx 4.4 Lite1 ;
and
.Fl S
and
.Fl s
in
.Ox 4.5
for
.Nm
and in
.Ox 5.6
for
.Nm whatis .
The options
.Fl acfhIKklOTWw
appeared in
.Ox 5.7 .
.Sh AUTHORS
.An -nosplit
.An Bill Joy
wrote
.Nm manwhere
in 1977 and the original
.Bx
.Nm
and
.Nm whatis
in February 1979.
The current version was written by
.An Kristaps Dzonsons Aq Mt kristaps@bsd.lv
and
.An Ingo Schwarze Aq Mt schwarze@openbsd.org .
