.\"	$NetBSD: zforce.1,v 1.2 2003/12/28 12:43:43 wiz Exp $
.\"	$OpenBSD: zforce.1,v 1.1 2003/07/29 11:50:09 otto Exp $
.\"
.\" Copyright (c) 2003 Otto Moerbeek <otto@drijf.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd Январь 26, 2007
.Dt ZFORCE 1
.Os
.Sh ИМЯ
.Nm zforce
.Nd обязывает файлы gzip иметь суффикс .gz 
.Sh КРАТКИЙ ОБЗОР
.Nm zforce
.Ar
.Sh ОПИСАНИЕ
The
.Nm
Утилита переименовывает
.Xr gzip 1
файлы с суффиксом
.Sq .gz
таким образом, что
.Xr gzip 1
не будет сжимать файлы дважды.
Это может быть полезно, если имена файлов были усечены при передаче файлов.
Файлы, 
Файлы, у которых есть суффикс
.Sq .gz ,
.Sq -gz ,
.Sq _gz ,
.Sq .tgz
или
.Sq .taz
или файлы, которые не были сжаты с помощью
.Xr gzip 1 ,
игнорируются
.Sh СМОТРЕТЬ ТАКЖЕ
.Xr gzip 1
.Sh ПРЕДОСТЕРЕЖЕНИЯ
.Nm
переписывает существующие файлы без предупреждения.
