.\"
.\" Copyright (c) 2008 Daniel Gerzo
.\" Все права защищены.
.\"
.\" Распространение и использование в исходных и двоичных формах, с модификацией или без
.\" модификацией, разрешены при соблюдении следующих условий
.\" соблюдены:
.\" 1. Перераспределение исходного кода должно сохранять вышеуказанное уведомление об авторских правах
.\" уведомление об авторских правах, этот список условий и следующий отказ от ответственности.
.\" 2. Перераспределение в двоичной форме должно воспроизводить вышеуказанное уведомление об авторских правах
.\" уведомление об авторских правах, этот список условий и следующий отказ от ответственности в
.\" документации и/или других материалах, поставляемых вместе с дистрибутивом.
.\"
.\" ДАННАЯ ДОКУМЕНТАЦИЯ ПРЕДОСТАВЛЯЕТСЯ АВТОРОМ ``КАК ЕСТЬ`` И ЛЮБЫЕ ЯВНЫЕ ИЛИ
.\" ПОДРАЗУМЕВАЕМЫХ ГАРАНТИЙ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ, ПОДРАЗУМЕВАЕМЫМИ ГАРАНТИЯМИ
.\" ТОВАРНОГО СОСТОЯНИЯ И ПРИГОДНОСТИ ДЛЯ КОНКРЕТНОЙ ЦЕЛИ, НЕ ПРИНИМАЮТСЯ.
.\" НИ ПРИ КАКИХ ОБСТОЯТЕЛЬСТВАХ АВТОР НЕ НЕСЕТ ОТВЕТСТВЕННОСТИ ЗА ЛЮБЫЕ ПРЯМЫЕ, КОСВЕННЫЕ,
.\" СЛУЧАЙНЫЕ, СПЕЦИАЛЬНЫЕ, ОБРАЗЦОВЫЕ ИЛИ КОСВЕННЫЕ УБЫТКИ (ВКЛЮЧАЯ, НО
.\" НЕ ОГРАНИЧИВАЯСЬ, ПРИОБРЕТЕНИЕ ТОВАРОВ ИЛИ УСЛУГ, ЗАМЕНЯЮЩИХ ИХ, ПОТЕРЮ ИСПОЛЬЗОВАНИЯ,
.\" ДАННЫХ ИЛИ ПРИБЫЛИ; ИЛИ ПЕРЕРЫВА В РАБОТЕ), КАКИМИ БЫ ПРИЧИНАМИ ОНИ НИ БЫЛИ ВЫЗВАНЫ И ПО ЛЮБОМУ
.\" ТЕОРИИ ОТВЕТСТВЕННОСТИ, БУДЬ ТО ДОГОВОР, СТРОГАЯ ОТВЕТСТВЕННОСТЬ ИЛИ ПРАВОНАРУШЕНИЕ
.\" (ВКЛЮЧАЯ НЕБРЕЖНОСТЬ ИЛИ ИНОЕ), ВОЗНИКАЮЩИХ В РЕЗУЛЬТАТЕ ИСПОЛЬЗОВАНИЯ
.\" ДАННОГО ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ, ДАЖЕ ЕСЛИ ВЫ БЫЛИ ПРЕДУПРЕЖДЕНЫ О ВОЗМОЖНОСТИ ТАКОГО УЩЕРБА.
.\"
.Dd 15 марта 2022 г.
.Dt NULLFS 5
.Os
.Sh ИМЯ
.Nm nullfs
.Nd "нулевая файловая система"
.Sh SYNOPSIS
Чтобы включить поддержку этого драйвера,
поместите следующую строку в конфигурационный файл ядра:
.Bd -ragged -offset indent
.Cd "опции NULLFS"
.Ed
.Pp
В качестве альтернативы, чтобы загрузить драйвер как
модуля во время загрузки, поместите следующую строку в
.Xr loader.conf 5 :
.Bd -literal -offset indent
nullfs_load="YES"
.Ed
.Sh ОПИСАНИЕ
Сайт
.Nm
драйвер разрешает
.Fx
ядру монтировать поддерево файловой системы loopback.
.Sh ПРИМЕРЫ
Чтобы смонтировать
.Nm
файловой системы:
.Pp
.Dl "mount_nullfs /usr/ports /home/devel/ports"
.Pp
Также можно определить запись в
.Xr fstab 5
которая выглядит примерно так:
.Pp
.Bd -литеральный
/usr/ports /home/devel/ports nullfs rw 0 0
.Ed
.Sh СМОТРИТЕ ТАКЖЕ
.Xr fstab 5 ,
.Xr mount_nullfs 8
.Sh ИСТОРИЯ
Сайт
.Nm
впервые появился в
.Bx 4.4 .
.Sh АВТОРЫ
.An -nosplit
Сайт
.Nm
реализация ядра была написана
.An Джон Хайдеман .
.Pp
Эта страница руководства была написана
.An Даниэль Герзо Aq Mt danger@FreeBSD.org .



