.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)services.5	8.1 (Berkeley) 6/5/93
.\"
.Dd April 4, 2010
.Dt SERVICES 5
.Os
.Sh ИМЯ
.Nm служба
.Nd база данных о названиях служб
.Sh ОПИСАНИЕ
.Nm
Файл содержит информацию о
известные услуги, доступные в
Интернете.
Для каждой услуги должна присутствовать одна строка
со следующей информацией:
.Bd -unfilled -offset indent
официальное название службы
номер порта
имя протокола
псевдонимы
.Ed
.Pp
Элементы разделяются любым количеством пробелов и/или символов табуляции.
Номер порта и имя протокола считаются одним
.Em item ;
``/'' используется для
разделите порт и протокол (например,\& ``512/tcp'').
``#'' указывает на начало
комментарий; последующие символы до конца строки
не интерпретируется процедурами, выполняющими поиск в файле.
.Pp
Названия служб могут содержать любые печатные
символ, отличный от разделителя полей, новой строки,
или символ комментария.
.Pp
Если
.Dq db
указывается в качестве источника в
.Xr nsswitch.conf 5 ,
.Pa /var/db/services.db
поиске.
Базу данных в
.Pa /var/db/services.db
необходимо обновить с помощью
.Xr services_mkdb 8
после применения изменений в файле служб.
.Sh ВЗАИМОДЕЙСТВИИ
Доступ к NIS
.Pa services.byname
карту можно включить, добавив одиночный ``+'' в отдельную строку
в
.Pa /etc/services
файл
Это приведет к вставке содержимого карты служб NIS.
в том месте, где появляется «+».
.Sh FILES
.Bl -tag -width /etc/services -compact
.It Pa /etc/services
.Nm
файл находится в
.Pa /etc .
.El
.Sh СМОТРИТЕ ТАКЖЕ
.Xr getservent 3 ,
.Xr nsswitch.conf 5 ,
.Xr services_mkdb 8
.Sh ИСТОРИЯ
.Nm
формат файла появился в
.Bx 4.2 .
.Sh ОШИБКИ
Вместо статического файла следует использовать сервер имен.
