.\" Copyright (c) 2020 Gordon Bergling
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.От 27 апреля 2020 г.
.Dt UNIONFS 5 
.Os 
.Sh ИМЯ 
.Nm unionfs
.Nd "UNION FS"
.Sh КРАТКОЕ ОПИСАНИЕ
Чтобы скомпилировать этот драйвер в ядро, 
поместите следующие строки в свой файл конфигурации 
ядра:
.Bd -ragged -offset indent 
.Cd "option UNIONFS"
.Ed 
.Pp 
В качестве альтернативы, чтобы загрузить драйвер как модуль 
во время загрузки, поместите следующую строку в файл
.Xr loader.conf 5 :
.Bd -буквенный отступ со смещением 
unionfs_load="YES"
.Ed 
.Sh ОПИСАНИЕ
Драйвер UNIONFS представляет собой реализацию стекируемой файловой системы unification.
.Sh СМОТРИТЕ ТАКЖЕ
.Xr mount_unionfs 8
.Sh СТАНДАРТЫ 
.Rs 
.%T Union монтируется в версии 4.4 BSD-Lite
.%A Дж. С. Пендри 
.%A М. К. МаКкусик
.%R Материалы технической конференции USENIX по UNIX и передовым вычислительным системам
.%D Декабрь 1995 г. 
.Re 
.Pp 
.Rs 
.%T Тюрьмы: заключение всемогущего рута 
.%A П. Х. Камп
.%A Р. Н . М. Уотсон 
.%R Материалы Второй Международной конференции по системному администрированию и сетевым технологиям (SANE2000)
.%D Май 2000 г.
.Re 
.Sh ИСТОРИЯ 
Драйвер устройства 
.Nm 
впервые появился в версии 
.Fx 5.0 .
.Sh АВТОРЫ
.An -nosplit
The
.Nm 
драйвер устройства был написан Яном-Саймоном Пендри для 
.Bx 4.4 
и 
.Масанори ОЗАВА, Aq Mt ozawa@ongs.co.jp 
переопределено управление блокировкой для 
.Fx 7.0 .
Страница руководства написана
.An Гордоном Берглингом, Aq Mt gbe@FreeBSD.org .
.ИСПРАВЛЕНЫ ОШИБКИ
Пожалуйста, ознакомьтесь со списком ошибок, касающихся файловой системы 
.Xr mount_unionfs 8 
на странице руководства для получения списка ошибок, касающихся файловой системы 
.Nm 
.
