.\"-
.\" Авторское право (c) 1990, 1993
.\"	Регенты Калифорнийского университета. Все права защищены.
.\"
.\" Этот код создан на основе программного обеспечения, предоставленного
.\" Институтом инженеров электротехники и электроники, Inc.
.\"
.\" Распространение и использование в исходной и двоичной формах, с изменениями или без них,
.\" разрешены при соблюдении следующих условий:
.\" 1. Распространения исходного кода должны сохранять вышеуказанное уведомление об авторском
.\"    праве, этот список условий и следующий отказ от ответственности.
.\" 2. Распространения в двоичной форме должны воспроизводить вышеуказанное уведомление об авторском
.\"    праве, этот список условий и следующий отказ от ответственности в документации
.\"    и/или других материалах, предоставляемых с распространением.
.\" 3. Название университета и имена его участников не могут использоваться для поддержки или
.\"    продвижения продуктов, созданных на основе этого программного обеспечения, без
.\"    предварительного письменного разрешения.
.\"
.\" ДАННОЕ ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЕНО РЕГЕНТАМИ И УЧАСТНИКАМИ «КАК ЕСТЬ», И
.\" ЛЮБЫЕ ПРЯМЫЕ ИЛИ КОСВЕННЫЕ ГАРАНТИИ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ,
.\" ГАРАНТИЯМИ ТОВАРНОЙ ПРИГОДНОСТИ И СООТВЕТСТВИЯ КОНКРЕТНОЙ ЦЕЛИ,
.\" ОТКАЗЫВАЮТСЯ. В НИКАКОМ СЛУЧАЕ РЕГЕНТЫ ИЛИ УЧАСТНИКИ НЕ НЕСУТ ОТВЕТСТВЕННОСТИ
.\" ЗА ЛЮБЫЕ ПРЯМЫЕ, КОСВЕННЫЕ, СЛУЧАЙНЫЕ, СПЕЦИАЛЬНЫЕ, ПОКАЗАТЕЛЬНЫЕ ИЛИ ПОСЛЕДУЮЩИЕ
.\" УЩЕРБЫ (ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ, ПРИОБРЕТЕНИЕМ ЗАМЕЩАЮЩИХ ТОВАРОВ
.\" ИЛИ УСЛУГ; УТРАТОЙ ПРАВА ПОЛЬЗОВАНИЯ, ДАННЫХ ИЛИ ПРИБЫЛИ; ЛИБО ПРЕРЫВАНИЕМ ДЕЯТЕЛЬНОСТИ)
.\" НЕЗАВИСИМО ОТ ТОГО, НА КАКОЙ ТЕОРИИ ОТВЕТСТВЕННОСТИ, ДОГОВОРНОЙ, СТРОГОЙ
.\" ОТВЕТСТВЕННОСТИ ИЛИ ДЕЛИКТНОЙ (ВКЛЮЧАЯ НЕБРЕЖНОСТЬ ИЛИ ИНОЕ)
.\" ОСНОВЫВАЕТСЯ ЛИСПОЛЬЗОВАНИЕ ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ, ДАЖЕ ЕСЛИ БЫЛО СООБЩЕНО О
.\" ВОЗМОЖНОСТИ ТАКОГО УЩЕРБА.
.\"
.\"	@(#)echo.1	8.1 (Беркли) 7/22/93
.\"
.Dd 5 октября 2016
.Dt ECHO 1
.Os
.Sh НАЗВАНИЕ
.Nm echo
.Nd запись аргументов в стандартный вывод
.Sh СИНТАКСИС
.Nm
.Op Fl n
.Op Ar string ...
.Sh ОПИСАНИЕ
Утилита
.Nm
записывает любые указанные операнды, разделенные одним пробелом
.Pq Ql "\ "
и заканчивающиеся символом новой строки
.Pq Ql \en
в стандартный вывод.
.Pp
Доступен следующий параметр:
.Bl -tag -width flag
.It Fl n
Не выводить завершающий символ новой строки.
.El
.Pp
Маркер конца параметров
.Fl Fl
не распознается и записывается буквально.
.Pp
Символ новой строки также может быть опущен путем добавления
.Ql \ec
в конец строки, как это делается
в системах, совместимых с iBCS2.
Обратите внимание, что
параметр
.Fl n
и эффект
.Ql \ec
определены реализацией в
.St -p1003.1-2001
с поправкой Cor.\& 1-2002.
Для переносимости
.Nm
следует использовать только в случае, если первый аргумент не начинается с дефиса
.Pq Ql "-"
и не содержит обратных слешей
.Pq Ql "\e" .
Если этого недостаточно,
.Xr printf 1
следует использовать.
.Pp
Большинство оболочек предоставляют встроенную команду
.Nm ,
которая, как правило, отличается от этой утилиты
в обращении с опциями и обратными слешами.
См. руководство по встроенным командам
.Xr builtin 1 .
.Sh КОД ЗАВЕРШЕНИЯ
.Pp
Приложение завершается с кодом 0 в случае успеха, и с кодом >0, если произошла ошибка.
.Sh СМ. ТАКЖЕ
.Xr builtin 1 ,
.Xr csh 1 ,
.Xr printf 1 ,
.Xr sh 1
.Sh СТАНДАРТЫ
Утилита
.Nm
соответствует
.St -p1003.1-2001
с поправкой Cor.\& 1-2002.
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.At v2 .
