.\" Copyright (c) 2001, 2002 Чак Руйяр
.\"Все права защищены.
.\"
.\" Распространение и использование в исходном коде и двоичной форме, с использованием или без использования
.\" модификаций, если следующие условия
.\" соблюдаются:
.\" 1. При распространении исходного кода должно сохраняться вышеуказанное уведомление
.\"    об авторских правах, этот список условий и следующий дисклеймер.
.\" 2. При распространиении в двоичной форме должно воспроизводиться уведомление об авторских правах,
.\"    этот список условий и следующий ниже отказ от ответственности в
.\"    документации и/или других материалах, поставляемых с дистрибутивом.
.\" 3. Ни название университета, ни имена его участников не могут быть использованы для
.\"    поддержки или продвижения продуктов, созданных на основе данного программного обеспечения,
.\"    без специального предварительного письменного согласия.
.\"
.\" ДАННОЕ ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЯЕТСЯ ПРАВООБЛАДАТЕЛЯМИ И СОАВТОРАМИ ``КАК ЕСТЬ'', И 
.\" МЫ ОТКАЗЫВАЕМСЯ ОТ ЛЮБЫХ ПОДРАЗУМЕВАЕМЫХ ОБЯЗАТЕЛЬСТВ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ, 
.\" ПОДРАЗУМЕВАЕМЫЕ ГАРАНТИИ ТОВАРНОЙ ПРИГОДНОСТИ И НЕПРИГОДНОСТИ ДЛЯ ОПРЕДЕЛЕННОЙ
.\" ЦЕЛИ. НИ В КОЕМ СЛУЧАЕ ПРАВООБЛАДАТЕЛИ ИЛИ СОВАТОРЫ НЕ НЕСУТ ОТВЕТСТВЕННОСТИ
.\" ЗА ЛЮБЫЕ ПРЯМЫЕ, КОСВЕННЫЕ, СЛУЧАЙНЫЕ, ОСОБЫЕ, ПОКАЗАТЕЛЬНЫЕ ИЛИ ЛОГИЧЕСКИ ВЫТЕКАЮЩИЕ
.\" УБЫТКИ (ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ ИМИ, ПРИОБРЕТЕНИЕ ЗАМЕНЯЮЩИХ ТОВАРОВ ИЛИ УСЛУГ;
.\" ПОТЕРЮ ВОЗМОЖНОСТИ ИСПОЛЬЗОВАНИЯ, ДАННЫХ ИЛИ ПРИБЫЛИ; ИЛИ ПРЕКРАЩЕНИЕ ДЕЯТЕЛЬНОСТИ)
.\" НЕЗАВИСИМО ОТ ПРИЧИНЕННОГО УЩЕРБА И НА ОСНОВАНИИ ЛЮБОЙ ТЕОРИИ ОТВЕТСТВЕННОСТИ, БУДЬ ТО В РАМКАХ КОНТРАКТА, 
.\" ПРЯМОЙ ОТВЕТСТВЕННОСТИ ИЛИ ДЕЛИКТА (ВКЛЮЧАЯ ХАЛАТНОСТЬ ИЛИ ИНОЕ), ВОЗНИКШЕГО КАКИМ-ЛИБО ОБРАЗОМ
.\" В РЕЗУЛЬТАТЕ ИСПОЛЬЗОВАНИЯ ДАННОГО ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ, ДАЖЕ ЕСЛИ ВЫ БЫЛИ ОСВЕДОМЛЕНЫ О ВОЗМОЖНОСТИ
.\" ТАКОГО УЩЕРБА.
.\"
.Dd 1 мая, 2010 год
.Dt PATHCHK 1
.Os
.Sh НАЗВАНИЕ
.Nm pathchk
.Nd check pathnames
.Sh СИНТАКСИС
.Nm
.Op Fl pP
.Ar назваие патча ...
.Sh ОПИСАНИЕ
Утилита
.Nm
утилита проверяет, является ли каждый из указанных
аргументов
.Ar название патча
допустимым или переносимым.
.Pp
Диагностическое сообщение записывается для каждого аргумента , который:
.Bl -bullet
.It
Длиннее, чем
.Dv PATH_MAX
байт.
.It
Содержит любой компонент длиной более
.Dv NAME_MAX
байт.
(Значение
.Dv NAME_MAX
зависит от базовой файловой системы.)
.It
Содержит компонент директории, которая недоступна для поиска.
.El
.Pp
Это не считается ошибкой, если аргумент
.Ar название патча
содержит несуществующий компонент до тех пор, пока может быть создан компонент с таким
именем.
.Pp
Поддерживаемые опции:
.Bl -tag -width indent
.It Fl p
Выполните проверку переносимости указанных
.Ar название патча
аргументов.
Выполните проверку переносимости указанного
.Bl -bullet
.It
Длиннее, чем
.Dv _POSIX_PATH_MAX
.Pq 255
байт.
.It
Содержит компонент длиной более
.Dv _POSIX_NAME_MAX
.Pq 14
байт.
.It
Contains any character not in the portable filename character set (that is,
alphanumeric characters,
Содержит любые символы, не входящие в набор символов переносимого имени файла (то есть
буквенно-цифровые символы,
.Ql \&. ,
.Ql \&-
и
.Ql _ ) .
Ни один компонент не может начинаться с символа
.Pq Ql \&-
дефиса.
.El
.It Fl P
В дополнение к проверке по умолчанию или
.Fl p
напишите диагностику для каждого аргумента, который:
.Bl -bullet
.It
Пуст.
.It
Содержит компонент, который начинается с дефиса.
.El
.El
.Sh СТАТУС ЗАВЕРШЕНИЯ
.Ex -std
.Sh ПРИМЕРЫ
Проверьте, являются ли имена файлов в текущей директории переносимыми в
другие
.Tn POSIX
системы:
.Pp
.Dl "find . -exec pathchk -p -- {} +"
.Sh SEE ALSO
.Xr getconf 1 ,
.Xr pathconf 2 ,
.Xr stat 2
.Sh СТАНДАРТЫ
Утилита
.Nm
соответствует требованиям
.St -p1003.1-2001 .
.Sh ИСТОРИЯ
Утилита
.Nm
появилась в
.Fx 5.0 .
