.\"
.\" Copyright (c) 2004 Пол Армстронг
.\" Copyright (c) 2009 Thomas Abthorpe
.\"
.\" Все права защищены.
.\"
.\" Распространение и использование в исходных и двоичных формах, с или без
.\" модификации, разрешены при соблюдении следующих условий
.\" соблюдены:
.\" 1. Перераспределение исходного кода должно сохранять вышеуказанное уведомление об авторских правах
.\" уведомление об авторских правах, этот список условий и следующий отказ от ответственности.
.\" 2. Перераспределение в двоичной форме должно воспроизводить вышеуказанное уведомление об авторских правах
.\" уведомление об авторских правах, этот список условий и следующий отказ от ответственности в
.\" документации и/или других материалах, поставляемых вместе с дистрибутивом.
.\"
.\" ДАННОЕ ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЯЕТСЯ РАЗРАБОТЧИКАМИ ``КАК ЕСТЬ`` И ЛЮБЫЕ ЯВНЫЕ ИЛИ
.\" ПОДРАЗУМЕВАЕМЫХ ГАРАНТИЙ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ, ПОДРАЗУМЕВАЕМЫМИ ГАРАНТИЯМИ
.\" ТОВАРНОГО СОСТОЯНИЯ И ПРИГОДНОСТИ ДЛЯ КОНКРЕТНОЙ ЦЕЛИ, НЕ ПРИНИМАЮТСЯ.
.\" НИ ПРИ КАКИХ ОБСТОЯТЕЛЬСТВАХ РАЗРАБОТЧИКИ НЕ НЕСУТ ОТВЕТСТВЕННОСТИ ЗА ЛЮБЫЕ ПРЯМЫЕ, КОСВЕННЫЕ,
.\" СЛУЧАЙНЫЕ, СПЕЦИАЛЬНЫЕ, ОБРАЗЦОВЫЕ ИЛИ КОСВЕННЫЕ УБЫТКИ (ВКЛЮЧАЯ, НО
.\" НЕ ОГРАНИЧИВАЯСЬ, ПРИОБРЕТЕНИЕ ТОВАРОВ ИЛИ УСЛУГ, ЗАМЕНЯЮЩИХ ИХ; ПОТЕРЮ ИСПОЛЬЗОВАНИЯ,
.\" ДАННЫХ ИЛИ ПРИБЫЛИ; ИЛИ ПЕРЕРЫВА В РАБОТЕ), КАКИМИ БЫ ПРИЧИНАМИ ОНИ НИ БЫЛИ ВЫЗВАНЫ И ПО ЛЮБОМУ
.\" ТЕОРИИ ОТВЕТСТВЕННОСТИ, БУДЬ ТО ДОГОВОР, СТРОГАЯ ОТВЕТСТВЕННОСТЬ ИЛИ ПРАВОНАРУШЕНИЕ
.\" (ВКЛЮЧАЯ НЕБРЕЖНОСТЬ ИЛИ ИНОЕ), ВОЗНИКАЮЩИХ В РЕЗУЛЬТАТЕ ИСПОЛЬЗОВАНИЯ
.\" ДАННОГО ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ, ДАЖЕ ЕСЛИ ВЫ БЫЛИ ПРЕДУПРЕЖДЕНЫ О ВОЗМОЖНОСТИ ТАКОГО УЩЕРБА.
.\"
.Dd 14 октября 2012 г.
.Dt PORTINDEX 5
.Os
.Sh ИМЯ
.Nm ИНДЕКС
.Nd "Файл, содержащий информацию о состоянии дерева портов"
.Sh ОПИСАНИЕ
Файл индекса портов в
.Pa /usr/ports
содержит различные биты информации о дереве портов.
Каждая основная ветвь
.Fx
есть отдельный индексный файл, названный
.Dq INDEX- Ns Ar N ,
где
.Ar N
это номер основной версии
.Fx
ветви, т.е:
.Pa INDEX-7 ,
или
.Pa INDEX-8 .
.Bl -tag -width XXXXXXXXXXXX
.It Cm \&name
Имя пакета.
.It Cm \&path
Путь к директории порта.
.It Cm \&install prefix
Префикс установки по умолчанию.
.It Cm \&short description
Краткое описание.
.It Cm \&полное описание
Путь к полному описанию.
.It Cm \&maintainer email
Адрес электронной почты сопровождающего.
.It Cm \&index
Категории, в которые входит этот порт.
.It Cm \&build dependencies
Порты, которые должны быть установлены перед сборкой этого порта.
.It Cm \&run dependencies
Порты, которые должны быть установлены для запуска этого порта.
.It Cm \&website
Веб-сайт проекта для данного порта.
.It Cm \&e-deps
Порты, которые могут потребоваться для извлечения этого порта.
.It Cm \&p-deps
Порты, которые могут потребоваться для исправления этого порта.
.It Cm \&f-deps
Порты, которые могут потребоваться для извлечения этого порта.
.El
.Sh ФАЙЛЫ
.Bl -tag -width /usr/ports/INDEX-8XX
.It Pa /usr/ports/INDEX- Ns Ar N
где
.Ar N
это номер основной версии
.Fx
ветви.
.El
.Sh ПРИМЕРЫ
.Bd -literal
vim-6.3.15|/usr/ports/editors/vim|/usr/local|Vi "workalike", с множеством дополнительных возможностей|/usr/ports/editors/vim/pkg-descr|obrien@FreeBSD.org|editors|libiconv-1.9.2_1|libiconv-1.9.2_1|http://www.vim.org/|||||
.Ed
.Sh СМОТРИТЕ ТАКЖЕ 
.Xr сборка 7 ,
.Xr порты 7
.Sh АВТОРЫ
.An -nosplit
Эта страница руководства была написана
.An Пол Армстронг
и
.An Thomas Abthorpe Aq Mt tabthorpe@FreeBSD.org .


