.\" Copyright (c) 2019 The FreeBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" Эта документация была написана 
.\" Константином Белоусовым <kib@FreeBSD.org> при спонсорской поддержке
.\" FreeBSD Foundation.
.\"
.\" Распространение и использование в исходном коде и двоичной форме, с использованием или без использования
.\" модификаций, если следующие условия
.\" соблюдаются:
.\" 1. При распространении исходного кода должно сохраняться вышеуказанное уведомление
.\"    об авторских правах, этот список условий и следующий дисклеймер.
.\" 2. При распространиении в двоичной форме должно воспроизводиться уведомление об авторских правах,
.\"    этот список условий и следующий ниже отказ от ответственности в
.\"    документации и/или других материалах, поставляемых с дистрибутивом.
.\"
.\" ДАННОЕ ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЯЕТСЯ ПРАВООБЛАДАТЕЛЯМИ И СОАВТОРАМИ ``КАК ЕСТЬ'', И 
.\" МЫ ОТКАЗЫВАЕМСЯ ОТ ЛЮБЫХ ПОДРАЗУМЕВАЕМЫХ ОБЯЗАТЕЛЬСТВ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ, 
.\" ПОДРАЗУМЕВАЕМЫЕ ГАРАНТИИ ТОВАРНОЙ ПРИГОДНОСТИ И НЕПРИГОДНОСТИ ДЛЯ ОПРЕДЕЛЕННОЙ
.\" ЦЕЛИ. НИ В КОЕМ СЛУЧАЕ ПРАВООБЛАДАТЕЛИ ИЛИ СОВАТОРЫ НЕ НЕСУТ ОТВЕТСТВЕННОСТИ
.\" ЗА ЛЮБЫЕ ПРЯМЫЕ, КОСВЕННЫЕ, СЛУЧАЙНЫЕ, ОСОБЫЕ, ПОКАЗАТЕЛЬНЫЕ ИЛИ ЛОГИЧЕСКИ ВЫТЕКАЮЩИЕ
.\" УБЫТКИ (ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ ИМИ, ПРИОБРЕТЕНИЕ ЗАМЕНЯЮЩИХ ТОВАРОВ ИЛИ УСЛУГ;
.\" ПОТЕРЮ ВОЗМОЖНОСТИ ИСПОЛЬЗОВАНИЯ, ДАННЫХ ИЛИ ПРИБЫЛИ; ИЛИ ПРЕКРАЩЕНИЕ ДЕЯТЕЛЬНОСТИ)
.\" НЕЗАВИСИМО ОТ ПРИЧИНЕННОГО УЩЕРБА И НА ОСНОВАНИИ ЛЮБОЙ ТЕОРИИ ОТВЕТСТВЕННОСТИ, БУДЬ ТО В РАМКАХ КОНТРАКТА, 
.\" ПРЯМОЙ ОТВЕТСТВЕННОСТИ ИЛИ ДЕЛИКТА (ВКЛЮЧАЯ ХАЛАТНОСТЬ ИЛИ ИНОЕ), ВОЗНИКШЕГО КАКИМ-ЛИБО ОБРАЗОМ
.\" В РЕЗУЛЬТАТЕ ИСПОЛЬЗОВАНИЯ ДАННОГО ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ, ДАЖЕ ЕСЛИ ВЫ БЫЛИ ОСВЕДОМЛЕНЫ О ВОЗМОЖНОСТИ
.\" ТАКОГО УЩЕРБА.
.\"
.Dd 5 октября, 2023 год
.Dt PROCCONTROL 1
.Os
.Sh НАЗВАНИЕ
.Nm proccontrol
.Nd Control some process execution aspects
.Sh СИНТАКСИС
.Nm
.Fl m Ar режим
.Op Fl s Ar контроль
.Op Fl q
.Fl p Ar идентификатор_процесса | команда
.Sh ОПИСАНИЕ
Команда
.Nm
изменяет параметр выполнения существующего процесса,
указанного аргументом
.Ar идентификатор_процесса ,
или запускает выполнение новой программы
.Ar команда
с установленным для неё параметром выполнения.
.Pp
Какой параметр выполнения изменяется, определяется обязательным
параметром
.Ar режим .
Возможные значения для
.Ar режим
следующие:
.Bl -tag -width trapcap
.It Ar aslr
Управление рандомизацией расположения адресного пространства.
Применимо только к вновь созданному процессу.
.It Ar trace
Управление разрешением на подключение отладчиков.
Обратите внимание, что процесс может разрешить трассировку только для себя,
а не для любого другого процесса.
.It Ar trapcap
Управляет сигнализацией о нарушениях режима работы с возможностями.
.It Ar protmax
Управляет неявным применением приложения PROT_MAX для
.Xr mmap 2 .
.It Ar nonewprivs
Управляет отключением битов setuid и sgid для
.Xr execve 2 .
.It Ar wxmap
Управляет режимом исключительной записи при выполнении отображений.
.It Ar kpti
Управляет включением KPTI, только для AMD64.
.It Ar la48
Контролирует ограничение адресного пространства процесса в пользовательском режиме до 48 бит адреса,
только для AMD64, на машинах, способных к 57-битной адресации.
.El
.Pp
Аргумент
.Ar контроль
указывает, должен ли выбранный
.Ar режим
быть включен или отключен.
Возможные значения:
.Ar enable
и
.Ar disable ,
при этом значение по умолчанию -
.Ar enable ,
если не указано.
Смотрите
.Xr procctl 2
для детального описания эффектов каждого режима и взаимодействия с другими
средствами управления процессами.
.Pp
Переключатель
.Fl q
заставляет утилиту запрашивать и печатать текущую настройку для
выбранного режима.
Опция
.Fl q
требует указания процесса-цели запроса с помощью
.Fl p .
.Sh СТАТУС ЗАВЕРШЕНИЯ
.Ex -std
.Sh ПРИМЕРЫ
.Bl -bullet
.It
Чтобы отключить возможность подключения отладчиков к процессу 1020, выполните
.Dl "proccontrol -m trace -s disable -p 1020"
.It
Чтобы выполнить программу
.Xr uniq 1
в режиме, при котором нарушения доступа к возможностям вызывают
.Dv SIGTRAP
доставку, сделайте
.Dl "proccontrol -m trapcap uniq"
.It
Чтобы запросить текущий режим включения ASLR для запущенного
процесса 1020, сделайте
.Dl "proccontrol -m aslr -q -p 1020"
.El
.Sh СМОТРИТЕ ТАКЖЕ
.Xr kill 2 ,
.Xr procctl 2 ,
.Xr ptrace 2 ,
.Xr mitigations 7
.Sh ИСТОРИЯ
Команда
.Nm
появилась в
.Fx 10.0 .
.Sh АВТОРЫ
Команда
.Nm
и эта страница мануала были написаны
.An Konstantin Belousov Aq Mt kib@freebsd.org
при спонсорской поддержке FreeBSD Foundation.
