.\" Авторское право (c) 1983, 1991, 1993
.\"	Регенты Калифорнийского университета.  Все права защищены.
.\"
.\" Распространение и использование в исходных и двоичных формах, с модификацией или без
.\" модификацией, разрешается при соблюдении следующих условий
.\" соблюдены:
.\" 1. Перераспределение исходного кода должно сохранять вышеуказанное уведомление об авторских правах
.\" уведомление об авторских правах, этот список условий и следующий отказ от ответственности.
.\" 2. Перераспределение в двоичной форме должно воспроизводить вышеуказанное уведомление об авторских правах
.\" уведомление об авторских правах, этот список условий и следующий отказ от ответственности в
.\" документации и/или других материалах, поставляемых вместе с дистрибутивом.
.\" 3. Ни название Университета, ни имена его соавторов
.\" не могут быть использованы для поддержки или продвижения продуктов, созданных на основе этого программного обеспечения
.\" без специального предварительного письменного разрешения.
.\"
.\" ДАННОЕ ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЯЕТСЯ РЕГЕНТАМИ И РАЗРАБОТЧИКАМИ "КАК ЕСТЬ" И
.\" ЛЮБЫЕ ЯВНЫЕ ИЛИ ПОДРАЗУМЕВАЕМЫЕ ГАРАНТИИ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ
.\" ПОДРАЗУМЕВАЕМЫЕ ГАРАНТИИ ТОВАРНОГО СОСТОЯНИЯ И ПРИГОДНОСТИ ДЛЯ КОНКРЕТНОЙ ЦЕЛИ
.\" НЕ ПРИНИМАЮТСЯ.  НИ ПРИ КАКИХ ОБСТОЯТЕЛЬСТВАХ РЕГЕНТЫ ИЛИ ВКЛАДЧИКИ НЕ НЕСУТ ОТВЕТСТВЕННОСТИ
.\" ЗА ЛЮБЫЕ ПРЯМЫЕ, КОСВЕННЫЕ, СЛУЧАЙНЫЕ, СПЕЦИАЛЬНЫЕ, ПРИМЕРНЫЕ ИЛИ КОСВЕННЫЕ УБЫТКИ.
.\" УЩЕРБ (ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ, ПРИОБРЕТЕНИЕ ТОВАРОВ-ЗАМЕНИТЕЛЕЙ
.\" ИЛИ УСЛУГИ; ПОТЕРЮ ИСПОЛЬЗОВАНИЯ, ДАННЫХ ИЛИ ПРИБЫЛИ; ИЛИ ПЕРЕРЫВ В РАБОТЕ)
.\" НЕЗАВИСИМО ОТ ПРИЧИН И ЛЮБОЙ ТЕОРИИ ОТВЕТСТВЕННОСТИ, БУДЬ ТО КОНТРАКТ, СТРОГИЙ
.\" ОТВЕТСТВЕННОСТИ, ИЛИ ДЕЛИКТА (ВКЛЮЧАЯ ХАЛАТНОСТЬ ИЛИ ИНОЕ), ВОЗНИКАЮЩИХ КАКИМ-ЛИБО ОБРАЗОМ
.\" В СВЯЗИ С ИСПОЛЬЗОВАНИЕМ ДАННОГО ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ, ДАЖЕ ЕСЛИ ВЫ БЫЛИ ПРЕДУПРЕЖДЕНЫ О ВОЗМОЖНОСТИ
.\" ТАКОГО УЩЕРБА.
.\"
.\"     @(#)protocols.5 8.1 (Berkeley) 6/5/93
.\"
.Dd 7 декабря 2020 г.
.Dt PROTOCOLS 5
.Os
.Sh ИМЯ
.Nm протоколы
База данных имен протоколов .Nd
.Sh ОПИСАНИЕ
Сайт
.Nm
содержит информацию о присвоенных номерах протоколов
используемых в протоколах IPv4 и IPv6 для идентификации протокола следующего уровня.
Для каждого протокола должна присутствовать одна строка
со следующей информацией:
.Bd -незаполненный -отступ
официальное имя протокола
номер протокола
псевдонимы
.Ed
.Pp
Элементы разделяются любым количеством пробелов и/или
символами табуляции.
Символ ``#'' указывает на начало
комментария; символы до конца строки
не интерпретируются программами поиска в файле.
.Pp
Имена протоколов могут содержать любой печатаемый
любой печатный символ, кроме разделителя полей, новой строки,
или символа комментария.
.Sh ФАЙЛЫ
.Bl -tag -width /etc/protocols -compact
.It Pa /etc/protocols
The
.Nm
находится в
.Pa /etc .
.El
.Sh СМОТРИТЕ ТАКЖЕ
.Xr getprotoent 3
.Rs
.%R RFC 2780
.%D Март 2000 г.
.%T "IANA Allocation Guidelines For Values In the \
Интернет-протокола и связанных с ним заголовков"
.Re
.Rs
.%R RFC 5237
.%D Февраль 2008 г.
.%T "Руководство по распределению IANA для поля протокола"
.Re
.Sh ИСТОРИЯ
Сайт
.Nm
появился в
.Bx 4.2 ,
в котором описывались "известные протоколы, используемые в Интернете DARPA".
Недостатки .Sh
Вместо статического файла следует использовать сервер имен.


