.\" Copyright (c) 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)hier.7	8.1 (Berkeley) 6/5/93
.\"
.Dd July 6, 2023
.Dt HIER 7
.Os
.Sh НАИМЕНОВАНИЕ
.Nm hier
.Nd расположение файловых систем
.Sh СИНТАКСИС
Обзор иерархии файловой системы.
.Sh ОПИСАНИЕ 
.Bl -tag -width "/libexec/"
.It Pa /
корневой каталог
.It Pa /bin/
пользовательские утилиты, которые являются основополагающими для однопользовательского и многопользовательского режимов
.It Pa /boot/
программы и конфигурационные файлы, используемые при загрузке операционной системы
.Pp
.Bl -tag -width "nvmecontrol/" -compact
.It Pa defaults/
файлы конфигурации загрузочного устройства по умолчанию; смотрите
.Xr loader.conf 5
.It Pa dtb/
скомпилированные файлы сплющенного дерева устройств (FDT); смотрите
.Xr fdt 4
и
.Xr dtc 1
.Pp
.Bl -tag -width "overlays/" -compact
.It Pa overlays/
скомпилированные наложения сплющенного дерева устройств (FDT); их можно применить с помощью
.Va fdt_overlays
установив в
.Xr loader.conf 5
.El
.Pp
.It Pa efi/
точка монтирования системного раздела EFI (ESP) в системах UEFI
.It Pa firmware/
загружаемые модули ядра, содержащие двоичную микропрограмму, для оборудования, на которое
прошивка должна быть загружена
.It Pa kernel/
чистый исполняемый файл ядра (операционная система, загружаемая в память при загрузке)
и модули ядра
.It Pa modules/
загружаемые сторонние модули ядра, например, связанные с
.Xr ports 7
.It Pa zfs/
файлы кэша пула
.Xr zfs 8
.El
.It Pa /compat/
файлы, поддерживающие двоичную совместимость с другими операционными системами
.Pp
.Bl -tag -width "nvmecontrol/" -compact
.It Pa linux/
расположение по умолчанию для совместимости с
.Xr linux 4
во время выполнения
.El
.Pp
.It Pa /dev/
обычная точка монтирования для
.Xr devfs 5
.Pp
.Bl -tag -width "nvmecontrol/" -compact
.It Pa fd/
файлы дескрипторов файлов; смотрите
.Xr fd 4
.El
.It Pa /etc/
файлы конфигурации системы и скрипты
.Pp
.Bl -tag -width "nvmecontrol/" -compact
.It Pa bluetooth/
конфигурационные файлы bluetooth
.It Pa defaults/
файлы конфигурации системы по умолчанию; смотрите
.Xr rc 8
.It Pa localtime
информация о местном часовом поясе; смотрите
.Xr ctime 3
.It Pa mail/
файлы управления
.Xr sendmail 8
.It Pa mtree/
конфигурационные файлы
.Xr mtree 8
.It Pa pam.d/
конфигурационные файлы для библиотеки Pluggable Authentication Modules (PAM); смотрите
.Xr pam 3
.It Pa periodic/
сценарии, которые выполняются ежедневно, еженедельно или ежемесячно с помощью
.Xr cron 8 ;
смотрите
.Xr periodic 8
.It Pa ppp/
файлы конфигурации PPP; смотрите
.Xr ppp 8
.It Pa rc.d/
система и сценарии запуска/контроля демонов; смотрите
.Xr rc 8
.It Pa security/
Файлы конфигурации аудита OpenBSM; смотрите
.Xr audit 8
.It Pa ssh/
Конфигурационные файлы OpenSSH; смотрите
.Xr ssh 1
.It Pa ssl/
Файлы конфигурации OpenSSL
.El
.It Pa /home/
домашние каталоги пользователей; хотя их расположение не стандартизировано, типичный домашний каталог для интерактивного пользователя
.Dv beastie
был бы
.Pa /home/beastie/
.It Pa /lib/
системные библиотеки, критически важные для двоичных файлов в
.Pa /bin
и
.Pa /sbin
.Pp
.Bl -tag -width "nvmecontrol/" -compact
.It Pa casper/
конкретные услуги
.Xr libcasper 3
Библиотеки поддержки Capsicum
.It Pa geom/
библиотеки, предназначенные для конкретных классов утилиты
.Xr geom 8
.It Pa nvmecontrol/
специфические библиотеки для расширения утилиты
.Xr nvmecontrol 8
.El
.It Pa /libexec/
системные утилиты, критически важные для двоичных файлов в
.Pa /bin
и
.Pa /sbin
.It Pa /media/
пустой каталог, обычно содержащий точки монтирования для съемных носителей, таких как
USB-накопители, компакт-диски и DVD-диски
.It Pa /mnt/
пустой каталог, обычно используемый администраторами системы в качестве временной точки монтирования
точка
.It Pa /net/
автоматизированные общие ресурсы NFS; смотрите
.Xr auto_master 5
.It Pa /nonexistent/
несуществующий каталог; обычно домашний каталог для специальных учетных записей пользователей.
учетных записей, которым не требуется домашний каталог. смотрите также
.Pa /var/empty/
.It Pa /proc/
файловая система процессов; смотрите
.Xr procfs 5
.It Pa /rescue/
статически связанные программы для аварийного восстановления; смотрите
.Xr rescue 8
.It Pa /root/
домашний каталог корневого пользователя
.It Pa /sbin/
системные программы и утилиты администрирования, которые являются основополагающими для
однопользовательского и многопользовательского режимов
.It Pa /tmp/
временные файлы, которые могут быть удалены
.Xr rc 8 ;
смотрите переменную
.Va clear_tmp_enable
в
.Xr rc.conf 5
.It Pa /usr/
содержит большинство пользовательских утилит и приложений
.Pp
.Bl -tag -width "freebsd-dist/" -compact
.It Pa bin/
общие утилиты, инструменты программирования и приложения
.It Pa freebsd-dist/
файлы дистрибутива FreeBSD
.Pq например base.txz ; смотрите
.Xr release 7
и
.Xr bsdinstall 8
.It Pa include/
стандартные заголовочные файлы Си
.It Pa lib/
общие и архивные библиотеки
.Xr ar 1 Ns -type
.Pp
.Bl -tag -width Fl -compact
.It Pa compat/
общие библиотеки для совместимости
.It Pa debug/
автономные отладочные данные для ядра и базовых библиотек системы и двоичных файлов
.It Pa dtrace/
Скрипты библиотеки DTrace
.It Pa engines/
OpenSSL (набор инструментов для криптографии/SSL) динамически загружаемые движки
.El
.Pp
.It Pa libdata/
различные файлы данных утилиты
.Pp
.Bl -tag -width Fl -compact
.It Pa gcc/
Конфигурационные данные GCC
.It Pa ldscripts/
скрипты компоновки; смотрите
.Xr ld 1
.It Pa pkgconfig/
.Xr pc 5 Pq Pa ports/devel/pkgconf
файлы; коллекции флагов компилятора, флагов компоновщика и другой информации
относящаяся к использованию библиотеки
.El
.Pp
.It Pa libexec/
системные демоны и системные утилиты, которые выполняются другими программами
.Pp
.Bl -tag -width Fl -compact
.It Pa aout/
утилиты для работы с исполняемыми файлами a.out
.It Pa elf/
утилиты для работы с исполняемыми файлами ELF
.It Pa lpr/
коммунальные услуги и фильтры для системы печати LP; смотрите
.Xr lpr 1
.It Pa sendmail/
двоичные файлы
.Xr sendmail 8 ;
смотрите
.Xr mailwrapper 8
.It Pa sm.bin/
ограниченная оболочка для
.Xr sendmail 8 ;
смотрите
.Xr smrsh 8
.El
.Pp
.It Pa local/
локальных исполняемых файлов, библиотек и т.д.
Также используется в качестве места назначения по умолчанию для
.Xr ports 7
рамки.
В рамках следует использовать
.Pa local/ ,
общий план, разработанный
.Nm
для
.Pa /usr .
Исключением является документация по портам
.Po в
.Pa share/doc/<port>/ Ns Pc ,
и
.Pa /usr/local/etc
.Po mimics
.Pa /etc Ns Pc .
.It Pa obj/
дерево целей для конкретной архитектуры, созданное путем построения
.Fx
из исходных текстов; смотрите
.Xr build 7
.It Pa ports/
.Fx
коллекция портов; смотрите
.Xr ports 7
.It Pa sbin/
системные демоны и системные утилиты, которые выполняются пользователями
.It Pa share/
независимые от архитектуры файлы
.Pp
.Bl -tag -width Fl -compact
.It Pa calendar/
файлы календаря всей системы; смотрите
.Xr calendar 1
.It Pa dict/
списки слов; смотрите
.Xr look 1
.Pp
.Bl -tag -width Fl -compact
.It Pa freebsd
.Fx Ns -specific
термины, имена собственные и жаргон
.It Pa web2
слова из Второго Словаря Вебстера
.El
.Pp
.It Pa doc/
различная документация
.It Pa examples/
различные примеры для пользователей и программистов
.It Pa firmware/
образы микропрограмм, загружаемые пользовательскими программами
.It Pa games/
используется в различных играх
.It Pa keys/
известные доверенные и отозванные ключи
.Pp
.Bl -tag -width Fl -compact
.It Pa pkg/
отпечатки пальцев для
.Xr pkg 7
и
.Xr pkg 8
.El
.Pp
.It Pa locale/
файлы локализации; смотрите
.Xr setlocale 3
.It Pa man/
страницы руководства
.It Pa misc/
разные файлы системы
.Pp
.Bl -tag -width Fl -compact
.It Pa termcap
база данных характеристик терминалов; смотрите
.Xr termcap 5
.El
.Pp
.It Pa mk/
шаблоны для создания; смотрите
.Xr make 1
.It Pa nls/
файлы поддержки национальных языков
.It Pa security/
файлы данных для политик безопасности, таких как
.Xr mac_lomac 4
.It Pa sendmail/
конфигурационные файлы
.Xr sendmail 8
.It Pa skel/
пример
.Pa .\&
(тчк) файлы для новых учетных записей
.It Pa snmp/
MIBs, файлы примеров и определения деревьев для демона SNMP
.Pp
.Bl -tag -width Fl -compact
.It Pa defs/
файлы определения деревьев для использования с
.Xr gensnmptree 1
.It Pa mibs/
MIB файлы
.El
.Pp
.It Pa syscons/
файлы
.Xr syscons 4
.Pp
.Bl -tag -width Fl -compact
.It Pa fonts/
консольные шрифты; смотрите
.Xr vidcontrol 1
и
.Xr vidfont 1
.It Pa keymaps/
карты клавиатуры консоли; смотрите
.Xr kbdcontrol 1
и
.Xr kbdmap 1
.It Pa scrnmaps/
карты экрана консоли
.El
.Pp
.It Pa sysroot/
файлы, необходимые для аргумента -sysroot компилятора/линковщика для сборки неродных
двоичных файлов
.Pp
.Bl -tag -width Fl -compact
.It Pa VERSION/
файлы для выпуска ВЕРСИИ
.Fx .
По умолчанию,
.Dq VERSU
соответствует
.Xr uname 1
.Fl r .
.Pp
.Bl -tag -width Fl -compact
.It Pa MACHINE.MACHINE_ARCH/
представляют собой двоичный ABI для этих файлов.
.Dq МАШИНА
соответствует
.Xr uname 1
.Fl m .
.Dq MACHINE_ARCH
соответствует
.Xr uname 1
.Fl p .
.El
.El
.Pp
.It Pa tabset/
файлы описания вкладок для различных терминалов; используется в файле termcap;
смотрите
.Xr termcap 5
.It Pa vi/
поддержка локализации и утилиты для
.Xr vi 1
.It Pa vt/
файлы
.Xr vt 4
.Pp
.Bl -tag -width Fl -compact
.It Pa fonts/
консольные шрифты; смотрите
.Xr vidcontrol 1
и
.Xr vidfont 1
.It Pa keymaps/
карты клавиатуры консоли; смотрите
.Xr kbdcontrol 1
и
.Xr kbdmap 1
.\" .It Pa scrnmaps/
.\" карты экрана консоли
.El
.Pp
.It Pa zoneinfo/
информация о конфигурации часового пояса; смотрите
.Xr tzfile 5
.El
.Pp
.It Pa src/
.Fx
исходный код; смотрите
.Xr development 7 .
Расположение дерева исходников описывается верхним уровнем файла
.Pa README.md .
.Pp
.It Pa tests/
тестовый насбор
.Fx ;
смотрите
.Xr tests 7
.El
.It Pa /var/
журнальные, временные, переходные файлы и файлы очереди печати
.Pp
.Bl -tag -width "preserve/" -compact
.It Pa account/
файлы системного учета
.Pp
.Bl -tag -width Fl -compact
.It Pa acct
файл учета выполнения; смотрите
.Xr acct 5
.El
.Pp
.It Pa at/
файлы расписания с таймером; смотрите
.Xr at 1
.Pp
.Bl -tag -width Fl -compact
.It Pa jobs/
рабочие файлы
.It Pa spool/
выходные файлы очереди печати
.El
.Pp
.It Pa backups/
разные файлы резервного копирования
.It Pa cache/
разные файлы кэша
.Pp
.Bl -tag -width Fl -compact
.It Pa pkg/
кэшированные пакеты для
.Xr pkg 8
.El
.Pp
.It Pa crash/
каталог по умолчанию для дампов аварий ядра; смотрите
.Xr crash 8
и
.Xr savecore 8
.It Pa cron/
файлы
.Xr cron 8
.Pp
.Bl -tag -width Fl -compact
.It Pa tabs/
файлы
.Xr crontab 5
.El
.Pp
.It Pa db/
различные автоматически генерируемые файлы баз данных, специфичные для системы
.Pp
.Bl -tag -width "freebsd-update/" -compact
.It Pa freebsd-update/
временные файлы и загрузки для
.Xr freebsd-update 8
.El
.Pp
.It Pa empty/
для использования программами, которым требуется пустой каталог.
Используется, например, для разделения привилегий с помощью
.Xr sshd 8
.It Pa games/
разные состояния игры и файлы результатов
.It Pa heimdal/
Базы данных сервера Kerberos; смотрите
.Xr kdc 8
.It Pa log/
различные файлы журналов системы
.Pp
.Bl -tag -width "utx.lastlogin" -compact
.It Pa utx.lastlogin
журнал последнего входа в систему; смотрите
.Xr getutxent 3
.It Pa utx.log
журнал входа/выхода; смотрите
.Xr getutxent 3
.El
.Pp
.It Pa mail/
файлы пользовательских почтовых ящиков
.It Pa msgs/
база данных системных сообщений; смотрите
.Xr msgs 1
.It Pa preserve/
Не используется, присутствует по историческим причинам
.It Pa quotas/
файлы информации о квотах файловой системы
.It Pa run/
файлы, содержащие информацию об операционной системе с момента ее загрузки
.Pp
.Bl -tag -width Fl -compact
.It Pa bhyve/
виртуальные машины
.Xr bhyve 8
.Xr unix 4 Ns -domain sockets
.It Pa ppp/
доступный для записи группе
.Dq network
для сокетов с коммутируемыми соединениями; смотрите
.Xr ppp 8
.It Pa utx.active
база данных текущих пользователей; смотрите
.Xr getutxent 3
.El
.Pp
.It Pa rwho/
файлы данных rwho; смотрите
.Xr rwhod 8 ,
.Xr rwho 1 ,
и
.Xr ruptime 1
.It Pa spool/
различные справочники по принтерам и почтовым системам
.Pp
.Bl -tag -width "clientmqueue/" -compact
.It Pa clientmqueue/
Очередь не доставленных писем; смотрите
.Xr sendmail 8
.It Pa ftp/
Корневая директория ftp; смотрите
.Xr ftpd 8
.It Pa mqueue/
очередь недоставленных писем; смотрите
.Xr sendmail 8
.It Pa output/
каталоги очередей строчного принтера
.El
.Pp
.It Pa tmp/
временные файлы, которые не удаляются
.Xr rc 8
.Pp
.Bl -tag -width "vi.recover/" -compact
.It Pa vi.recover/
файлы восстановления
.Xr vi 1
.El
.Pp
.It Pa yp/
карты NIS; смотрите
.Xr yp 8
.El
.El
.Sh ПРИМЕЧАНИЯ
На этой странице руководства описаны стандартные расположения файловой системы
.Fx .
Фактическая иерархия в конкретной системе определяется
администратором.
Хорошо поддерживаемая установка будет включать в себя адаптированную версию
этого документа.
.Sh СМОТРИТЕ ТАКЖЕ
.Xr apropos 1 ,
.Xr find 1 ,
.Xr grep 1 ,
.Xr ls 1 ,
.Xr whereis 1 ,
.Xr which 1
.Sh ИСТОРИЯ
Страница руководства
.Nm
появилась в
.At v7 .
