.\" Copyright (c) 1987, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)hostname.7	8.2 (Berkeley) 12/30/93
.\"
.Dd December 25, 2013
.Dt HOSTNAME 7
.Os
.Sh ИМЯ
.Nm hostname
.Nd описание разрешения имени хоста
.Sh ОПИСАНИЕ
Имена хостов - это домены, где домен представляет собой иерархический
список поддоменов, разделенных точками; например, компьютер monet в поддомене Berkeley
поддомена EDU в Интернете будет представлен в виде
.Pp
.Dl monet.Berkeley.EDU
.Pp
(без завершающей точки).
.Pp
Имена хостов часто используются сетевыми клиентскими и серверными программами,
которые, как правило, должны преобразовать имя в адрес для использования.
(Эта функция обычно выполняется библиотечной программой
.Xr gethostbyname 3 . )
Имена хостов обрабатываются средством распознавания интернет-имен следующим
образом.
.Pp
Если имя состоит из одного компонента, т.е. не содержит точки,
и если переменная окружения
.Dq Ev HOSTALIASES
задается как имя файла,
в этом файле выполняется поиск любой строки, соответствующей введенному имени хоста.
Файл должен состоять из строк, состоящих из двух строк, разделенных пробелами,
первая из которых является псевдонимом имени хоста,
а вторая - полным именем хоста,
которое будет заменено на этот псевдоним.
Если между именем хоста, которое требуется разрешить,
и первым полем строки в файле обнаружено совпадение без учета регистра, выполняется поиск замененного имени
без дальнейшей обработки.
.Pp
Если входное имя заканчивается конечной точкой,
конечная точка удаляется,
а оставшееся имя просматривается без дальнейшей обработки.
.Pp
Если введенное имя не заканчивается точкой в конце, то выполняется поиск
по списку доменов до тех пор, пока не будет найдено совпадение.
Список поиска по умолчанию включает сначала локальный домен,
затем его родительские домены, содержащие как минимум 2 компонента имени (сначала самый длинный).
Например,
в домене CS.Berkeley.EDU имя lithium.CChem сначала будет проверяться
как lithium.CChem.CS.Berkeley.EDU, а затем как lithium.CChem.Berkeley.EDU.
Lithium.CChem.EDU не будет использоваться, так как
от локального домена остался только один компонент.
Путь поиска можно изменить по сравнению с заданным по умолчанию
с помощью общесистемного конфигурационного файла (смотрите
.Xr resolver 5 ) .
.Sh СМОТРИТЕ ТАКЖЕ
.Xr gethostbyname 3 ,
.Xr resolver 5
.Sh ИСТОРИЯ
.Nm Hostname
появился в
.Bx 4.2 .
