.\"-
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.\" Copyright (c) 2024 Alexander Ziaee <concussious@runbox.com>
.\"
.Dd April 17, 2024
.Dt "NETWORKING" 7
.Os
.Sh ИМЯ
.Nm networking ,
.Nm wifi
.Nd краткое руководство по подключению к сети
.Sh ОПИСАНИЕ
В следующих примерах предполагается, что мы подключаемся к Ethernet
с помощью первого интерфейса, найденного драйвером
.Xr em 4 ,
и Wi-Fi с первым интерфейсом, найденным драйвером
.Xr iwn 4 ,
хотя ваше аппаратное обеспечение будет отличаться.
.Sh ПРИМЕРЫ
.Bl -tag -width 0n
.It Sy Подключение к сети Ethernet с помощью DHCP:
.Bd -literal -offset 2n
.Ic # dhclient em0
.Ed
.It Sy Подключение к сотовой сети с помощью USB-модема:
.Pp
Загрузите драйвер подключения через USB,
.Xr urndis 4 :
.Bd -literal -offset 2n
.Ic # kldload urndis
.Ed
.Pp
Запросите аренду DHCP-сервера на интерфейсе подключения USB:
.Bd -literal -offset 2n
.Ic # dhclient ue0
.Ed
.It Sy Подключение к сети Wi-Fi:
.Pp
Определите свое оборудование Wi-Fi:
.Bd -literal -offset 2n
.Ic % sysctl net.wlan.devices
.Ed
.Pp
Настройте свое оборудование Wi-Fi в качестве интерфейса wlan0:
.Ed
.Bd -literal -offset 2n
.Ic # sysrc wlans_iwn0="wlan0"
.Ed
.Pp
Установите этот интерфейс для согласования аренды DHCP с
.Xr wpa_supplicant 8 :
.Bd -literal -offset 2n
.Ic # sysrc ifconfig_wlan0="WPA SYNCDHCP"
.Ed
.Pp
Введите данные о сети Wi-Fi:
.Bd -literal -offset 2n
.Ic # wpa_passphrase \(dqmyssid\(dq \(dqmypassphrase\(dq >> wpa_supplicant.conf
.Ed
.Pp
Перезапустите демон сетевого интерфейса:
.Bd -literal -offset 2n
.Ic # service netif restart
.Ed
.Pp
.It Sy Поиск сетей Wi-Fi:
.Bd -literal -offset 2n
.Ic % ifconfig wlan0 scan
.Ed
.It Sy Режим полета:
.Bd -literal -offset 2n
.Ic # service netif stop
.Ed
.El
.Sh СМОТРИТЕ ТАКЖЕ
.Xr bsdconfig 8 ,
.Xr dhclient 8 ,
.Xr ifconfig 8 ,
.Xr wpa_passphrase 8
.Pp
Глава о расширенных сетях в руководстве
.Fx .
.Sh ПРЕДУПРЕЖДЕНИЯ
Специальные символы оболочки в
.Ar SSID
или
.Ar passphrase
нужно будет экранировать для
.Xr wpa_passphrase 8 ,
обычно использующий
.Ql \e ,
более подробную информацию смотрите на странице руководства для вашей оболочки.
.Pp
В настоящий момент
.Ql Ic service netif restart
не перезапускает маршрутизацию.
Распространенным обходным путем вместо этого является выдача
.Ql Ic service netif restart && service routing restart .