.\" Авторские права (c) 2007, 2008 Марсель Муленар
.\" Все права защищены.
.\"
.\" Распространение и использование в исходных и бинарных формах, с изменениями или без,
.\" разрешено при условии соблюдения следующих условий:
.\" 1. Перераспределения исходного кода должны сохранять вышеуказанное уведомление об авторском праве,
.\"    этот список условий и следующее отказ от ответственности.
.\" 2. Перераспределения в бинарной форме должны воспроизводить вышеуказанное уведомление об авторском праве,
.\"    этот список условий и следующее отказ от ответственности в
.\"    документации и/или других материалах, поставляемых с распространением.
.\"
.\" ЭТО ПО ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЯЕТСЯ АВТОРАМИ И УЧАСТНИКАМИ "КАК ЕСТЬ" И
.\" ЛЮБЫЕ ЯВНЫЕ ИЛИ ПОДРАЗУМЕВАЕМЫЕ ГАРАНТИИ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ, ПОДРАЗУМЕВАЕМЫМИ ГАРАНТИЯМИ
.\" ТОВАРНОСТИ И ПРИГОДНОСТИ ДЛЯ КОНКРЕТНОЙ ЦЕЛИ ОТКАЗЫВАЮТСЯ. НИ В КОЕМ СЛУЧАЕ АВТОРЫ ИЛИ УЧАСТНИКИ НЕ НЕСУТ
.\" ОТВЕТСТВЕННОСТЬ ЗА ЛЮБОЙ ПРЯМОЙ, КОСВЕННЫЙ, СЛУЧАЙНЫЙ, ОСОБЫЙ, ПРИМЕРНЫЙ ИЛИ КОСВЕННЫЙ УЩЕРБ
.\" (ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ, ПО ЗАМЕЩЕНИЮ ТОВАРОВ ИЛИ УСЛУГ; ПОТЕРЮ ИСПОЛЬЗОВАНИЯ, ДАННЫХ ИЛИ ПРИБЫЛИ; ИЛИ ПРЕРЫВАНИЕ БИЗНЕСА)
.\" ТЕМ НЕ МЕНЕЕ ВЫЗВАННО И НА ЛЮБОЙ ТЕОРИИ ОТВЕТСТВЕННОСТИ, БУДЬ ТО В КОНТРАКТЕ, СТРОГОЙ ОТВЕТСТВЕННОСТИ,
.\" ИЛИ ДЕЛИКТ (ВКЛЮЧАЯ ХАЛАТНОСТЬ ИЛИ ИНАЧЕ) ВОЗНИКАЮЩИМ В ЛЮБОМ СПОСОБЕ
.\" ВНЕ ИСПОЛЬЗОВАНИЯ ЭТОГО ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ, ДАЖЕ ЕСЛИ БЫЛО ПРЕДУПРЕЖДЕНИЕ О ВОЗМОЖНОСТИ ТАКОГО УЩЕРБА.
.\"
.Dd 26 июля 2023 года
.Dt GPART 8
.Os
.Sh НАЗВАНИЕ
.Nm gpart
.Nd "утилита управления разделением диска для класса GEOM"
.Sh СИНТАКСИС
.\" ==== ДОБАВИТЬ ====
.Nm
.Cm add
.Fl t Ar тип
.Op Fl a Ar выравнивание
.Op Fl b Ar начало
.Op Fl s Ar размер.Op Fl i Ar index
.Op Fl l Ar метка
.Op Fl f Ar флаги
.Ar geom
.\" ==== РЕЗЕРВНОЕ КОПИРОВАНИЕ ====
.Nm
.Cm backup
.Ar geom
.\" ==== ЗАГРУЗОЧНЫЙ КОД ====
.Nm
.Cm bootcode
.Op Fl N
.Op Fl b Ar загрузочный_код
.Op Fl p Ar часть_кода Fl i Ar index
.Op Fl f Ar флаги
.Ar geom
.\" ==== ПОДТВЕРЖДЕНИЕ ====
.Nm
.Cm commit
.Ar geom
.\" ==== СОЗДАНИЕ ====
.Nm
.Cm create
.Fl s Ar схема
.Op Fl n Ar вводы
.Op Fl f Ar флаги
.Ar провайдер
.\" ==== УДАЛЕНИЕ ====
.Nm
.Cm delete
.Fl i Ar index
.Op Fl f Ar флаги
.Ar geom
.\" ==== УНИЧТОЖЕНИЕ ====
.Nm
.Cm destroy
.Op Fl F
.Op Fl f Ar флаги
.Ar geom
.\" ==== ИЗМЕНЕНИЕ ====
.Nm
.Cm modify
.Fl i Ar index
.Op Fl l Ar метка
.Op Fl t Ar тип
.Op Fl f Ar флаги
.Ar geom
.\" ==== ВОССТАНОВЛЕНИЕ ====
.Nm
.Cm recover
.Op Fl f Ar флаги
.Ar geom
.\" ==== ИЗМЕНЕНИЕ РАЗМЕРА ====
.Nm
.Cm resize
.Fl i Ar index
.Op Fl a Ar выравнивание
.Op Fl s Ar размер
.Op Fl f Ar флаги
.Ar geom
.\" ==== ВОССТАНОВЛЕНИЕ ИЗ РЕЗЕРВНОЙ КОПИИ ====
.Nm
.Cm restore
.Op Fl lF
.Op Fl f Ar флаги
.Ar провайдер
.Op Ar ...
.\" ==== УСТАНОВКА ====
.Nm
.Cm set
.Fl a Ar атрибут
.Fl i Ar index
.Op Fl f Ar флаги
.Ar geom
.\" ==== ПОКАЗАТЬ ====
.Nm
.Cm show
.Op Fl l | r
.Op Fl p
.Op Ar geom ...
.\" ==== ОТМЕНА ====
.Nm
.Cm undo
.Ar geom
.\" ==== СНЯТИЕ УСТАНОВКИ ====
.Nm
.Cm unset
.Fl a Ar атрибут
.Fl i Ar index
.Op Fl f Ar флаги
.Ar geom
.\"
.Nm
.Cm list
.Nm
.Cm status
.Nm
.Cm load
.Nm
.Cm unload
.Sh ОПИСАНИЕ
The
.Nm
утилита используется для разбиения на разделы GEOM провайдеров, обычно дисков.
Первый аргумент - это действие, которое должно быть выполнено:
.Bl -tag -width ".Cm загрузочный_код"
.\" ==== ДОБАВЛЕНИЕ ====
.It Cm add
Добавление нового раздела в схему разбиения, указанную
.Ar geom .
Тип раздела должен быть указан с помощью
.Fl t Ar тип .
Местоположение раздела, размер и другие атрибуты будут рассчитаныАвтоматически, если соответствующие опции не указаны.
.Pp
Команда
.Cm add
принимает следующие опции:
.Bl -tag -width 12n
.It Fl a Ar alignment
Если указано, то утилита
.Nm
пытается выровнять
.Ar start
смещение и размер раздела
.Ar size
чтобы они были кратны
.Ar alignment
значению.
.It Fl b Ar start
Логический блочный адрес, где раздел будет начинаться.
Допускается использование суффикса единицы измерения СИ.
.It Fl f Ar flags
Дополнительные операционные флаги.
Смотрите раздел под названием
.Sx "OPERATIONAL FLAGS"
ниже для обсуждения
его использования.
.It Fl i Ar index
Индекс в таблице разделов, на котором новый раздел должен быть
размещен.
Индекс определяет имя специального файла устройства, используемого
для представления раздела.
.It Fl l Ar label
Метка, прикрепленная к разделу.
Эта опция действительна только при использовании на схемах разделения, которые поддерживают
метки разделов.
.It Fl s Ar size
Создать раздел размера
.Ar size .
Допускается использование суффикса единицы измерения СИ.
.It Fl t Ar type
Создать раздел типа
.Ar type .
Типы разделов обсуждаются ниже в разделе под названием
.Sx "PARTITION TYPES" .
.El
.\" ==== РЕЗЕРВНОЕ КОПИРОВАНИЕ ====
.It Cm backup
Выгрузить таблицу разделов в стандартный вывод в специальном формате, используемом действием
.Cm restore
.
.\" ==== ЗАГРУЗОЧНЫЙ КОД ====
.It Cm bootcode
Внедрить загрузочный код в метаданные схемы разделения на
.Ar geom
(используя
.Fl b Ar bootcode )
или записать загрузочный код в раздел (используя
.Fl p Ar partcode
и
.Fl i Ar index ).
.Pp
Команда
.Cm bootcode
принимает следующие опции:
.Bl -tag -width 10n
.It Fl N
Не сохранять серийный номер тома для MBR.
MBR загрузочный код по умолчанию содержит серийный номер тома, и

.Nm
пытается сохранить его при установке нового загрузочного кода.
Эта опция пропускает сохранение, чтобы помочь с некоторыми версиями
.Xr boot0cfg 8
которые не поддерживают серийный номер тома.
.It Fl b Ar bootcode
Внедрить загрузочный код из файла
.Ar bootcode
в метаданные схемы разбиения для
.Ar geom.
Не все схемы разбиения имеют встроенный загрузочный код, поэтому опция
.Fl b Ar bootcode
специфична для схемы (см. раздел под названием
.Sx BOOTSTRAPPING
ниже).
Файл
.Ar bootcode
должен соответствовать требованиям схемы разбиения к содержанию и размеру файла.
.It Fl f Ar flags
Дополнительные операционные флаги.
Смотрите раздел под названием
.Sx "ОПЕРАЦИОННЫЕ ФЛАГИ"
ниже для обсуждения
их использования.
.It Fl i Ar index
Укажите целевой раздел для
.Fl p Ar partcode.
.It Fl p Ar partcode
Записать загрузочный код из файла
.Ar partcode
в указанный
.Ar geom
раздел, определенный с помощью
.Fl i Ar index.
Размер файла должен быть меньше размера раздела.
.El
.\" ==== COMMIT ====
.It Cm commit
Подтвердите любые ожидаемые изменения для geom
.Ar geom.
Все действия по умолчанию подтверждаются и не приведут к
ожидающим изменениям.
Действия могут быть изменены с помощью опции
.Fl f Ar flags,
так что они не подтверждаются, а становятся ожидающими.
Ожидающие изменения отражаются geom и утилитой
.Nm,
но они на самом деле не записываются на диск.
Действие
.Cm commit
запишет все ожидающие изменения на диск.
.\" ==== CREATE ====
.It Cm create
Создать новую схему разбиения на устройство, предоставленное
.Ar provider.
Схему, которую нужно использовать, следует указать с помощью опции
.Fl s Ar scheme.
.Pp
The.Cm create
команда принимает следующие опции:
.Bl -tag -width 10n
.It Fl f Ar flags
Дополнительные операционные флаги.
Смотрите раздел под названием
.Sx "ОПЕРАЦИОННЫЕ ФЛАГИ"
ниже для обсуждения
их использования.
.It Fl n Ar entries
Количество записей в таблице разделов.
Каждая схема разбиения имеет минимальное и максимальное число записей.
Эта опция позволяет создавать таблицы с количеством записей,
которое находится в пределах лимитов.
Некоторые схемы имеют максимум равный минимуму, а некоторые схемы имеют
максимум достаточно велик, чтобы считаться неограниченным.
По умолчанию, таблицы разделов создаются с минимальным числом
записей.
.It Fl s Ar scheme
Указать схему разбиения для использования.
Ядро должно иметь поддержку определённой схемы перед
тем как эта схема может быть использована для разбиения диска.
.El
.\" ==== DELETE ====
.It Cm delete
Удалить раздел из geom
.Ar geom
и дополнительно идентифицированный опцией
.Fl i Ar index
.
Раздел не может быть активно использован ядром.
.Pp
Команда
.Cm delete
принимает следующие опции:
.Bl -tag -width 10n
.It Fl f Ar flags
Дополнительные операционные флаги.
Смотрите раздел под названием
.Sx "ОПЕРАЦИОННЫЕ ФЛАГИ"
ниже для обсуждения
их использования.
.It Fl i Ar index
Указывает индекс раздела, который будет удалён.
.El
.\" ==== DESTROY ====
.It Cm destroy
Уничтожить схему разбиения, реализованную в geom
.Ar geom .
.Pp
Команда
.Cm destroy
принимает следующие опции:
.Bl -tag -width 10n
.It Fl F
Принудительное уничтожение таблицы разделов даже если она не пуста.
.It Fl f Ar flags
Дополнительные операционные флаги.
Смотрите раздел под названием
.Sx "ОПЕРАЦИОННЫЕ ФЛАГИ"
ниже для обсуждения.El
.\" ==== ИЗМЕНИТЬ ====
.It Cm modify
Изменить раздел в geom
.Ar geom
идентифицируемый дополнительно с помощью опции
.Fl i Ar index
.
Можно изменить только тип и/или метку раздела.
Не все схемы разбиения поддерживают метки, и попытка
изменить метку раздела в таких случаях недопустима.
.Pp
Команда
.Cm modify
принимает следующие опции:
.Bl -tag -width 10n
.It Fl f Ar flags
Дополнительные операционные флаги.
Смотрите раздел
.Sx "ОПЕРАЦИОННЫЕ ФЛАГИ"
ниже для обсуждения
их использования.
.It Fl i Ar index
Указывает индекс изменяемого раздела.
.It Fl l Ar label
Изменить метку раздела на
.Ar label .
.It Fl t Ar type
Изменить тип раздела на
.Ar type .
.El
.\" ==== ВОССТАНОВИТЬ ====
.It Cm recover
Восстановить метаданные схемы поврежденного раздела на geom
.Ar geom .
Смотрите раздел
.Sx ВОССТАНОВЛЕНИЕ
ниже для дополнительной информации.
.Pp
Команда
.Cm recover
принимает следующие опции:
.Bl -tag -width 10n
.It Fl f Ar flags
Дополнительные операционные флаги.
Смотрите раздел
.Sx "ОПЕРАЦИОННЫЕ ФЛАГИ"
ниже для обсуждения
их использования.
.El
.\" ==== ИЗМЕНИТЬ РАЗМЕР ====
.It Cm resize
Изменить размер раздела в geom
.Ar geom
идентифицируемый дополнительно с помощью опции
.Fl i Ar index
.
Если новый размер не указан, он автоматически рассчитывается
как максимально доступный из
.Ar geom .
.Pp
Команда
.Cm resize
принимает следующие опции:
.Bl -tag -width 12n
.It Fl a Ar alignment
Если указано, то утилита
.Nm
пытается выравнивать размер раздела
.Ar size
чтобы он был кратен значению
.Ar alignment
.
.It Fl f Ar flags
Дополнительные операционные флаги.
Смотрите раздел
.Sx "ОПЕРАЦИОННЫЕ ФЛАГИ"
ниже для обсуждения
их использования.
.It Fl i Ar index
Указывает индекс раздела, который нужно изменить.
.It Fl s Ar size
Указывает новый размер раздела в логических блоках.
Допускается использование суффикса единицы измерения СИ.
.El
.\" ==== ВОССТАНОВЛЕНИЕ ====
.It Cm restore
Восстановление таблицы разделов из ранее созданной резервной копии
.Cm backup
и чтение со стандартного ввода.
Восстанавливается только таблица разделов.
Это действие не затрагивает содержимое разделов.
После восстановления таблицы разделов и при необходимости записи загрузочного кода,
пользовательские данные должны быть восстановлены из резервной копии.
.Pp
Команда
.Cm restore
принимает следующие опции:
.Bl -tag -width 10n
.It Fl F
Уничтожить таблицу разделов на указанном
.Ar provider
перед началом восстановления.
.It Fl f Ar flags
Дополнительные операционные флаги.
Смотрите раздел
.Sx "ОПЕРАЦИОННЫЕ ФЛАГИ"
ниже для обсуждения
их использования.
.It Fl l
Восстановить метки разделов для схем разбиения, которые их поддерживают.
.El
.\" ==== УСТАНОВИТЬ ====
.It Cm set
Установить указанный атрибут на записи раздела.
Смотрите раздел
.Sx АТРИБУТЫ
ниже для списка доступных атрибутов.
.Pp
Команда
.Cm set
принимает следующие опции:
.Bl -tag -width 10n
.It Fl a Ar attrib
Указывает атрибут для установки.
.It Fl f Ar flags
Дополнительные операционные флаги.
Смотрите раздел
.Sx "ОПЕРАЦИОННЫЕ ФЛАГИ"
ниже для обсуждения
их использования.
.It Fl i Ar index
Указывает индекс раздела, на котором будет установлен атрибут.
.El
.\" ==== ПОКАЗАТЬ ====
.It Cm show
Показать текущую информацию о разделах для указанных geom или всех
geom, если они не указаны.
Вывод по умолчанию включает логический начальный блок каждогоразмер раздела в блоках, индексный номер раздела,
тип раздела и размер раздела, понятный человеку.
Размеры блоков и их расположение основаны на размере сектора устройства,
как показано командой
.Cm gpart list .
.Pp
Команда
.Cm show
принимает следующие опции:
.Bl -tag -width 10n
.It Fl l
Для схем разделения, которые поддерживают метки разделов, выводят их
вместо типа раздела.
.It Fl p
Показывает имена провайдеров вместо индексов разделов.
.It Fl r
Показывает сырой тип раздела вместо символического названия.
.El
.\" ==== UNDO ====
.It Cm undo
Отменяет все ожидающие изменения для geom
.Ar geom .
Это действие противоположно действию
.Cm commit
и может быть использовано для отмены любых изменений, которые не были подтверждены.
.\" ==== UNSET ====
.It Cm unset
Очищает указанный атрибут в записи раздела.
Смотрите раздел
.Sx ATTRIBUTES
ниже для списка доступных атрибутов.
.Pp
Команда
.Cm unset
принимает следующие опции:
.Bl -tag -width 10n
.It Fl a Ar attrib
Указывает атрибут для очистки.
.It Fl f Ar flags
Дополнительные операционные флаги.
Смотрите раздел
.Sx "OPERATIONAL FLAGS"
ниже для обсуждения
их использования.
.It Fl i Ar index
Указывает индекс раздела, на котором будет очищен атрибут.
.El
.It Cm list
Смотрите
.Xr geom 8 .
.It Cm status
Смотрите
.Xr geom 8 .
.It Cm load
Смотрите
.Xr geom 8 .
.It Cm unload
Смотрите
.Xr geom 8 .
.El
.Sh PARTITIONING SCHEMES
Утилита
.Nm
поддерживает несколько схем разделения:
.Bl -tag -width ".Cm BSD64"
.It Cm APM
Карта разделов Apple, используемая компьютерами Macintosh(R) с PowerPC(R).
Требуется опция ядра
.Cd GEOM_PART_APM
.It Cm BSD
Традиционный BSD
.Xr disklabel 8 ,
обычно используется для разделения MBR-разделов.
.Po
Эта схема также может быть использована в качестве единственного метода разбиения на разделы, без
использования MBR.
Инструменты для редактирования разделов с других операционных систем зачастую не
понимают логику работы с разделами только с disklabel, поэтому это иногда
называется
.Dq опасно посвященным (dangerously dedicated).
.Pc
Требуется опция ядра
.Cm GEOM_PART_BSD.
.It Cm BSD64
64-битная реализация disklabel BSD, используемая в
.Dx
для разделения MBR
или разделов GPT.
Требуется опция ядра
.Cm GEOM_PART_BSD64.
.It Cm LDM
Логический дисковый менеджер - это реализация менеджера томов для
Microsoft Windows NT.
Требуется опция ядра
.Cd GEOM_PART_LDM.
.It Cm GPT
Таблица разделов GUID используется на компьютерах Macintosh на базе Intel и
постепенно заменяет MBR на большинстве ПК и других системах.
Требуется опция ядра
.Cm GEOM_PART_GPT.
.It Cm MBR
Загрузочный сектор (Master Boot Record) используется на ПК и сменных носителях.
Требуется опция ядра
.Cm GEOM_PART_MBR.
Опция
.Cm GEOM_PART_EBR
добавляет поддержку Расширенного Загрузочного Сектора (Extended Boot Record, EBR),
используемого для определения логического раздела.
Опция
.Cm GEOM_PART_EBR_COMPAT
включает обратную совместимость для имен разделов
в схеме EBR.
Также предотвращает любые действия с такими разделами.
.El
.Pp
См.
.Xr glabel 8
для дополнительной информации о маркировке устройств и разделов.
.Sh ТИПЫ РАЗДЕЛОВ
Типы разделов идентифицируются на диске с помощью определенных строк или магических
значений.
Утилита
.Nm
использует символические имена для общих типов разделов, так что пользователю
не нужно знать эти значения или другие детали соответствующей схемы разбиения на разделы.Утилита 
.Nm 
также позволяет пользователю указывать типы разделов, специфичные для схемы, для типов разделов, которые не имеют символических имен.
Текущие символические имена, которые понимаются и используются 
.Fx, 
следующие:
.Bl -tag -width ".Cm dragonfly-disklabel64"
.It Cm apple-boot
Системный раздел, предназначенный для хранения загрузчиков на некоторых системах Apple.
Типы, специфичные для схемы, следующие:
.Qq Li "!171"
для MBR,
.Qq Li "!Apple_Bootstrap"
для APM и
.Qq Li "!426f6f74-0000-11aa-aa11-00306543ecac"
для GPT.
.It Cm bios-boot
Системный раздел, предназначенный для второй стадии программы загрузчика.
Обычно он используется загрузчиком GRUB 2 для схем разделов GPT.
Тип, специфичный для схемы, следующий:
.Qq Li "!21686148-6449-6E6F-744E-656564454649" .
.It Cm efi
Системный раздел для компьютеров, использующих интерфейс Extensible Firmware Interface (EFI).
Типы, специфичные для схемы, следующие:
.Qq Li "!239"
для MBR, и
.Qq Li "!c12a7328-f81f-11d2-ba4b-00a0c93ec93b"
для GPT.
.It Cm freebsd
Раздел 
.Fx, 
разделенный на файловые системы с помощью дисковой метки 
.Bx.
Это устаревший тип раздела и его не следует использовать для схем APM или GPT.
Типы, специфичные для схемы, следующие:
.Qq Li "!165"
для MBR,
.Qq Li "!FreeBSD"
для APM, и
.Qq Li "!516e7cb4-6ecf-11d6-8ff8-00022d09712b"
для GPT.
.It Cm freebsd-boot
Раздел 
.Fx, 
предназначенный для начального кода загрузки.
Тип, специфичный для схемы, следующий:
.Qq Li "!83bd6b9d-7f41-11dc-be0b-001560b84f0f"
для GPT.
.It Cm freebsd-swap
Раздел 
.Fx, 
предназначенный для пространства подкачки.
Типы, специфичные для схемы, следующие:
.Qq Li "!FreeBSD-swap"
для APM, и
.Qq Li "!516e7cb5-6ecf-11d6-8ff8-00022d09712b"
для GPT.
.It Cm freebsd-ufs
Раздел 
.Fx, 
содержащий файловую систему UFS или UFS2.Специфичные для схемы типы:
.Qq Li "!FreeBSD-UFS"
для APM и
.Qq Li "!516e7cb6-6ecf-11d6-8ff8-00022d09712b"
для GPT.
.It Cm freebsd-vinum
Раздел
.Fx,
содержащий том Vinum.
Специфичные для схемы типы:
.Qq Li "!FreeBSD-Vinum"
для APM и
.Qq Li "!516e7cb8-6ecf-11d6-8ff8-00022d09712b"
для GPT.
.It Cm freebsd-zfs
Раздел
.Fx,
содержащий том ZFS.
Специфичные для схемы типы:
.Qq Li "!FreeBSD-ZFS"
для APM и
.Qq Li "!516e7cba-6ecf-11d6-8ff8-00022d09712b"
для GPT.
.El
.Pp
Другие символические имена, которые могут быть использованы с утилитой
.Nm:
.Bl -tag -width ".Cm dragonfly-disklabel64"
.It Cm apple-apfs
Раздел Apple macOS, используемый для файловой системы Apple, APFS.
.It Cm apple-core-storage
Раздел Apple Mac OS X, используемый менеджером логических томов, известным как Core Storage.
Специфичный для схемы тип:
.Qq Li "!53746f72-6167-11aa-aa11-00306543ecac"
для GPT.
.It Cm apple-hfs
Раздел Apple Mac OS X, содержащий файловую систему HFS или HFS+.
Специфичные для схемы типы:
.Qq Li "!175"
для MBR,
.Qq Li "!Apple_HFS"
для APM и
.Qq Li "!48465300-0000-11aa-aa11-00306543ecac"
для GPT.
.It Cm apple-label
Раздел Apple Mac OS X, предназначенный для метаданных раздела, описывающих дисковое устройство.
Специфичный для схемы тип:
.Qq Li "!4c616265-6c00-11aa-aa11-00306543ecac"
для GPT.
.It Cm apple-raid
Раздел Apple Mac OS X, используемый в конфигурации программного RAID.
Специфичный для схемы тип:
.Qq Li "!52414944-0000-11aa-aa11-00306543ecac"
для GPT.
.It Cm apple-raid-offline
Раздел Apple Mac OS X, используемый в конфигурации программного RAID.
Специфичный для схемы тип:
.Qq Li "!52414944-5f4f-11aa-aa11-00306543ecac".It Cm apple-tv-recovery
Раздел Apple Mac OS X, используемый Apple TV.
Специфичный для схемы тип:
.Qq Li "!5265636f-7665-11aa-aa11-00306543ecac"
для GPT.
.It Cm apple-ufs
Раздел Apple Mac OS X, содержащий файловую систему UFS.
Специфичные для схемы типы:
.Qq Li "!168"
для MBR,
.Qq Li "!Apple_UNIX_SVR2"
для APM и
.Qq Li "!55465300-0000-11aa-aa11-00306543ecac"
для GPT.
.It Cm apple-zfs
Раздел Apple Mac OS X, содержащий том ZFS.
Специфичный для схемы тип:
.Qq Li "!6a898cc3-1dd2-11b2-99a6-080020736631"
для GPT.
Тот же GUID также используется для
.Sy illumos/Solaris /usr раздела.
Смотрите
.Sx CAVEATS
ниже.
.It Cm dragonfly-label32
Раздел
.Dx
с файловыми системами, подразделенный с помощью
.Bx
disklabel.
Специфичный для схемы тип:
.Qq Li "!9d087404-1ca5-11dc-8817-01301bb8a9f5"
для GPT.
.It Cm dragonfly-label64
Раздел
.Dx
с файловыми системами, подразделенный с помощью
disklabel64.
Специфичный для схемы тип:
.Qq Li "!3d48ce54-1d16-11dc-8696-01301bb8a9f5"
для GPT.
.It Cm dragonfly-legacy
Устаревший тип раздела, используемый в
.Dx.
Специфичный для схемы тип:
.Qq Li "!bd215ab2-1d16-11dc-8696-01301bb8a9f5"
для GPT.
.It Cm dragonfly-ccd
Раздел
.Dx
используемый с драйвером Concatenated Disk.
Специфичный для схемы тип:
.Qq Li "!dbd5211b-1ca5-11dc-8817-01301bb8a9f5"
для GPT.
.It Cm dragonfly-hammer
Раздел
.Dx
содержащий файловую систему Hammer.
Специфичный для схемы тип:
.Qq Li "!61dc63ac-6e38-11dc-8513-01301bb8a9f5"
для GPT.
.It Cm dragonfly-hammer2
Раздел
.Dx
содержащий файловую систему Hammer2.
Специфичный для схемы тип:
.Qq Li "!5cbb9ad1-862d-11dc-a94d-01301bb8a9f5"
для GPT..It Cm dragonfly-swap
.Dx
раздел, выделенный под область подкачки.
Специфический для схемы тип -
.Qq Li "!9d58fdbd-1ca5-11dc-8817-01301bb8a9f5"
для GPT.
.It Cm dragonfly-ufs
.Dx
раздел, содержащий файловую систему UFS1.
Специфический для схемы тип -
.Qq Li "!9d94ce7c-1ca5-11dc-8817-01301bb8a9f5"
для GPT.
.It Cm dragonfly-vinum
.Dx
раздел, используемый с Менеджером Логических Томов.
Специфический для схемы тип -
.Qq Li "!9dd4478f-1ca5-11dc-8817-01301bb8a9f5"
для GPT.
.It Cm ebr
Раздел, подразделенный на файловые системы с EBR.
Специфический для схемы тип -
.Qq Li "!5"
для MBR.
.It Cm fat16
Раздел, содержащий файловую систему FAT16.
Специфический для схемы тип -
.Qq Li "!6"
для MBR.
.It Cm fat32
Раздел, содержащий файловую систему FAT32.
Специфический для схемы тип -
.Qq Li "!11"
для MBR.
.It Cm fat32lba
Раздел, содержащий файловую систему FAT32 (LBA).
Специфический для схемы тип -
.Qq Li "!12"
для MBR.
.It Cm hifive-fsbl
Неформатированный раздел, содержащий первичный загрузчик HiFive.
Специфический для схемы тип -
.Qq Li "!5b193300-fc78-40cd-8002-e86c45580b47"
для GPT.
.It Cm hifive-bbl
Неформатированный раздел, содержащий вторичный загрузчик HiFive.
Специфический для схемы тип -
.Qq Li "!2e54b353-1271-4842-806f-e436d6af6985"
для GPT.
.It Cm linux-data
Linux раздел, содержащий файловую систему с данными.
Специфические для схемы типы -
.Qq Li "!131"
для MBR и
.Qq Li "!0fc63daf-8483-4772-8e79-3d69d8477de4"
для GPT.
.It Cm linux-lvm
Linux раздел, выделенный под Менеджер Логических Томов.
Специфические для схемы типы -
.Qq Li "!142"
для MBR и
.Qq Li "!e6d6d379-f507-44c2-a23c-238f2a3df928"
для GPT.Раздел Linux, используемый в конфигурации программного RAID.
Специфичные для схемы типы:
.Qq Li "!253"
для MBR и
.Qq Li "!a19d880f-05fc-4d3b-a006-743f0f84911e"
для GPT.
.It Cm linux-swap
Раздел Linux, выделенный под область подкачки.
Специфичные для схемы типы:
.Qq Li "!130"
для MBR и
.Qq Li "!0657fd6d-a4ab-43c4-84e5-0933c84b4f4f"
для GPT.
.It Cm mbr
Раздел, который подразделен Master Boot Record (MBR).
Этот тип известен как
.Qq Li "!024dee41-33e7-11d3-9d69-0008c781f39f"
в GPT.
.It Cm ms-basic-data
Базовый раздел данных (BDP) для операционных систем Microsoft.
В GPT этот тип эквивалентен типам разделов
.Cm fat16, fat32
и
.Cm ntfs
в MBR.
Этот тип используется для разделов GPT с файловой системой exFAT.
Специфичный для схемы тип:
.Qq Li "!ebd0a0a2-b9e5-4433-87c0-68b6b72699c7"
для GPT.
.It Cm ms-ldm-data
Раздел, содержащий тома Логического Дискового Менеджера (LDM).
Специфичные для схемы типы:
.Qq Li "!66"
для MBR,
.Qq Li "!af9b60a0-1431-4f62-bc68-3311714a69ad"
для GPT.
.It Cm ms-ldm-metadata
Раздел, содержащий базу данных Логического Дискового Менеджера (LDM).
Специфичный для схемы тип:
.Qq Li "!5808c8aa-7e8f-42e0-85d2-e1e90434cfb3"
для GPT.
.It Cm netbsd-ccd
Раздел
.Nx
, используемый с драйвером Concatenated Disk.
Специфичный для схемы тип:
.Qq Li "!2db519c4-b10f-11dc-b99b-0019d1879648"
для GPT.
.It Cm netbsd-cgd
Зашифрованный раздел
.Nx
.
Специфичный для схемы тип:
.Qq Li "!2db519ec-b10f-11dc-b99b-0019d1879648"
для GPT.
.It Cm netbsd-ffs
Раздел
.Nx
, который содержит файловую систему UFS.
Специфичный для схемы тип:
.Qq Li "!49f48d5a-b10e-11dc-b99b-0019d1879648"
для GPT..Rs
Файловая система NetBSD LFS
.Re
Файловая система NetBSD LFS содержится в
.Nx
разделе. Специфический для схемы тип —
.Qq Li "!49f48d82-b10e-11dc-b99b-0019d1879648"
для GPT.
.Rs
NetBSD RAID
.Re
.Nx
раздел, используемый в конфигурации программного RAID.
Специфический для схемы тип —
.Qq Li "!49f48daa-b10e-11dc-b99b-0019d1879648"
для GPT.
.Rs
NetBSD swap
.Re
.Nx
раздел, выделенный под область подкачки.
Специфический для схемы тип —
.Qq Li "!49f48d32-b10e-11dc-b99b-0019d1879648"
для GPT.
.Rs
NTFS
.Re
Раздел, содержащий файловую систему NTFS или exFAT.
Специфический для схемы тип —
.Qq Li "!7"
для MBR.
.Rs
Prep-boot
.Re
Системный раздел, выделенный для хранения загрузчиков на некоторых системах PowerPC,
особенно на тех, что произведены IBM.
Специфические для схемы типы —
.Qq Li "!65"
для MBR и
.Qq Li "!9e1a2d38-c612-4316-aa26-8b49521e5a8b"
для GPT.
.Rs
Solaris-boot
.Re
Раздел illumos/Solaris, выделенный для загрузчика.
Специфический для схемы тип —
.Qq Li "!6a82cb45-1dd2-11b2-99a6-080020736631"
для GPT.
.Rs
Solaris-root
.Re
Раздел illumos/Solaris, выделенный для корневой файловой системы.
Специфический для схемы тип —
.Qq Li "!6a85cf4d-1dd2-11b2-99a6-080020736631"
для GPT.
.Rs
Solaris-swap
.Re
Раздел illumos/Solaris, выделенный для области подкачки.
Специфический для схемы тип —
.Qq Li "!6a87c46f-1dd2-11b2-99a6-080020736631"
для GPT.
.Rs
Solaris-backup
.Re
Раздел illumos/Solaris, выделенный для резервного копирования.
Специфический для схемы тип —
.Qq Li "!6a8b642b-1dd2-11b2-99a6-080020736631"
для GPT.
.Rs
Solaris-var
.Re
Раздел illumos/Solaris, выделенный для файловой системы /var.
Специфический для схемы тип —
.Qq Li "!6a8ef2e9-1dd2-11b2-99a6-080020736631"
для GPT.
.Rs
Solaris-home
.Re
(продолжение следует...)Раздел Illumos/Solaris, предназначенный для файловой системы /home.
Специфический для схемы тип:
.Qq Li "!6a90ba39-1dd2-11b2-99a6-080020736631"
для GPT.
.It Cm solaris-altsec
Раздел Illumos/Solaris, предназначенный для альтернативного сектора.
Специфический для схемы тип:
.Qq Li "!6a9283a5-1dd2-11b2-99a6-080020736631"
для GPT.
.It Cm solaris-reserved
Раздел Illumos/Solaris, предназначенный для зарезервированного пространства.
Специфический для схемы тип:
.Qq Li "!6a945a3b-1dd2-11b2-99a6-080020736631"
для GPT.
.It Cm vmware-vmfs
Раздел, содержащий файловую систему VMware (VMFS).
Специфический для схемы тип:
.Qq Li "!251"
для MBR и
.Qq Li "!aa31e02a-400f-11db-9590-000c2911d1b8"
для GPT.
.It Cm vmware-vmkdiag
Раздел, содержащий диагностическую файловую систему VMware.
Специфический для схемы тип:
.Qq Li "!252"
для MBR и
.Qq Li "!9d275380-40ad-11db-bf97-000c2911d1b8"
для GPT.
.It Cm vmware-reserved
Зарезервированный раздел VMware.
Специфический для схемы тип:
.Qq Li "!9198effc-31c0-11db-8f-78-000c2911d1b8"
для GPT.
.It Cm vmware-vsanhdr
Раздел, заявленный VMware VSAN.
Специфический для схемы тип:
.Qq Li "!381cfccc-7288-11e0-92ee-000c2911d0b2"
для GPT.
.El
.Sh ATTRIBUTES
Специфические атрибуты для EBR:
.Bl -tag -width ".Cm active"
.It Cm active
.El
.Pp
Специфические атрибуты для GPT:
.Bl -tag -width ".Cm bootfailed"
.It Cm bootme
Когда установлен, загрузчик первой стадии
.Nm gptboot
попытается загрузить систему с этого раздела.
Несколько разделов могут быть отмечены атрибутом
.Cm bootme
Смотрите
.Xr gptboot 8
для более подробной информации.
.It Cm bootonce
Установка этого атрибута автоматически устанавливает атрибут
.Cm bootme
Когда установлен, загрузчик первой стадии
.Nm gptboot
будет попытаться загрузить систему с этого раздела только один раз.
Несколько разделов можно отметить с помощью пар атрибутов
.Cm bootonce
и
.Cm bootme
Смотрите
.Xr gptboot 8
для получения дополнительной информации.
.It Cm bootfailed
Этот атрибут не следует управлять вручную.
Его управляет загрузчик первой стадии
.Nm gptboot
и скрипт запуска
.Pa /etc/rc.d/gptboot
Смотрите
.Xr gptboot 8
для получения дополнительной информации.
.It Cm lenovofix
Установка этого атрибута перезаписывает Защитную MBR новой, где
раздел 0xee является вторым, а не первым записью.
Это решает проблему совместимости BIOS с некоторыми моделями Lenovo, включая
X220, T420 и T520, позволяя им загружаться с дисков, разделенных с помощью GPT
без использования EFI.
.El
.Pp
Специфические атрибуты схемы для MBR:
.Bl -tag -width ".Cm active"
.It Cm active
.El
.Sh BOOTSTRAPPING
.Fx
поддерживает несколько схем разбиения на разделы и каждая схема использует разный
загрузочный код.
Загрузочный код расположен в определенной области диска для каждой схемы разбиения на разделы и может варьироваться по размеру для разных схем.
.Pp
Загрузочный код можно разделить на два типа.
Первый тип встроен в метаданные схемы разбиения на разделы, в то время как
второй тип находится на определенном разделе.
Встраивание загрузочного кода должно выполняться только с помощью команды
.Cm gpart bootcode
с опцией
.Fl b Ar bootcode
Класс GEOM PART знает, как безопасно встраивать загрузочный код в
метаданные конкретной схемы разбиения на разделы, не причиняя никакого ущерба.
.Pp
Master Boot Record (MBR) использует 512-байтовый образ загрузочного кода, встроенного
в область метаданных таблицы разделов.Существует два варианта кода начальной загрузки:
.Pa /boot/mbr
и
.Pa /boot/boot0 .
.Pa /boot/mbr
ищет в таблице разделов раздел с атрибутом
.Cm active
(смотрите раздел
.Sx ATTRIBUTES),
затем выполняет следующий этап начальной загрузки.
Образ
.Pa /boot/boot0
содержит менеджер загрузки с некоторыми дополнительными интерактивными функциями
для мультизагрузки с выбранного пользователем раздела.
.Pp
Разметка диска BSD обычно создается внутри раздела MBR (сектора)
с типом
.Cm freebsd
(смотрите раздел
.Sx "ТИПЫ РАЗДЕЛОВ").
Используется образ кода начальной загрузки размером 8 КБ
.Pa /boot/boot ,
встроенный в область метаданных таблицы разделов.
.Pp
Оба типа кода начальной загрузки используются для загрузки с таблицы разделов GUID.
Сначала защитный MBR встраивается в первый сектор диска из образа
.Pa /boot/pmbr .
Он ищет в GPT раздел
.Cm freebsd-boot
(смотрите раздел
.Sx "ТИПЫ РАЗДЕЛОВ") и выполняет следующий этап начальной загрузки с него.
Раздел
.Cm freebsd-boot
должен быть меньше 545 КБ.
Он может быть расположен как до, так и после других разделов
.Fx
на диске.
Существует два варианта кода начальной загрузки для записи в этот раздел:
.Pa /boot/gptboot
и
.Pa /boot/gptzfsboot .
.Pp
.Pa /boot/gptboot
используется для загрузки с разделов UFS.
.Cm gptboot
просматривает разделы
.Cm freebsd-ufs
в GPT и выбирает один для загрузки на основе атрибутов
.Cm bootonce
и
.Cm bootme .
Если ни один атрибут не найден,
.Pa /boot/gptboot
загружается с первого раздела
.Cm freebsd-ufs .
.Pa /boot/loader
.Pq третий этап начальной загрузки
загружается с первого раздела, который соответствует этим условиям.Для получения дополнительной информации смотри
.Xr gptboot 8 .
.Pp
.Pa /boot/gptzfsboot
используется для загрузки с ZFS.
Он ищет в GPT
.Cm freebsd-zfs
разделы, пытаясь обнаружить пулы ZFS.
После того как все пулы обнаружены,
.Pa /boot/loader
запускается с первого найденного, установленного как загрузочный.
.Pp
Схема APM также не поддерживает встраивание кода загрузки.
Вместо этого, образ кода загрузки размером 800 КБайт
.Pa /boot/boot1.hfs
должен быть записан с помощью команды
.Cm gpart bootcode
на раздел типа
.Cm apple-boot ,
размер которого также должен составлять 800 КБ.
.Sh ОПЕРАЦИОННЫЕ ФЛАГИ
Действия, отличные от
.Cm commit
и
.Cm undo ,
принимают необязательный параметр
.Fl f Ar flags .
Этот параметр используется для указания операционных флагов, специфичных для действия.
По умолчанию утилита
.Nm 
определяет флаг
.Ql C ,
чтобы действие было немедленно
подтверждено.
Пользователь может указать
.Dq Fl f Cm x ,
чтобы результат действия был отложенным изменением, которое позже, вместе с другими отложенными изменениями, может быть подтверждено как единое составное изменение с помощью действия
.Cm commit
или отменено с помощью действия
.Cm undo .
.Sh ВОССТАНОВЛЕНИЕ
Класс GEOM PART поддерживает восстановление таблиц разделов только для GPT.
Основные метаданные GPT хранятся в начале устройства.
Для избыточности, вторичная
.Pq backup
копия метаданных хранится в конце устройства.
В результате наличия двух копий, некоторые повреждения метаданных не
являются фатальными для работы GPT.
Когда ядро обнаруживает поврежденные метаданные, оно помечает эту таблицу как поврежденную
и сообщает о проблеме.
.Cm destroy
и
.Cm recover
- это единственные операции, разрешенные на поврежденных таблицах.
.Pp
Если один заголовок GPT кажется поврежденным, но другая копия остается целой,Ядра будут регистрировать следующее:
.Bd -literal -offset indent
GEOM: поставщик: основная таблица GPT повреждена или недействительна.
GEOM: поставщик: используется вторичная таблица -- настоятельно рекомендуется восстановление.
.Ed
.Pp
или
.Bd -literal -offset indent
GEOM: поставщик: вторичная таблица GPT повреждена или недействительна.
GEOM: поставщик: используется только основная таблица -- рекомендуется восстановление.
.Ed
.Pp
Также команды как
.Nm
например
.Cm show , status
и
.Cm list
будут сообщать о повреждённых таблицах.
.Pp
Если размер устройства изменился (например,\& расширение объёма), то
вторичный заголовок GPT больше не будет располагаться в последнем секторе.
Это не порча метаданных, но это опасно, потому что
любое повреждение основной таблицы GPT приведёт к потере таблицы разделов.
Эта проблема сообщается ядром с сообщением:
.Bd -literal -offset indent
GEOM: поставщик: вторичный заголовок GPT не находится в последнем LBA.
.Ed
.Pp
Эту ситуацию можно исправить с помощью команды
.Cm recover
Эта команда реконструирует повреждённые метаданные, используя известные действительные
метаданные и перемещает вторичную таблицу GPT в конец устройства.
.Pp
.Em ВНИМАНИЕ :
Класс GEOM PART может обнаружить одну и ту же таблицу разделов, видимую через
разные поставщики GEOM, и некоторые из них будут помечены как повреждённые.
Будьте осторожны при выборе поставщика для восстановления.
Если выбрать неправильно, вы можете уничтожить метаданные другого класса GEOM,
например,\& GEOM MIRROR или GEOM LABEL.
.Sh ПЕРЕМЕННЫЕ SYSCTL
Следующие переменные
.Xr sysctl 8
могут быть использованы для контроля поведения класса GEOM
.Nm PART
Значение по умолчанию показано рядом с каждой переменной.
.Bl -tag -width indent.It Va kern.geom.part.allow_nesting : No 0
По умолчанию некоторые схемы (в настоящее время BSD и BSD64) не разрешают
дальнейшее вложенное разделение.
Эта переменная переопределяет это ограничение и позволяет произвольное вложение (кроме
в случае разделов, созданных смещением 0).
Некоторые схемы имеют свои собственные отдельные проверки, смотрите ниже.
.It Va kern.geom.part.auto_resize : No 1
Эта переменная контролирует автоматическое изменение размера поведения класса
.Nm PART
GEOM.
Когда эта переменная включена и обнаружен новый размер провайдера, метаданные схемы
изменяются, но все изменения не сохраняются на диск до тех пор, пока не будет выполнена команда
.Cm gpart commit
для подтверждения изменений.
Это поведение также сообщается с диагностическим сообщением:
.Sy "GEOM_PART: (провайдер) был автоматически изменен в размере."
.Sy "Используйте `gpart commit (провайдер)` для сохранения изменений или `gpart undo (провайдер)`"
.Sy "для их отмены."
.It Va kern.geom.part.check_integrity : No 1
Эта переменная контролирует поведение проверок целостности метаданных.
Когда включены проверки целостности, класс
.Nm PART
GEOM проверяет все общие параметры разделов, полученные из метаданных диска.
Если обнаружено какое-либо несоответствие, таблица разделов будет
отклонена с диагностическим сообщением:
.Sy "GEOM_PART: Проверка целостности не пройдена (провайдер, схема)".
.It Va kern.geom.part.gpt.allow_nesting : No 0
По умолчанию схема GPT разрешена только на самом внешнем уровне вложенности.
Эта переменная позволяет удалить это ограничение.
.It Va kern.geom.part.ldm.debug : No 0
Уровень отладки модуля управления логическими дисками (LDM).
Может быть установлено число от 0 до 2 включительно.
Если установлено в 0, выводится минимальная отладочная информация,
и если установлено в 2, будет печатать максимум информации для отладки.
.It Va kern.geom.part.ldm.show_mirrors : Нет 0
Эта переменная контролирует, как модуль Менеджер Логических Дисков (LDM) обрабатывает
зеркальные тома.
По умолчанию зеркальные тома показываются как разделы с типом
.Cm ms-ldm-data
(смотрите раздел
.Sx "ТИПЫ РАЗДЕЛОВ").
Если эта переменная установлена в 1, каждый компонент зеркального тома будет
представлен как независимый раздел.
.Em ПРИМЕЧАНИЕ:
Это может нарушить работу зеркального тома и привести к повреждению данных.
.It Va kern.geom.part.mbr.enforce_chs : Нет 0
Укажите, как модуль Записи Основной Загрузки (MBR) проводит выравнивание.
Если эта переменная установлена в ненулевое значение, модуль автоматически
пересчитает указанные пользователем смещение и размер для выравнивания с геометрией CHS.
В противном случае значения останутся без изменений.
.It Va kern.geom.part.separator : Нет ""
Укажите необязательный разделитель, который будет вставлен между именем GEOM
и именем раздела.
Эта переменная является
.Xr загружаемой 8
настраиваемой.
Обратите внимание, что установка этой переменной может нарушить работу программного обеспечения, которое предполагает определенную
схему именования.
.El
.Sh СТАТУС ВЫХОДА
Статус выхода 0 при успешном выполнении и 1, если команда не удалась.
.Sh ПРИМЕРЫ
В приведенных ниже примерах предполагается, что логический размер блока диска составляет 512
байт, независимо от его физического размера блока.
.Ss GPT
В этом примере мы будем форматировать
.Pa ada0
с использованием схемы GPT и создадим загрузочные, своп и корневые разделы.
Сначала нам нужно создать таблицу разделов:
.Bd -literal -offset indent
/sbin/gpart create -s GPT ada0
.Ed
.Pp
Далее устанавливаем защитный MBR с загрузочным кодом первой стадии.
Защитный MBR содержит список одного загрузочного раздела, охватывающего 
ваш полный диск, что позволяет BIOS, не поддерживающим GPT, выполнять загрузку с диска
и предотвращает попытки инструментов, которые не распознают схему GPT,
считать диск ненормированным.
.Bd -literal -offset indent
/sbin/gpart bootcode -b /boot/pmbr ada0
.Ed
.Pp
Затем создаем специализированный раздел
.Cm freebsd-boot
для размещения загрузчика второй стадии, который будет загружать
.Fx
ядро и модули из файловой системы UFS или ZFS.
Этот раздел должен быть больше, чем код первой ступени загрузки
.Po
либо
.Pa /boot/gptboot
для UFS, либо
.Pa /boot/gptzfsboot
для ZFS
.Pc ,
но меньше чем 545 кБ, так как загрузчик первой стадии будет загружать
все содержимое раздела в память при загрузке, независимо от того, сколько данных
он фактически содержит.
Мы создаем загрузочный раздел размером 472 блока (236 кБ) с смещением 40, что
соответствует размеру таблицы разделов (34 блока или 17 кБ), округленного до
ближайшей границы в 4 кБ.
.Bd -literal -offset indent
/sbin/gpart add -b 40 -s 472 -t freebsd-boot ada0
/sbin/gpart bootcode -p /boot/gptboot -i 1 ada0
.Ed
.Pp
Теперь создаем 4 ГБ раздел swap в первом доступном смещении,
что составляет 40 + 472 = 512 блоков (256 кБ).
.Bd -literal -offset indent
/sbin/gpart add -s 4G -t freebsd-swap ada0
.Ed
.Pp
Выравнивание раздела swap и всех последующих разделов по границе в 256 кБ
обеспечивает оптимальную производительность на широком спектре носителей, от
обычных дисков с блоками по 512 байт, до современных дисков
.Dq advanced format
с физическими блоками по 4096 байт, до RAID-томов с размером полосы до 256 кБ.
.Pp
В заключение, мы создаем и форматируем 8 ГБ раздел
.Cm freebsd-ufs
для корневой файловой системы, оставляя остальную часть устройства свободнойДля дополнительных файловых систем:
.Bd -literal -offset indent
/sbin/gpart add -s 8G -t freebsd-ufs ada0
/sbin/newfs -Uj /dev/ada0p3
.Ed
.Ss MBR
В этом примере мы будем форматировать
.Pa ada0
с использованием схемы MBR и создадим один раздел, который мы подразделим
используя традиционную
.Bx
таблицу разделов (disklabel).
.Pp
Сначала создаем таблицу разделов, а также один раздел размером 64 ГБ с
выравниванием в 4 кБ, затем отметим этот раздел как активный (загрузочный)
и установим загрузочный код первой стадии:
.Bd -literal -offset indent
/sbin/gpart create -s MBR ada0
/sbin/gpart add -t freebsd -s 64G -a 4k ada0
/sbin/gpart set -a active -i 1 ada0
/sbin/gpart bootcode -b /boot/boot0 ada0
.Ed
.Pp
Затем создаем disklabel в этом разделе
.Po
.Dq slice
по терминологии disklabel
.Pc
с возможностью до 20 разделов:
.Bd -literal -offset indent
/sbin/gpart create -s BSD -n 20 ada0s1
.Ed
.Pp
Далее создаем 8 ГБ корневой раздел и 4 ГБ раздел подкачки (swap):
.Bd -literal -offset indent
/sbin/gpart add -t freebsd-ufs -s 8G ada0s1
/sbin/gpart add -t freebsd-swap -s 4G ada0s1
.Ed
.Pp
Наконец, устанавливаем соответствующий загрузочный код для
.Bx
метки (label):
.Bd -literal -offset indent
/sbin/gpart bootcode -b /boot/boot ada0s1
.Ed
.Ss Удаление разделов и уничтожение схемы разделения
Если при попытке уничтожить таблицу разделов появляется ошибка
.Em "Device busy"
необходимо помнить, что сначала нужно удалить все разделы с помощью
.Cm delete
действия.
В этом примере,
.Pa da0
имеет три раздела:
.Bd -literal -offset indent
/sbin/gpart delete -i 3 da0
/sbin/gpart delete -i 2 da0
/sbin/gpart delete -i 1 da0
/sbin/gpart destroy da0.Ed
.Pp
Вместо удаления каждого раздела и затем уничтожения схемы разделения, можно использовать опцию
.Fl F
вместе с командой
.Cm destroy
для удаления всех разделов перед уничтожением схемы разделения. Это эквивалентно предыдущему примеру:
.Bd -literal -offset indent
/sbin/gpart destroy -F da0
.Ed
.Ss Резервное копирование и восстановление
Создать резервную копию таблицы разделов с
.Pa da0 :
.Bd -literal -offset indent
/sbin/gpart backup da0 > da0.backup
.Ed
.Pp
Восстановить таблицу разделов из резервной копии на
.Pa da0 :
.Bd -literal -offset indent
/sbin/gpart restore -l da0 < /mnt/da0.backup
.Ed
.Pp
Клонировать таблицу разделов с
.Pa ada0
на
.Pa ada1
и
.Pa ada2 :
.Bd -literal -offset indent
/sbin/gpart backup ada0 | /sbin/gpart restore -F ada1 ada2
.Ed
.Sh СМОТРИ ТАКЖЕ
.Xr geom 4 ,
.Xr boot0cfg 8 ,
.Xr geom 8 ,
.Xr glabel 8 ,
.Xr gptboot 8
.Sh ИСТОРИЯ
Утилита
.Nm
впервые появилась в
.Fx 7.0 .
.Sh АВТОРЫ
.An Marcel Moolenaar Aq Mt marcel@FreeBSD.org
.Sh ОСОБЕННОСТИ
Тип раздела
.Em apple-zfs
(6a898cc3-1dd2-11b2-99a6-080020736631) также используется на платформах illumos/Solaris для томов ZFS.