.\" Авторские права (c) 2001-2002 Максим Евменкин <m_evmenkin@yahoo.com>
.\" Все права защищены.
.\"
.\" Перераспределение и использование в исходных и двоичных формах, с изменениями или без,
.\" разрешается при условии соблюдения следующих условий:
.\" 1. Перераспределения исходного кода должны сохранять вышеуказанное уведомление об авторских правах,
.\"    этот список условий и следующее отказ от ответственности.
.\" 2. Перераспределения в двоичной форме должны воспроизводить вышеуказанное уведомление об авторских правах,
.\"    этот список условий и следующее отказ от ответственности в
.\"    документации и/или других материалах, поставляемых с распределением.
.\"
.\" ЭТО ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЯЕТСЯ АВТОРОМ И УЧАСТНИКАМИ "КАК ЕСТЬ" И
.\" ЛЮБЫЕ ЯВНЫЕ ИЛИ ПОДРАЗУМЕВАЕМЫЕ ГАРАНТИИ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ ТЕМ, ПОДРАЗУМЕВАЕМЫМИ ГАРАНТИЯМИ
.\" КОММЕРЧЕСКОЙ ЦЕННОСТИ И ПРИГОДНОСТИ ДЛЯ ОПРЕДЕЛЁННОЙ ЦЕЛИ ОТКАЗЫВАЮТСЯ. НИ ПРИ КАКИХ ОБСТОЯТЕЛЬСТВАХ
.\" АВТОР ИЛИ УЧАСТНИКИ НЕ НЕСУТ ОТВЕТСТВЕННОСТИ ЗА ЛЮБЫЕ ПРЯМЫЕ, НЕПРЯМЫЕ, СЛУЧАЙНЫЕ,
.\" ОСОБЫЕ, ЭКЗЕМПЛЯРНЫЕ ИЛИ КОСВЕННЫЕ УЩЕРБЫ (ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ ТЕМ, ЗАТРАТЫ НА ЗАМЕЩЕНИЕ ТОВАРОВ
.\" ИЛИ УСЛУГ; ПОТЕРИ ИСПОЛЬЗОВАНИЯ, ДАННЫХ ИЛИ ПРИБЫЛИ; ИЛИ ПРЕРЫВАНИЕ БИЗНЕСА)
.\" ОДНАКО ВЫЗВАННЫЕ И ПО ЛЮБОЙ ТЕОРИИ ОТВЕТСТВЕННОСТИ, БУДЬ ТО ПО ДОГОВОРУ, СТРОГОЙ
.\" ОТВЕТСТВЕННОСТИ, ИЛИ ДЕЛИКТЕ (ВКЛЮЧАЯ ХАЛАТНОСТЬ ИЛИ ИНАЧЕ) ВОЗНИКШИЕ В ЛЮБОМ СЛУЧАЕ
.\" В СВЯЗИ С ИСПОЛЬЗОВАНИЕМ ЭТОГО ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ, ДАЖЕ ЕСЛИ БЫЛИ ПРЕДУПРЕЖДЕНЫ О ВОЗМОЖНОСТИ ТАКОГО УЩЕРБА.
.\"
.\" $Id: hccontrol.8,v 1.6 2003/08/06 21:26:38 max Exp $
.\"
.Dd 3 мая 2020 года
.Dt HCCONTROL 8
.Os
.Sh НАЗВАНИЕ
.Nm hccontrol
.Nd Утилита конфигурации Bluetooth HCI
.Sh СИНТАКСИС
.Nm
.Op Fl hN
.Op Fl n Ar Имя_узла_HCI.Ar command
.Op Ar параметры ...
.Sh ОПИСАНИЕ
Команда
.Nm
подключается к указанному узлу Netgraph типа
.Dv HCI
или к первому найденному, если ни один не указан, и пытается отправить указанную
команду узлу Netgraph HCI или связанному устройству Bluetooth.
Команда
.Nm
будет выводить результаты на стандартный вывод и сообщения об ошибках на стандартный вывод ошибок.
.Pp
Опции следующие:
.Bl -tag -width indent
.It Fl h
Отобразить сообщение о использовании и выйти.
.It Fl N
Показать Bluetooth адреса в виде чисел.
Обычно
.Nm
пытается разрешить Bluetooth адреса и отображать их символически.
.It Fl n Ar имя_узла_HCI
Подключиться к указанному узлу Netgraph HCI.
.It Ar command
Одна из поддерживаемых команд (см. ниже).
Специальная команда
.Cm help
может быть использована для получения списка всех поддерживаемых команд.
Чтобы получить больше информации о конкретной команде, используйте
.Cm help Ar команда .
.It Ar параметры
Один или несколько необязательных разделённых пробелами параметров команды.
Многие команды требуют адрес удалённого устройства в качестве одного из параметров.
Адрес удалённого устройства может быть указан как BD_ADDR или имя.
Если указано имя, то команда
.Nm
попытается разрешить имя через
.Xr bt_gethostbyname 3 .
.El
.Sh КОМАНДЫ
В настоящее время поддерживаемые команды HCI в
.Nm
следующие:
.Pp
.Bl -tag -width 40n -offset indent -compact
.It Cm Inquiry
.It Cm Create_Connection
.It Cm Disconnect
.It Cm Add_SCO_Connection
.It Cm Change_Connection_Packet_Type
.It Cm Remote_Name_Request
.It Cm Read_Remote_Supported_Features
.It Cm Read_Remote_Version_Information
.It Cm Read_Clock_Offset
.It Cm Role_Discovery
.It Cm Switch_Role.It Cm Read_Link_Policy_Settings - .It Cm Читать_Настройки_Политики_Связи
.It Cm Write_Link_Policy_Settings - .It Cm Записать_Настройки_Политики_Связи
.It Cm Reset - .It Cm Сброс
.It Cm Read_Pin_Type - .It Cm Читать_Тип_Pin
.It Cm Write_Pin_Type - .It Cm Записать_Тип_Pin
.It Cm Read_Stored_Link_Key - .It Cm Читать_Сохраненный_Ключ_Связи
.It Cm Write_Stored_Link_Key - .It Cm Записать_Сохраненный_Ключ_Связи
.It Cm Delete_Stored_Link_Key - .It Cm Удалить_Сохраненный_Ключ_Связи
.It Cm Change_Local_Name - .It Cm Изменить_Локальное_Имя
.It Cm Read_Local_Name - .It Cm Читать_Локальное_Имя
.It Cm Read_Connection_Accept_Timeout - .It Cm Читать_Таймаут_Приема_Соединения
.It Cm Write_Connection_Accept_Timeout - .It Cm Записать_Таймаут_Приема_Соединения
.It Cm Read_Page_Timeout - .It Cm Читать_Таймаут_Поиска_Страницы
.It Cm Write_Page_Timeout - .It Cm Записать_Таймаут_Поиска_Страницы
.It Cm Read_Scan_Enable - .It Cm Читать_Включение_Сканирования
.It Cm Write_Scan_Enable - .It Cm Записать_Включение_Сканирования
.It Cm Read_Page_Scan_Activity - .It Cm Читать_Активность_Сканирования_Страницы
.It Cm Write_Page_Scan_Activity - .It Cm Записать_Активность_Сканирования_Страницы
.It Cm Read_Inquiry_Scan_Activity - .It Cm Читать_Активность_Сканирования_Запросов
.It Cm Write_Inquiry_Scan_Activity - .It Cm Записать_Активность_Сканирования_Запросов
.It Cm Read_Authentication_Enable - .It Cm Читать_Включение_Аутентификации
.It Cm Write_Authentication_Enable - .It Cm Записать_Включение_Аутентификации
.It Cm Read_Encryption_Mode - .It Cm Читать_Режим_Шифрования
.It Cm Write_Encryption_Mode - .It Cm Записать_Режим_Шифрования
.It Cm Read_Class_Of_Device - .It Cm Читать_Класс_Устройства
.It Cm Write_Class_Of_Device - .It Cm Записать_Класс_Устройства
.It Cm Read_Voice_Settings - .It Cm Читать_Настройки_Голоса
.It Cm Write_Voice_Settings - .It Cm Записать_Настройки_Голоса
.It Cm Read_Number_Broadcast_Retransmissions - .It Cm Читать_Количество_Повторных_Трансляций
.It Cm Write_Number_Broadcast_Retransmissions - .It Cm Записать_Количество_Повторных_Трансляций
.It Cm Read_Hold_Mode_Activity - .It Cm Читать_Активность_Режима_Удержания
.It Cm Write_Hold_Mode_Activity - .It Cm Записать_Активность_Режима_Удержания
.It Cm Read_SCO_Flow_Control_Enable - .It Cm Читать_Включение_Управления_Потоком_SCO
.It Cm Write_SCO_Flow_Control_Enable - .It Cm Записать_Включение_Управления_Потоком_SCO
.It Cm Read_Link_Supervision_Timeout - .It Cm Читать_Таймаут_Контроля_Связи
.It Cm Write_Link_Supervision_Timeout - .It Cm Записать_Таймаут_Контроля_Связи
.It Cm Read_Page_Scan_Period_Mode - .It Cm Читать_Режим_Периода_Сканирования_Страницы
.It Cm Write_Page_Scan_Period_Mode - .It Cm Записать_Режим_Периода_Сканирования_Страницы
.It Cm Read_Page_Scan_Mode - .It Cm Читать_Режим_Сканирования_Страницы
.It Cm Write_Page_Scan_Mode - .It Cm Записать_Режим_Сканирования_Страницы
.It Cm Read_LE_Host_Support - .It Cm Читать_Поддержку_LE_Host
.It Cm Write_LE_Host_Support - .It Cm Записать_Поддержку_LE_Host
.It Cm Read_Local_Version_Information - .It Cm Читать_Информацию_О_Локальной_Версии
.It Cm Read_Local_Supported_Commands - .It Cm Читать_Поддерживаемые_Локальные_Команды
.It Cm Read_Local_Supported_Features - .It Cm Читать_Поддерживаемые_Локальные_Функции
.It Cm Read_Buffer_Size - .It Cm Читать_Размер_Буфера
.It Cm Read_Country_Code - .It Cm Читать_Код_Страны
.It Cm Read_BD_ADDR - .It Cm Читать_BD_ADDR
.It Cm Read_Failed_Contact_Counter - .It Cm Читать_Счетчик_Неудачных_Соединений
.It Cm Reset_Failed_Contact_Counter - .It Cm Сброс_Счетчика_Неудачных_Соединений
.It Cm Get_Link_Quality - .It Cm Получить_Качество_Связи
.It Cm Read_RSSI - .It Cm Читать_RSSI
.It Cm LE_Enable - .It Cm LE_Включить
.It Cm LE_Read_Local_Supported_Features - .It Cm LE_Читать_Поддерживаемые_Локальные_Функции
.It Cm LE_Set_Advertising_Parameters
.It Cm LE_Read_Advertising_Physical_Channel_Tx_Power
.It Cm LE_Set_Advertising_Data
.It Cm LE_Set_Scan_Response_Data
.It Cm LE_Set_Advertising_Enable
.It Cm LE_Set_Scan_Parameters
.It Cm LE_Set_Scan_Enable
.It Cm LE_Read_Supported_States
.It Cm LE_Read_Buffer_Size
.It Cm LE_Scan
.It Cm LE_Read_White_List_Size
.It Cm LE_Clear_White_List
.It Cm LE_Add_Device_To_White_List
.It Cm LE_Remove_Device_From_White_List
.It Cm LE_Connect
.It Cm LE_Read_Channel_Map
.It Cm LE_Read_Remote_Features
.It Cm LE_Rand
.El
.Pp
Текущие поддерживаемые команды узла в
.Nm
являются:
.Pp
.Bl -tag -width 40n -offset indent -compact
.It Cm Read_Node_State
.It Cm Initialize
.It Cm Read_Debug_Level
.It Cm Write_Debug_Level
.It Cm Read_Node_Buffer_Size
.It Cm Read_Node_BD_ADDR
.It Cm Read_Node_Features
.It Cm Read_Node_Stat
.It Cm Reset_Node_Stat
.It Cm Flush_Neighbor_Cache
.It Cm Read_Neighbor_Cache
.It Cm Read_Connection_List
.It Cm Read_Node_Link_Policy_Settings_Mask
.It Cm Write_Node_Link_Policy_Settings_Mask
.It Cm Read_Node_Packet_Mask
.It Cm Write_Node_Packet_Mask
.It Cm Read_Node_Role_Switch
.It Cm Write_Node_Role_Switch
.It Cm Read_Node_List
.El
.Sh СТАТУС ВЫХОДА
.Ex -std
.Sh ПРИМЕРЫ
Сделать Bluetooth LE хост, ubt0hci, доступным для сканирования с помощью
.Xr hccontrol 8 команд:
.Bd -literal -offset indent
hccontrol -n ubt0hci le_set_advertising_enable disable
hccontrol -n ubt0hci le_set_advertising_param
hccontrol -n ubt0hci le_read_advertising_channel_tx_power
hccontrol -n ubt0hci le_set_advertising_data
hccontrol -n ubt0hci le_set_scan_response -n FBSD_Host
hccontrol -n ubt0hci le_set_advertising_enable enable
.Ed
.Sh СМОТРИ ТАКЖЕ
.Xr bluetooth 3 ,
.Xr netgraph 3 ,
.Xr netgraph 4 ,
.Xr ng_hci 4
.Sh АВТОРЫ
.An Максим Евменкин Aq Mt m_evmenkin@yahoo.com
.Sh ОШИБКИ
Скорее всего есть.
Пожалуйста, сообщите, если найдете.