.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.\" Copyright (c) 2022 Michael Tuexen <tuexen@FreeBSD.org>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd June 30, 2022
.Dt TCPSSO 8
.Os
.Sh ИМЯ
.Nm tcpsso
.Nd устанавливает параметр сокета на конечной точке TCP
.Sh КРАТКИЙ ОБЗОР
.Nm
.Fl i Ar id
.Op Ar level
.Ar optname
.Ar optval
.Nm
.Fl a
.Op Ar level
.Ar optname
.Ar optval
.Nm
.Fl C Ar cc-algo
.Op Fl S Ar stack
.Op Fl s Ar state
.Op Ar level
.Ar optname
.Ar optval
.Nm
.Op Fl C Ar cc-algo
.Fl S Ar stack
.Op Fl s Ar state
.Op Ar level
.Ar optname
.Ar optval
.Nm
.Op Fl C Ar cc-algo
.Op Fl S Ar stack
.Fl s Ar state
.Op Ar level
.Ar optname
.Ar optval
.Sh ОПИСАНИЕ
.Nm
команда применяет
.Ar level
параметр уровневой розетки с названием
.Ar optname
и значением
.Ar optval
на конечной точке TCP из командной строки.
.Pp
Конечные точки TCP в
.Dv TIME_WAIT
состоянии не могут быть обработаны с помощью
.Nm .
Конечные точки TCP в
.Dv SYN_RCVD
состоянии могут быть обработаны только в том случае, если их предыдущее состояние было
.Dv SYN_SENT .
.Pp
.Op Ar level
может быть задано в виде неотрицательного числа или символического имени, как
.Dv SOL_SOCKET ,
.Dv IPPROTO_IP ,
.Dv IPPROTO_IPV6 ,
или
.Dv IPPROTO_TCP .
Если не указано,
.Nm
выводит уровень из
.Ar optname ,
если он указан как символьное имя.
Если это не так, используется
.Dv IPPROTO_TCP .
.Pp
.Ar optname
может быть задано в виде неотрицательного числа или символического имени, как
.Dv SO_DEBUG ,
.Dv IP_TOS ,
.Dv IPV6_TCLASS ,
.Dv TCP_LOG ,
.Dv TCP_CONGESTION ,
или
.Dv TCP_FUNCTION_BLK .
.Pp
.Ar optval
может быть в виде целого значения, которое будет преобразовано в двоичное значение и
передано как значение типа int.
Если оно не может быть проанализировано как целое значение, оно будет обработано как строка.
Если
.Ar optname
равно
.Dv TCP_FUNCTION_BLK ,
тогда
.Ar optval
преобразуется в
.Vt "struct tcp_function_set" .
.Pp
Если
.Fl i Ar id
указывается, тогда
.Nm
применит параметр сокета к конечной точке TCP с помощью
.Dv inp_gencnt
предоставленного в качестве
.Ar id .
.Dv inp_gencnt
для существующих конечных точек TCP можно определить с помощью
.Xr sockstat 1 .
.Pp
Если
.Fl a
указывается, тогда
.Nm
применит опцию socket ко всем конечным точкам TCP с учетом вышеуказанных
ограничений состояния.
.Pp
Если
.Fl C Ar cc-algo
указывается, тогда
.Nm
применит параметр socket ко всем конечным точкам TCP, используя
алгоритм управления перегрузкой TCP
.Ar cc-algo
и с учетом вышеуказанных ограничений состояния.
.Pp
Если
.Fl S Ar stack
указывается, тогда
.Nm
применит параметр socket ко всем конечным точкам TCP, используя стек TCP
.Ar stack
и с учетом вышеуказанных ограничений состояния.
.Pp
Если
.Fl s Ar state
указывается, тогда
.Nm
будет применен параметр socket ко всем конечным точкам TCP, находящимся в состоянии
.Ar state .
.Ar state
является одним из
.Dv CLOSED ,
.Dv LISTEN ,
.Dv SYN_SENT ,
.Dv SYN_RCVD ,
.Dv ESTABLISHED ,
.Dv CLOSE_WAIT ,
.Dv FIN_WAIT_1 ,
.Dv CLOSING ,
.Dv LAST_ACK ,
.Dv FIN_WAIT_2 .
Использование
.Dv SYN_RCVD
применяется только к конечным точкам TCP в состоянии
.Dv SYN_RCVD
если их предыдущее состояние было
.Dv SYN_SENT .
.Pp
Если несколько из
.Fl C Ar cc-algo ,
.Fl S Ar stack ,
и
.Fl s Ar state
указаны,
.Nm
будет применен параметр socket ко всем конечным точкам TCP, не находящимся в
состоянии
.Dv TIME_WAIT
и использование алгоритма контроля перегрузки
.Ar cc-algo ,
находясь в состоянии
.Ar state ,
и использование стека TCP
.Ar stack ,
если указано.
.Pp
Если ни один из
.Fl a ,
.Fl C ,
.Fl S ,
или
.Fl s
параметров не указывается, тогда параметр
.Fl i
должно быть указан.
.Sh СТАТУС ВЫХОДА
.Ex -std
.Sh ПРИМЕРЫ
Чтобы диагностировать проблему с конкретным TCP-соединением, подключенным к
.Xr sshd 8 ,
сначала определите его
.Dv inp_gencnt
используя
.Xr sockstat 1 :
.Bd -literal -offset indent
# sockstat -4 -c -i -p 22 -P tcp -q
root     sshd       827   4  tcp4 \e
	192.168.1.1:22        192.168.1.2:53736     435
.Ed
.Pp
Затем используйте следующую команду, чтобы включить на нем запись в черный ящик:
.Bd -literal -offset indent
# tcpsso -i 435 TCP_LOG 4
.Ed
.Pp
Чтобы переключить все конечные точки TCP с использования стека freebsd на стек rack, используйте:
.Bd -literal -offset indent
# tcpsso -S freebsd TCP_FUNCTION_BLK rack
.Ed
.Pp
Следующая команда настроит модуль управления перегрузкой всех
конечных точек TCP, использующих cubic в качестве алгоритма управления перегрузкой, на алгоритм управления
перегрузкой newreno:
.Bd -literal -offset indent
# tcpsso -C cubic TCP_CONGESTION newreno
.Ed
.Sh СМОТРИТЕ ТАКЖЕ
.Xr sockstat 1 ,
.Xr setsockopt 2 ,
.Xr tcp 4 ,
.Xr tcp_functions 9
.Sh ИСТОРИЯ
.Nm
команда впервые появилась в
.Fx 14 .
.Sh АВТОРЫ
.An Майкл Тьюксен Aq Mt tuexen@FreeBSD.org
