.\"
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or https://opensource.org/licenses/CDDL-1.0.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\"
.\" Copyright (c) 2009 Sun Microsystems, Inc. All Rights Reserved.
.\" Copyright 2011 Joshua M. Clulow <josh@sysmgr.org>
.\" Copyright (c) 2011, 2019 by Delphix. All rights reserved.
.\" Copyright (c) 2013 by Saso Kiselkov. All rights reserved.
.\" Copyright (c) 2014, Joyent, Inc. All rights reserved.
.\" Copyright (c) 2014 by Adam Stevko. All rights reserved.
.\" Copyright (c) 2014 Integros [integros.com]
.\" Copyright 2019 Richard Laager. All rights reserved.
.\" Copyright 2018 Nexenta Systems, Inc.
.\" Copyright 2019 Joyent, Inc.
.\"
.Dd June 30, 2019
.Dt ZFS-USERSPACE 8
.Os
.
.Sh ИМЯ
.Nm zfs-userspace
.Nd пространство для отображения и квоты набора данных ZFS
.Sh КРАТКИЙ ОБЗОР
.Nm zfs
.Cm userspace
.Op Fl Hinp
.Oo Fl o Ar field Ns Oo , Ns Ar field Oc Ns … Oc
.Oo Fl s Ar field Oc Ns …
.Oo Fl S Ar field Oc Ns …
.Oo Fl t Ar type Ns Oo , Ns Ar type Oc Ns … Oc
.Ar filesystem Ns | Ns Ar snapshot Ns | Ns Ar path
.Nm zfs
.Cm groupspace
.Op Fl Hinp
.Oo Fl o Ar field Ns Oo , Ns Ar field Oc Ns … Oc
.Oo Fl s Ar field Oc Ns …
.Oo Fl S Ar field Oc Ns …
.Oo Fl t Ar type Ns Oo , Ns Ar type Oc Ns … Oc
.Ar filesystem Ns | Ns Ar snapshot Ns | Ns Ar path
.Nm zfs
.Cm projectspace
.Op Fl Hp
.Oo Fl o Ar field Ns Oo , Ns Ar field Oc Ns … Oc
.Oo Fl s Ar field Oc Ns …
.Oo Fl S Ar field Oc Ns …
.Ar filesystem Ns | Ns Ar snapshot Ns | Ns Ar path
.
.Sh ОПИСАНИЕ
.Bl -tag -width ""
.It Xo
.Nm zfs
.Cm userspace
.Op Fl Hinp
.Oo Fl o Ar field Ns Oo , Ns Ar field Oc Ns … Oc
.Oo Fl s Ar field Oc Ns …
.Oo Fl S Ar field Oc Ns …
.Oo Fl t Ar type Ns Oo , Ns Ar type Oc Ns … Oc
.Ar filesystem Ns | Ns Ar snapshot Ns | Ns Ar path
.Xc
Отображает пространство, занимаемое каждым пользователем, и квоты для него в указанной
файловой системе,
снапшоте или пути.
Если указан путь, будет использоваться файловая система, содержащая этот путь.
Это соответствует
.Sy userused@ Ns Em user ,
.Sy userobjused@ Ns Em user ,
.Sy userquota@ Ns Em user ,
and
.Sy userobjquota@ Ns Em user
properties.
.Bl -tag -width "-S field"
.It Fl H
Не печатает заголовки, использует выходные данные, разделенные табуляцией.
.It Fl S Ar field
Выполняет сортировку по этому полю в обратном порядке.
Смотрите
.Fl s .
.It Fl i
Преобразуйте SID в POSIX ID.
POSIX ID может быть недолговечным, если не существует сопоставления.
Обычные интерфейсы POSIX
.Pq, такие как Xr stat 2 , Nm ls Fl l , выполняют это преобразование, поэтому параметр
.Fl i
позволяет выводить данные из
.Nm zfs Cm userspace
для непосредственного сравнения с этими утилитами.
Однако,
.Fl i
может привести к путанице, если некоторые файлы были созданы пользователем SMB до того как было установлено сопоставление имен SMB с POSIX.
В таком случае некоторые файлы будут принадлежать объекту SMB, а некоторые
- объекту POSIX.
Однако, параметр
.Fl i
сообщит, что объект POSIX имеет общее использование и квоту для обоих.
.It Fl n
Выводит числовой идентификатор вместо имени пользователя/группы.
.It Fl o Ar field Ns Oo , Ns Ar field Oc Ns …
Отображает только указанные поля из следующего набора:
.Sy type ,
.Sy name ,
.Sy used ,
.Sy quota .
По умолчанию отображаются все поля.
.It Fl p
Использует точный
.Pq поддающийся разбору
числовой вывод.
.It Fl s Ar field
Сортирует выходные данные по этому полю.
Флаги
.Fl s
и
.Fl S
могут быть заданы несколько раз для сортировки сначала по одному полю, затем по
другому.
По умолчанию это
.Fl s Sy type Fl s Sy name .
.It Fl t Ar type Ns Oo , Ns Ar type Oc Ns …
Выводит только указанные типы из следующего набора:
.Sy all ,
.Sy posixuser ,
.Sy smbuser ,
.Sy posixgroup ,
.Sy smbgroup .
По умолчанию это
.Fl t Sy posixuser , Ns Sy smbuser .
Значение по умолчанию можно изменить, включив в него типы групп.
.El
.It Xo
.Nm zfs
.Cm groupspace
.Op Fl Hinp
.Oo Fl o Ar field Ns Oo , Ns Ar field Oc Ns … Oc
.Oo Fl s Ar field Oc Ns …
.Oo Fl S Ar field Oc Ns …
.Oo Fl t Ar type Ns Oo , Ns Ar type Oc Ns … Oc
.Ar filesystem Ns | Ns Ar snapshot
.Xc
Отображает пространство, занимаемое каждой группой в указанной
файловой системе или снапшоте, и установленные для нее квоты.
Эта подкоманда идентична
.Cm userspace ,
за исключением того, что по умолчанию отображаются следующие типы
.Fl t Sy posixgroup , Ns Sy smbgroup .
.It Xo
.Nm zfs
.Cm projectspace
.Op Fl Hp
.Oo Fl o Ar field Ns Oo , Ns Ar field Oc Ns … Oc
.Oo Fl s Ar field Oc Ns …
.Oo Fl S Ar field Oc Ns …
.Ar filesystem Ns | Ns Ar snapshot Ns | Ns Ar path
.Xc
Отображает пространство, занимаемое каждым проектом в указанной
файловой системе или снапшоте, и установленные для него квоты.
Эта подкоманда идентична
.Cm userspace ,
за исключением того, что идентификатор проекта - это цифра, а не название.
Так что не нужен ни тот, ни другой параметр
.Fl i
для преобразования SID в POSIX ID ни
.Fl n
для числового идентификатора, ни
.Fl t
для типов.
.El
.
.Sh СМОТРИТЕ ТАКЖЕ
.Xr zfsprops 7 ,
.Xr zfs-set 8
